### ISSUE TITLE
Crash in al_show_native_file_dialog if display is NULL (Windows)

### ISSUE THREAD

**Issue by pedro-w** [liballeg/allegro5#1005]
The [docs ](https://liballeg.org/a5docs/trunk/native_dialog.html#al_show_native_file_dialog) say that it's OK to pass a NULL display to `al_show_native_file_dialog` but, on Windows at least, the display parameter is dereferenced without checks and this causes a crash.
See also: https://www.allegro.cc/forums/revision/1040364
Example where it is dereferenced: (happens when opening a folder)
https://github.com/liballeg/allegro5/blob/d7757184d335d400460808eff8e0d19c9f557673/addons/native_dialog/win_dialog.c#L79

**Comment by fatcerberus** [comment]
That’s weird because I’ve been passing `NULL` to this function for many years and have never had a crash because of it on any platform:
https://github.com/fatcerberus/minisphere/blob/master/src/minisphere/main.c#L247

**Comment by pedro-w** [comment]
It does the right thing when opening a file but not a directory
https://github.com/liballeg/allegro5/blob/d7757184d335d400460808eff8e0d19c9f557673/addons/native_dialog/win_dialog.c#L180
I think from your code you're opening a file? In which case should be OK.
I left the description a bit vague because I haven't been through it all yet in case there's anywhere else that needs fixing.
