### ISSUE TITLE
Tools in the 4.4.3 release are broken

### ISSUE THREAD

**Issue by jwrdegoede** [liballeg/allegro5#1027]
The 4.4.3 release seems to have accidentally? dropped:

#include "plugins.h"

From tools/datedit.c, leading to the tools missing handling of bitmap, etc. files breaking them. Re-adding the include:

```
--- allegro-4.4.3/tools/datedit.c
+++ allegro-4.4.3/tools/datedit.c
@@ -107,6 +107,8 @@
    int done, i;
    AL_CONST char *prop_types;
 
+   #include "plugins.h"
+
    do {
       done = TRUE;

```

Fixes this.

**Comment by fatcerberus** [comment]
Apparently this was intentional:
https://github.com/liballeg/allegro5/commit/fd821138e1256edbaa106f4650f83956806f71da

**Comment by jwrdegoede** [comment]
fd82113 claims the header does not exist, this is not true, the header is auto-generated, at least when using the cmake buildsys. It looks to me like the author of that commit tried to fix a build-error with some other buildsys, but did it the wrong way.

The autogenerated plugin.h contains the tools/plugins/*.inc snippets which look like this:

```
/* registration code for setting up the alpha channel plugin */
{
   extern DATEDIT_MENU_INFO datalpha_menu1;
   extern DATEDIT_MENU_INFO datalpha_menu2;

   datedit_register_menu(&datalpha_menu1);
   datedit_register_menu(&datalpha_menu2);
}
```

Without this the plugins are not registered and e.g. selecting "File -> Read Bitmap" in grabber throws this error: 

```
You seem to have removed the BITMAP plugin!

Not good ...
```

Restoring the include fixes this.

Note the dat tool is also broken, under Linux it now segfaults when executing: "dat -a -t bmp foo.dat bar.pcx", see: https://bugzilla.redhat.com/show_bug.cgi?id=1682921

Restoring the include also fixes this crash.

**Comment by SiegeLord** [comment]
Ok, I'll look into it and release 4.4.3.1 with the fix.

**Comment by SiegeLord** [comment]
4.4.3.1 is now released, and this should be fixed. Thanks for reporting this!
