### ISSUE TITLE
Please migrate to Python 3

### ISSUE THREAD

**Issue by gusnan** [liballeg/allegro5#1079]
Please migrate to Python 3 - Debian is dropping Python 2 support during the current release cycle:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936116

And upstream:

https://pythonclock.org/

I have done some basic tests myself, but haven't yet managed to make the test system work properly with Python 3.

Thanks for all your work on Allegro!

**Comment by allefant** [comment]
Ha, we should have done that a long time ago. Anyway, should be very easy.

**Comment by SiegeLord** [comment]
Yeah, we're happy to do it. @gusnan, could you clarify what Python 3 support means for Debian? Is `/usr/bin/python` becoming Python 3? Do we need to use `/usr/bin/python3`?

**Comment by gusnan** [comment]
No, `/usr/bin/python` is Python2, and that will not become 3 in Debian - please use `/usr/bin/python3`.
