### ISSUE TITLE
al_get_display_refresh_rate() on Windows (tested on Windows 10, two different PCs)

### ISSUE THREAD

**Issue by mikiZX** [liballeg/allegro5#1100]
Issue: the function returns 0 (zero) when using windowed mode though calling Windows.h function EnumDisplaySettings that provides the refresh rate of the monitor returns correctly the actual monitor refresh rate even from the windowed thread.

output of ex_monitorinfo on PC where this was observed:

1 adapters found...
Adapter 0: (0, 0) - (1280, 1024)
Available fullscreen display modes:
Mode 0: 640 x 480, 60 Hz
Mode 1: 640 x 480, 72 Hz
Mode 2: 640 x 480, 75 Hz
Mode 3: 640 x 480, 59 Hz
Mode 4: 720 x 480, 56 Hz
Mode 5: 720 x 480, 60 Hz
Mode 6: 720 x 480, 72 Hz
Mode 7: 720 x 480, 75 Hz
Mode 8: 720 x 576, 56 Hz
Mode 9: 720 x 576, 60 Hz
Mode 10: 720 x 576, 72 Hz
Mode 11: 720 x 576, 75 Hz
Mode 12: 800 x 600, 56 Hz
Mode 13: 800 x 600, 60 Hz
Mode 14: 800 x 600, 72 Hz
Mode 15: 800 x 600, 75 Hz
Mode 16: 1024 x 768, 60 Hz
Mode 17: 1024 x 768, 70 Hz
Mode 18: 1024 x 768, 75 Hz
Mode 19: 1152 x 864, 75 Hz
Mode 20: 1280 x 720, 60 Hz
Mode 21: 1280 x 720, 75 Hz
Mode 22: 1280 x 720, 59 Hz
Mode 23: 1280 x 768, 60 Hz
Mode 24: 1280 x 768, 75 Hz
Mode 25: 1280 x 800, 60 Hz
Mode 26: 1280 x 800, 75 Hz
Mode 27: 1280 x 960, 60 Hz
Mode 28: 1280 x 960, 75 Hz
Mode 29: 1280 x 1024, 60 Hz
Mode 30: 1280 x 1024, 75 Hz

And ex_displayoptions output (png file):
https://imgur.com/a/pluFnRe 

Running the following code gives back output of 'refresh rate:0' (please disregard the FPS and  timer setup part):
//-----------------------------------------
const float FPS = 60;

int main(int argc, char* argv[])
{
ALLEGRO_DISPLAY* display = NULL;
ALLEGRO_EVENT_QUEUE* event_queue = NULL;
ALLEGRO_TIMER* timer = NULL;

bool running = true;
bool redraw = true;

// Initialize allegro
if (!al_init()) {
fprintf(stderr, "Failed to initialize allegro.\n");
return 1;
}

// Initialize the timer
timer = al_create_timer(1.0 / FPS);
if (!timer) {
fprintf(stderr, "Failed to create timer.\n");
return 1;
}

// Create the display
display = al_create_display(640, 480);
if (!display) {
fprintf(stderr, "Failed to create display.\n");
return 1;
}

fprintf(stderr, "refresh rate:%d", al_get_display_refresh_rate(display)); 

....
// ----------------------------------------------------

I am nowhere near offering a solution though it appears that both OpenGL and DirectX Allegro5 window managers, when they call the EnumDisplaySettings do not write the dmDisplayFrequency value anywhere.

Possibly I am not using the al_get_display_refresh_rate() function correctly?

NOTE: 
   -al_get_display_refresh_rate() does return the correct refresh rate value when run in FULLSCREEN mode.
   -all this on MS Visual Studio using Nuget packages of Allegro

**Comment by rmbeer** [comment]
certainly as you describe, it only works in full screen, because despite using a display, it is still a window, and the refresh belongs to the whole screen. Unless said refresh value is forced into the window for the function.
if I'm not mistaken I use al_get_monitor_info when I want to extract data related to the screen, even though it is only the size of the screen.
Maybe the refresh values should appear in both sides. In al_get_display_refresh_rate and ALLEGRO_MONITOR_INFO.

**Comment by mikiZX** [comment]
Thank you both! I am on Windows and was unable to compile Allegro from source so cannot test at this time. Will close this issue.
Your very kind help is much appreciated.
