### ISSUE TITLE
Slow down mouse movement

### ISSUE THREAD

**Issue by SergioMayo** [liballeg/allegro5#1104]
Hello everybody
Sorry for my bad English
I'm creating a video game like air hockey
I need to slow down the mouse movement on the game screen.
I couldn't find a function that does this

**Comment by SiegeLord** [comment]
Could you explain what you want to happen? Do you want the strikers to lag the mouse or something?

**Comment by SergioMayo** [comment]
Hello,
I use the mouse to move the player's handle in the air hockey game I'm creating.
the speed of the mouse is excessive, I need the mouse to be
slowed down in the airhockey window at the start of the game.
example:
maximum mouse speed = 20
is there a Allegro5 function to set the maximum mouse speed?

**Comment by SiegeLord** [comment]
You can do something like this:

```c
float handle_x = 0.;
float handle_y = 0.;

while(!quit)
{
	al_wait_for_event(queue, &event);
	switch (event.type) {
		case ALLEGRO_EVENT_MOUSE_AXES:
			handle_x += event.mouse.dx * speed_factor;
			handle_y += event.mouse.dy * speed_factor;
			break;
	}
}
```

`dx` and `dy` fields show how much the mouse moved for that event. Here I just scale them, but you can try doing something else like clipping them.

**Comment by SergioMayo** [comment]
it works perfectly. thank you!

**Comment by SergioMayo** [comment]
Problem solved
