### ISSUE TITLE
How to get float values from mouse functions

### ISSUE THREAD

**Issue by SergioMayo** [liballeg/allegro5#1105]
hello everyone, sorry for my bad english

I'm doing the air hockey video game. to move the player's handle I use the mouse.
the problem is that the mouse, mouse.dx (int) and mouse.dy (int) functions return integer values. for greater accuracy of the player vector I need to have float values.
the windows operating system returns float values for mouse functions.
how can i get float values with Allegro5 functions?
thank you

**Comment by SergioMayo** [comment]
Anyone have a solution?

**Comment by SergioMayo** [comment]
no reply
what a disappointment this site

**Comment by SiegeLord** [comment]
A5 doesn't expose floating values. I think we can probably add a new event with floating point values, or do the hack like we did with `al_set_mouse_wheel_precision`.

**Comment by SergioMayo** [comment]
This is interesting for the mouse wheel.
It would be great to have float by mouse movement.
I don't know how to do it

**Comment by SiegeLord** [comment]
I'm working on some code to add this feature:  #1107

**Comment by SergioMayo** [comment]
thanks, I'll wait.

**Comment by SergioMayo** [comment]
I saw that the update for mouse float events is available.
what should I do?
should I install Allegro 5.2.6?
I don't know the github site well, what should I do?
should I close the discussion?

**Comment by SiegeLord** [comment]
Once the pull request is merged, we'll shortly make a release, 5.2.6. We're still working on it.
