### ISSUE TITLE
GLSL alpha testing hurts performance on mobile GPUs

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#1120]
The default GLSL shader looks like this:
```c
static const char *default_glsl_pixel_source =
   "#ifdef GL_ES\n"
   "precision lowp float;\n"
   "#endif\n"
   "uniform sampler2D " ALLEGRO_SHADER_VAR_TEX ";\n"
   "uniform bool " ALLEGRO_SHADER_VAR_USE_TEX ";\n"
   "uniform bool " ALLEGRO_SHADER_VAR_ALPHA_TEST ";\n"
   "uniform int " ALLEGRO_SHADER_VAR_ALPHA_FUNCTION ";\n"
   "uniform float " ALLEGRO_SHADER_VAR_ALPHA_TEST_VALUE ";\n"
   "varying vec4 varying_color;\n"
   "varying vec2 varying_texcoord;\n"
   "\n"
   "bool alpha_test_func(float x, int op, float compare);\n"
   "\n"
   "void main()\n"
   "{\n"
   "  vec4 c;\n"
   "  if (" ALLEGRO_SHADER_VAR_USE_TEX ")\n"
   "    c = varying_color * texture2D(" ALLEGRO_SHADER_VAR_TEX ", varying_texcoord);\n"
   "  else\n"
   "    c = varying_color;\n"
   "  if (!" ALLEGRO_SHADER_VAR_ALPHA_TEST " || alpha_test_func(c.a, " ALLEGRO_SHADER_VAR_ALPHA_FUNCTION ", "
                          ALLEGRO_SHADER_VAR_ALPHA_TEST_VALUE "))\n"
   "    gl_FragColor = c;\n"
   "  else\n"
   "    discard;\n"
   "}\n"
   "\n"
   "bool alpha_test_func(float x, int op, float compare)\n"
   "{\n"
   // Note: These must be aligned with the ALLEGRO_RENDER_FUNCTION enum values.
   "  if (op == 0) return false;\n" // ALLEGRO_RENDER_NEVER
   "  else if (op == 1) return true;\n" // ALLEGRO_RENDER_ALWAYS
   "  else if (op == 2) return x < compare;\n" // ALLEGRO_RENDER_LESS
   "  else if (op == 3) return x == compare;\n" // ALLEGRO_RENDER_EQUAL
   "  else if (op == 4) return x <= compare;\n" // ALLEGRO_RENDER_LESS_EQUAL
   "  else if (op == 5) return x > compare;\n" // ALLEGRO_RENDER_GREATER
   "  else if (op == 6) return x != compare;\n" // ALLEGRO_RENDER_NOT_EQUAL
   "  else if (op == 7) return x >= compare;\n" // ALLEGRO_RENDER_GREATER_EQUAL
   "  return false;\n"
   "}\n";
```

When it comes to how low-end mobile GPUs with tiling renderers, it has two problems.

1. A significant number of branches are dedicated to alpha testing, which is a rather rarely used feature. Due to the way shaders work, they get executed and hurt performance even when alpha testing is completely unused.
2. The sole existence of `discard`, even in an unused branch, makes plenty of optimizations like early depth testing impossible.

With one of my games (which doesn't use alpha testing at all) on Mali-400, changing `discard;` to `gl_FragColor = vec4(0.0);` gives it a boost from 22FPS to 24FPS, and commenting out alpha testing stuff altogether moves it to 32FPS.

A possible solution would be to have a separate shader that gets used only when alpha testing is enabled.

**Comment by SiegeLord** [comment]
Here's a few options:

1. Manual opt-out of the uber shader
    1. Add a new display flag/option to disable the default shader (probably a good idea regardless).
    2. Add some functionality to `al_get_default_shader_source` or a new function to get a 'lite' version of the source. One way to do it is to use `#ifndef NO_ALPHA_TEST` and then force the user to do a `strcat` with `#define NO_ALPHA_TEST` before compiling the shader.
    3. On the affected platforms, the user can disable the default shader, and use a custom shader.

2. Like (1), but add a display option to use the lite shader.

3. Something more automatic than (1).
    1. We could start out by creating a lite-shader, and switch over to a non-lite shader if the associated alpha test API is set away from the default value.

I'd rather start with (1) and see how it goes. What do you think @dos1, does it match the way you use the default shaders?

**Comment by dos1** [comment]
Oh, I missed the question!

> On the affected platforms

All platforms are affected, but some are more than others. Sometimes it's just slightly increased power consumption, while sometimes it's a sharp FPS drop.

Usually in my games I'm just using default shader and switch to a custom one in rare cases where something needs to be drawn in a custom way. I think that's the most common way to use Allegro, so it seems to me that it's the best to keep the default shader as lightweight as possible.

Is alpha testing a commonly used feature? I've never used it in my games, and it seems like it was even broken for a while.

I'm not sure (1) and (2) are worth it at all. We want existing Allegro games to be performant on mobile without making the user care about explicitly disabling some rare features themselves. (3) sounds like a sensible approach to me - and it only has to care about default shader, there's no need for similar logic around custom shaders.
