### ISSUE TITLE
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave

### ISSUE THREAD

**Issue by ZweiEuro** [liballeg/allegro5#1121]
How can I go about debugging this ? 
Audio for me is working completely fine, and the program I was working on started perfectly fine as well just a moment ago. What can cause this error ?
Recently switched from VSCode to the snap version, which shouldn't make a difference since I compile via the CLI.

**Comment by SiegeLord** [comment]
What OS are you on? I found this on the internets: https://dev.to/setevoy/linux-alsa-lib-pcmdmixc1108sndpcmdmixopen-unable-to-open-slave-38on

**Comment by DasVoelkel** [comment]
I clicked your link, thought "Didn't i do this already? " and did it again, that spawned a whole lot of errors after rebooting (that it didn't find the snd_hda_intel or card 0 etc.) So i removed it again to see what the previous setup said exactly, and now it works again ... I can not for the life of me tell you why

**Comment by DasVoelkel** [comment]
And now it it again reproduces the error ... I seriously can't fathom what causes this.

**Comment by ZweiEuro** [comment]
out of date
