### ISSUE TITLE
al_load_font fails; al_load_ttf_font doesn't?

### ISSUE THREAD

**Issue by ZweiEuro** [liballeg/allegro5#1133]
I am trying to load DejaVuSans.ttf as a font, as i am reading this al_load_font should do the same thing al_load_ttf_font just that it's more general.

For some reason one failes, while the other one does not ?

I noticed this error in the [Agui library](https://github.com/jmasterx/Agui/blob/1bd1b32083a62b4b851c81d41cceb4e5be6d08b4/src/Agui/Backends/Allegro5/Allegro5Font.cpp#L71)

I am not sure why this fails, but if i try to call the al_load_font normally in my code, it still fails

```

 auto font = al_load_font("assets/DejaVuSans.ttf", 16, agui::FONT_DEFAULT_FLAGS);   // default flags = 0
    fprintf(stderr, "step \n");      // <---------- font = 0x0

    font = al_load_ttf_font("assets/DejaVuSans.ttf", 16, 0);
    fprintf(stderr, "step \n"); // <---------- font = 0x7fffcc010e20    (some memory pointer, as expected)

    defaultFont = agui::Font::load("assets/DejaVuSans.ttf", 16);
    fprintf(stderr, "step \n");     //<------ terminated by exception "Allegrot failed to load font"

```

**Comment by SiegeLord** [comment]
One possibility is that you're calling `al_init_font_addon` addon after `al_init_ttf_addon`, can you check if that's the case?

**Comment by DasVoelkel** [comment]
It's definetly not

**Comment by gusnan** [comment]
@DasVoelkel what OS? Is it with Allegro distributed with a Linux distribution?

**Comment by DasVoelkel** [comment]
Installed via pacman:
![1590256038_grim](https://user-images.githubusercontent.com/18036573/82737000-fbb12080-9d2d-11ea-96c8-1a8264ab3577.png)

**Comment by gusnan** [comment]
@DasVoelkel Alright - I am one of the maintainers of Allegro in Debian, in there we were affected by the fact that the packaging of that specific font was moved, so I had to update the Debian packaging of Allegro to follow that. But since your of archlinux, it is probably a different problem. (Also, since you get different results for al_load_font and al_load_ttf_font I guess it's a different problem.

**Comment by SiegeLord** [comment]
I guess it'd be helpful to have a program to reproduce this issue.

**Comment by ZweiEuro** [comment]
Oh sorry,
My project is here:
https://github.com/ZweiEuro/game
the framework of some stuff i am trying out in allegro.

and in it is a submodule of my agui fork:
https://github.com/ZweiEuro/agui

for the simple reason that the compile was broken and i wanted to fix it

**Comment by SiegeLord** [comment]
You never actually call `al_init_font_addon`. Call it before `al_init_ttf_addon` and the `al_load_font` will work. I still got a black screen in your game, but that's possibly unrelated.

**Comment by ZweiEuro** [comment]
Yeah that's unrelated ... Really? 
In that case i am super sorry! 
Shouls've RTFM more carefully

**Comment by ZweiEuro** [comment]
User error, I should read the manual better
