### ISSUE TITLE
Allegro file bug?

### ISSUE THREAD

**Issue by Keameng** [liballeg/allegro5#1138]
I was trying to close an ALLEGRO_FILE, and it gave me read access violation on closing a file.

`ALLEGRO_FILE* file = al_open_memfile((void*)some_font, some_font_length, "r");
ALLEGRO_FONT* font = al_load_ttf_font_f(file, nullptr, 20, 0);
al_destroy_font(font);
al_fclose(file);`

**Comment by SiegeLord** [comment]
That's expected, see the note here: https://liballeg.org/a5docs/trunk/font.html#al_load_ttf_font_f

> Note: The file handle is owned by the returned ALLEGRO_FONT object and must not be freed by the caller, as FreeType expects to be able to read from it at a later time.
