### ISSUE TITLE
Very high cpu usage with audio enabled.

### ISSUE THREAD

**Issue by ITotalJustice** [liballeg/allegro5#1142]
Hi, I've just started using allegro and so far it's been amazing to use, so thank you for that :smiley: 

I'm having an issue with the audio however. When I call `al_reserve_samples(2)` after installing audio, the cpu usage of my pc jumps to ~200% (pulseaudio is at 130% and my app is at 80%).
This is without playing any audio either.

Playing audio samples / streams works fine, but I don't understand that high cpu usage. I quickly tried a sdl mixer and i don't have such issue with it. I did initially think that playing the audio was the issue but as i explained above, just reserving samples causes cycles to spin.

I am on linux Kubuntu LTS, i've compiled allegro5 from the latest commit. All dependencies (and optional) are installed also.

[Here's example code](https://gist.github.com/ITotalJustice/a9cd115300f3945ee2c5f0553cf6a27b) that i made which causes the issue for me.
[Here's the sdl equivalent which works fine](https://gist.github.com/ITotalJustice/c19aa4108112d13cd8e5926fd6f5d5f2). 

EDIT: Here's a screenshot of the cpu usage from the example code above. 
![Screenshot_20200607_215010](https://user-images.githubusercontent.com/47043333/83979853-42477300-a909-11ea-8664-23bde21ae929.png)

**Comment by SiegeLord** [comment]
Can reproduce, amongst a few other issues with pulseaudio. For now, I recommend switching to ALSA backend while we figure out what broke You can do that by calling: `al_set_config_value(al_get_system_config(), "audio", "driver", "alsa");` before `al_install_audio`. You'll need to compile Allegro with ALSA support, which requires `libasound2-dev` installed.

Also, which Kubuntu LTS are you on? 2004 or 1804?

**Comment by ITotalJustice** [comment]
Thank you, it works for me :+1: 

I'm using 20.04.

**Comment by SiegeLord** [comment]
I pushed a change that appeared to fix this issue for me on my system: https://github.com/liballeg/allegro5/commit/57d6e6c762f6f3ed70fec4e2a3c2d9b7055dd20a

**Comment by ITotalJustice** [comment]
Works for me too, thank you very much!
