### ISSUE TITLE
Feature Request: FileSystem Object Name Only

### ISSUE THREAD

**Issue by pmprog** [liballeg/allegro5#1146]
According to the docs, since 5.1.5 al_get_fs_entry_name returns the full filename and path.

One feature that I find quite useful with the .NET FileInfo and DirectoryInfo classes is to just get the name of the object (without any paths), as well as getting the parent directory.

So some ideas:

- al_get_fs_entry_filename : returns just the filename (ie C:\Dos\boot.txt => boot.txt)
- al_get_fs_entry_parent_dir : returns an FS entry to the parent folder (ie, C:\Dos\boot.txt => FS(C:\Dos)

**Comment by SiegeLord** [comment]
Hmm, ostensibly that's what the `ALLEGRO_PATH` API is for:

```c
#include <allegro5/allegro.h>
#include <stdio.h>

int main()
{ 
  al_init();
  ALLEGRO_FS_ENTRY* fs = al_create_fs_entry("/tmp/foo.txt");
  printf("%s\n", al_get_fs_entry_name(fs));
  ALLEGRO_PATH* p = al_create_path(al_get_fs_entry_name(fs));
  printf("%s\n", al_get_path_filename(p));
  al_destroy_path(p);
}
```

**Comment by pmprog** [comment]
Okay, I feel a total moron. Don't know why i completely forgot about the paths header.
Thanks
