### ISSUE TITLE
The program crashes when drawing primitives

### ISSUE THREAD

**Issue by AlexanderZhirov** [liballeg/allegro5#1149]
I wrote game for the Linux system. The game is compiled, everything works fine! I tried to port the code to Windows. On Windows I use MinGW with the MSYS2 libraries. Under Windows, everything compiles successfully. Faced a problem that when drawing primitives my program crashes. Through debugging, I saw that the problem is in the mutex. The debugger stops at the empty mutex address and returns an error.
As soon as I commented on the drawing of primitives, my program stopped crashing. But as soon as the drawing process arises, the program crashes again.

[simplified source code](https://github.com/AlexanderZhirov/allegro_lib)
[Here is a demonstration of the problem](https://www.youtube.com/watch?v=QfHRai3xXV8)

**Comment by SiegeLord** [comment]
I don't see a `al_init_primitives_addon` anywhere.

**Comment by pedro-w** [comment]
I've had this problem in the past. `al_init_primitives_addon` doesn't seem to be necessary on all platforms so it's easy to forget to put it in. But it needs to be there!

**Comment by AlexanderZhirov** [comment]
Yes indeed. How I did not see a mistake. My head is already cooking poorly. Thank you very much, added initialization and it worked for me.
