### ISSUE TITLE
Supply modifiers with key events - Issue for pre-AT keyboards

### ISSUE THREAD

**Issue by SteveFosdick** [liballeg/allegro5#1151]
A pre-AT keyboard (for example IBM type F with original PC or XT) does not have the separate cursor and Home, End, Insert, Delete, PgUp and PgDown keys.  To support such a keyboard an application needs to look at the state of NumLock and thus treat the numeric keypad keys as numbers (if numlock is engaged) or as these other functions if it is not.

At the moment Allegro does not supply the key modifiers (shift state) with ALLEGRO_EVENT_KEY_DOWN and ALLEGRO_EVENT_KEY_UP events, only with ALLEGRO_EVENT_KEY_CHAR events.

Whilst one might expect an application to be only interested in the state of NumLock when processing ALLEGRO_EVENT_KEY_CHAR events this presents an issue when the application using Allegro is emulating another machine and needs the up/down events to emulate the keyboard on that machine.

Please populate the modifiers field of the key up/down events to resolve this.

**Comment by SiegeLord** [comment]
We now populate the modifiers, please verify that this actually works for this use case.

**Comment by SteveFosdick** [comment]
Thanks very much for doing this.  I have tried testing with the latest git master but this crashes with what I suspect is an unrelated error:
```
(b-em:18168): Gtk-WARNING **: 19:13:59.698: GtkSocket: only works under X11
(b-em:18168): Gdk-WARNING **: 19:13:59.700: ../gtk/gdk/x11/gdkwindow-x11.c:5633 drawable is not a native X11 window
```
then:
```
Thread 11 "gtk thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6ffd640 (LWP 18308)]
0x00007ffff68dca39 in ?? () from /usr/lib/libX11.so.6
(gdb) bt
#0  0x00007ffff68dca39 in  () at /usr/lib/libX11.so.6
#1  0x00007ffff68dd2a5 in _XFlush () at /usr/lib/libX11.so.6
#2  0x00007ffff68dff46 in _XGetRequest () at /usr/lib/libX11.so.6
#3  0x00007ffff68c38ab in _XGetWindowAttributes () at /usr/lib/libX11.so.6
#4  0x00007ffff68c3a9b in XGetWindowAttributes () at /usr/lib/libX11.so.6
#5  0x00007ffff718c367 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff6c7480a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff6c74980 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff70d2329 in gtk_widget_realize () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff718eea9 in gtk_socket_add_id () at /usr/lib/libgtk-3.so.0
#10 0x00007ffff7f3b597 in  () at /usr/lib/liballegro_dialog.so.5.2
#11 0x00007ffff6b6e764 in  () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff6b6e340 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff6bbc1d9 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff6b6cc03 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff6f7b21f in gtk_main () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff7f3a97e in  () at /usr/lib/liballegro_dialog.so.5.2
#17 0x00007ffff6b96511 in  () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff7dd73e9 in start_thread () at /usr/lib/libpthread.so.0
#19 0x00007ffff78c6293 in clone () at /usr/lib/libc.so.6
(gdb) 
```

**Comment by SteveFosdick** [comment]
Looking at the commit history I wonder if the segmentation fault is due to a conversion to GTK3 being in progress and not yet complete (and maybe not tested on Wayland).  Or is that complete now?

**Comment by SiegeLord** [comment]
Try it again, after https://github.com/liballeg/allegro5/commit/9bc4c366207cf36f7d21e66e81b6751e75498de5.

**Comment by gusnan** [comment]
For me this works. Thanks! Sorry for not testing using wayland - it completely slipped my mind.

**Comment by SteveFosdick** [comment]
Thanks, that works.
