### ISSUE TITLE
3rd party controller: crash while enumerating buttons, and corrupt instance name

### ISSUE THREAD

**Issue by arganoid** [liballeg/allegro5#1156]
This is with the latest version from Nuget- 5.2.6.

Connecting this controller https://www.amazon.co.uk/gp/product/B01HTBX9AK/all leads to the following problems:

1. Intermittent assert/crash while getting button names, during "info->button[i].name = ADD_STRING(can->name_button[i], default_name_button[i]);". The assert is ALLEGRO_ASSERT(dest != 0); in add_string. This was happening every time but now is not happening even though I have not recompiled.

2. The instance name returned by this controller is corrupt. In joystick_enum_callback, lpddi->tszInstanceName is "单⁂潊獹楴正넀肊￾￿Þ䵈瘴4쀀". This is not the case in the equivalent Allegro 4 code, where the name is "USB Joystick". Not sure that it's valid Chinese given some of the characters, including what looks like a Korean character at the end.

Attached: screenshots showing contents of lpddi in both Allegro 4 and 5.

Allegro 4
![Controller Allegro4](https://user-images.githubusercontent.com/11721687/90270844-c448a080-de52-11ea-9772-5adaa5c51cce.png)

Allegro 5
![Controller Allegro5](https://user-images.githubusercontent.com/11721687/90270845-c4e13700-de52-11ea-8f80-9f4a6140b254.png)

**Comment by pedro-w** [comment]
This looks like a unicode thing to me, `IDirectInput8::EnumDevices` is returning a `DIDEVICEINSTANCE` with Ansi chars when the code is expecting UTF-16 - even the VS debugger is getting it wrong. 
(if you convert the raw bytes `'U' 'S' 'B' ' ' 'J' 'o' 'y' 's' 't' 'i' 'c' 'k'` pretending they're UTF-16 you will get 单⁂潪獹楴正)

**Comment by pedro-w** [comment]
I suspect the issue is here:
https://github.com/liballeg/allegro5/blob/0b925657edc1c7b08c9cce4d3062dee74ea2f232/src/win/wjoydxnu.cpp#L1157-L1158
We're always explicitly requesting the Ansi version of the interface (__al_IID_IDirectInput8**A**) ,  even though this file is using Unicode for everything else. @SiegeLord, can you remind me if Allegro is/should be using Unicode everywhere now by default?
That should sort out the 'Chinese' name, not sure about the crashes. Unfortunately I don't have any hardware to test it with.

**Comment by pedro-w** [comment]
I've made a branch which might fix it, as I say I don't have a joystick and there may be other things that need fixing.
It's in https://github.com/pedro-w/allegro5.git, branch `issue-1156`
If you're happy to recompile Allegro it would be good to see if this solves anything.

**Comment by SiegeLord** [comment]
@pedro-w Yes, Allegro should be using Unicode everywhere (or more specifically, the prevailing style is to have both ANSI + Unicode paths, but Unicode is the one that's selected by default). I think your fix is good regardless. I'll try testing it with my controllers to see if I can reproduce the original issue.

**Comment by arganoid** [comment]
I have confirmed that the fix works.

**Comment by pedro-w** [comment]
Both the crashes and the corrupt name?

**Comment by arganoid** [comment]
I now have access to the original project again, and can confirm that with the patch from pedro-w, it doesn't crash and shows the correct name.

**Comment by beoran** [comment]
@pedro-w could you please make a pull request? Thanks!

**Comment by pedro-w** [comment]
@beoran Done. Ignore the first one; the content is the same, I just made the title a bit more informative in the second.
