### ISSUE TITLE
al_acknowledge_resize() throwing NSInternalInconsistencyException on OSX

### ISSUE THREAD

**Issue by JohnEarnest** [liballeg/allegro5#1168]
I'm using allegro 5.2.6.0 from homebrew, on osx 10.14.6 (mojave).

I'd like to use a resizable window with constraints for a minimum size. I've found that in some situations calling `al_acknowledge_resize()` will cause a crash something like the following:
```
[34145:94913800] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff349f42fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5f0c1a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff34a0de59 -[NSException raise] + 9
	3   AppKit                              0x00007fff31fb45ca -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 317
	4   AppKit                              0x00007fff31fc5a19 -[NSWindow _commonMinMaxSizeChanged] + 23
	5   liballegro.5.2.dylib                0x0000000100e85f8b -[ALOpenGLView windowWillUseStandardFrame:defaultFrame:] + 223
	6   AppKit                              0x00007fff32297fa9 -[NSWindow _standardFrame] + 482
	7   AppKit                              0x00007fff3236eb3f -[NSWindow isZoomed] + 41
	8   liballegro.5.2.dylib                0x0000000100e86dcc acknowledge_resize_display_win + 259
	9   a.out                               0x0000000100e22ea3 _al_mangled_main + 211
	10  liballegro.5.2.dylib                0x0000000100e89a26 call_user_main + 23
	11  liballegro.5.2.dylib                0x0000000100e89a0f call_user_main + 0
	12  Foundation                          0x00007fff36b975c2 __NSThread__start__ + 1194
	13  libsystem_pthread.dylib             0x00007fff60a832eb _pthread_body + 126
	14  libsystem_pthread.dylib             0x00007fff60a86249 _pthread_start + 66
	15  libsystem_pthread.dylib             0x00007fff60a8240d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

The following is a small reproduction case:

```
#include <allegro5/allegro5.h>
#define INIT_WIDTH  300
#define INIT_HEIGHT 200

int main() {
  al_init();
  al_set_new_display_flags(ALLEGRO_WINDOWED | ALLEGRO_RESIZABLE);

  ALLEGRO_EVENT_QUEUE* queue=al_create_event_queue();
  ALLEGRO_DISPLAY*     disp =al_create_display(INIT_WIDTH, INIT_HEIGHT);
  al_set_window_constraints(disp, INIT_WIDTH,INIT_HEIGHT,0,0);
  al_apply_window_constraints(disp, true);

  al_register_event_source(queue, al_get_display_event_source(disp));
  bool running=true;
  while(running) {
    ALLEGRO_EVENT event;
    al_wait_for_event(queue, &event);
    if (event.type == ALLEGRO_EVENT_DISPLAY_CLOSE) running=false;
    if (event.type == ALLEGRO_EVENT_DISPLAY_RESIZE) al_acknowledge_resize(disp);
    if (al_is_event_queue_empty(queue)) al_flip_display();
  }
  return 0;
}
```
compiled like:
```
gcc resizable.c $(pkg-config allegro-5 allegro_main-5 --libs --cflags)
```

Since the problem happens somewhat inconsistently, I'm not certain that this is minimal. To produce the behavior, I run the program, grab the bottom right corner of the display and wiggle it around for a few seconds. Sometimes it takes a few tries to produce the crash.

Let me know if there's any other information I can provide.

**Comment by pedro-w** [comment]
This is the key part: "NSWindow drag regions should only be invalidated on the Main Thread!" - we've fixed a series of errors like this over the years, because (I believe) Apple keep tightening up what can and can't be done on a non-main thread. Usually the solution is simple.
I'll look into it.

**Comment by pedro-w** [comment]
I was able to reproduce this with Allegro's ex_resize2 example, which I think performs the same operations as your code. Are you able to compile Allegro from source and test the proposed fix?

**Comment by JohnEarnest** [comment]
Thanks for the quick response!

I was able to build the master branch from source using clang and run the `ex_resize2` example, but I'm having difficulty reproducing the problem there. I did get a `Segmentation Fault: 11` while resizing once, but no Cocoa exceptions. How would you like me to proceed?

**Comment by pedro-w** [comment]
OK, I'll check with your code (I was just being lazy)
I was using the ['Main Thread Checker' tool](https://developer.apple.com/documentation/xcode/diagnosing_memory_thread_and_crash_issues_early) ([more info](https://bryce.co/main-thread-checker-configuration/)) to look for violations but, thinking about it, that usually only prints warnings rather than crashing the app. Maybe you've something else going on. I have seen a crash in ex_resize2 once but that came from the font rendering code (and I'll look in to that separately)
If you are using Xcode you can enable it from `Edit Scheme...` 
Or from the command line, try
```
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/usr/lib/libMainThreadChecker.dylib path/to/your/exe
```

**Comment by pedro-w** [comment]
Yes, I reproduced the crash with your code, though it does take a lot of attempts. Must be a subtle timing thing. However MTC found a couple more violations from `setContentMaxSize:` and `setContentMinSize:` so I'll fix those and see how we get on.

**Comment by pedro-w** [comment]
It's not crashing for me now, but I realize the threading stuff in osxgl.m has become quite messy, jumping in and out of the main thread. I will spend a bit of time and see if I can straighten it out a bit.

**Comment by JohnEarnest** [comment]
For whatever it's worth, I really appreciate the effort you're putting into tracking this problem down, @pedro-w!
Your responsiveness makes me feel great about choosing Allegro 5 for my project.

**Comment by pedro-w** [comment]
I've updated the PR; I found a few more cases where the wrong thread was being used. Probably these would not have caused crashes but better to fix, I think.
