### ISSUE TITLE
Add a flag to disable 16x16 hardware bitmap minimum

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#1210]
Hardware bitmaps currently seem to have a minimum size of 16x16 - loading an image smaller than this still creates a 16x16 hardware texture padded with black pixels, which interferes with shaders, among other things.  I assume this behavior is present for compatibility reasons; if one doesn't already exist, there should probably be a flag to disable it.

**Comment by pedro-w** [comment]
If we tiled the smaller image out to 16x16 (which would include partial tiles in the general case, of course) would that fix the problem with shaders and not need an extra flag?

**Comment by SiegeLord** [comment]
I think it's not the padding per se that's the problem, is that the UV coordinates need to take into account the difference between the backing texture size and the bitmap dimensions, even if the pixels are "valid" in some sense.

I have zero problems adding a system config entry for this.

**Comment by fatcerberus** [comment]
@SiegeLord's got it.

If this were just for a single game, I wouldn't have an issue working around the current behavior (I would probably use a tile atlas anyway at that point), but given the nature of [Sphere](https://github.com/fatcerberus/sphere), the behavior doesn't tend to make much sense to other developers, even when I explain the underlying reason for it.  Worse is that my Web implementation, [Oozaru](https://github.com/fatcerberus/oozaru), *doesn't* exhibit this since it internally uses GL textures directly, and I'm not too keen to emulate it there.
