### ISSUE TITLE
MSAA - DX flickering window on startup

### ISSUE THREAD

**Issue by jarroddavis6889** [liballeg/allegro5#1227]
This still is not yet fixed, sigh. #1153 

It is such a pain for me when trying to build allegro5 from scratch on windows. I use Delphi (Object Pascal). It would really be nice to get this fixed merged into a official release. It's been 3 years already. My custom build of allegro5 is old does not have all the current additions/fixes etc. I've not touched it once I actually got it to compile. I know if I go in and try to merge it's gonna break everything. Sigh.

**Comment by EdgarReynaldo** [comment]
@jarroddavis6889 Jarrod, sorry, I totally forgot about this issue. I'm still not clear on how to actually fix this, because the microsoft docs are so vague as to be almost unhelpful. I still have the old code I was using. To be clear, did my code fix the issue? It wasn't a proper fix so I never made a pull request.

**Comment by jarroddavis6889** [comment]
Yes, it fixed it. I have been using it for 3 years. No jitter on startup for me. I tried to merge with the master branch code sometime last year, but it somehow it got jacked up and would not run. But I think that was on me as I did not know what I was doing to be honest, hehe. If you like you can see it working well [here](https://github.com/tinyBigGAMES/GameVision/releases/download/v2.0.0/GameVision-2.0.0.zip).

**Comment by EdgarReynaldo** [comment]
I looked over the code and it seems sound. Initial tests worked fine. But NOTE : MSAA does NOT work on my integrated Intel GPU, only on my NVIDIA Graphics Card.

**Comment by EdgarReynaldo** [comment]
I will make a Pull request as soon as I figure out how to get rid of extranneous update commits from merging with 5.2.7

**Comment by EdgarReynaldo** [comment]
https://github.com/liballeg/allegro5/pull/1228

**Comment by jarroddavis6889** [comment]
@EdgarReynaldo many thanks!
