### ISSUE TITLE
Multiple windows open before main window opens

### ISSUE THREAD

**Issue by Lester702** [liballeg/allegro5#1244]
I've been following the docs to make a basic program and every time I run my program there are a bunch of windows that open before the main window actually opens

https://user-images.githubusercontent.com/63370028/117207983-9af5e900-adc2-11eb-9740-31ce92b6deb8.mp4

**Comment by SiegeLord** [comment]
This is https://github.com/liballeg/allegro5/issues/1227, most likely. We have a fix in the works. If you remove the `ALLEGRO_SAMPLES` lines, this should go away.

**Comment by Lester702** [comment]
> This is #1227, most likely. We have a fix in the works. If you remove the `ALLEGRO_SAMPLES` lines, this should go away.

That worked. Thank you
