### ISSUE TITLE
audio gain in video streaming add-on

### ISSUE THREAD

**Issue by chundermike** [liballeg/allegro5#1247]
Hi,

Is it possible to set the audio gain when playing a (ogv) video file using the video streaming add-on?

Thanks in advance,
Mike

**Comment by beoran** [comment]
You can start the video with the audio connected to a specific voice: https://liballeg.org/a5docs/trunk/video.html#al_start_video_with_voice
However, there doesn't seem to be a way to set the gain on the voice directly, only via a mixer. 
I would say that it is a missing feature of the video plugin that you cannot redirect the audio output to a mixer.

**Comment by chundermike** [comment]
Thanks,

Yep, that's what I thought.  Can we make this a feature request please? Ideally start_video_with_mixer() if that's not too difficult?
________________________________

**Comment by chundermike** [comment]
Ok, I will try and have a go at implementing it.
Thanks
________________________________

**Comment by chundermike** [comment]
..I just realised that al_start_video takes ALLEGRO_MIXER as it's second parameter, so I think the functionality is already there.

**Comment by beoran** [comment]
Indeed, how did I miss that! Just use al_set_mixer_gain on that mixer then .
