### ISSUE TITLE
default audio mixer settings

### ISSUE THREAD

**Issue by chundermike** [liballeg/allegro5#1249]
Hi,

Up to now, I've been using just one audio mixer, and been attaching sources to it using the al_get_default_mixer() function. Now I want two mixers, so have to explicitly create them using the al_create_mixer()  functions.  These, however require parameters for  freq, depth and chan_conf.  What if I don't know these at the point of creating the mixer? When using the default mixer you don't to need to configure it and your sources just play through it like magic...maybe if I knew the default freq, depth and chan_conf for the default mixer I could just mimic these when creating the non-default mixers?

**Comment by SiegeLord** [comment]
So you're thinking of some sort of `al_create_mixer_with_default_settings` or something? It could be done, personally I just looked into A5's source and copied the values used there, but I agree it's not ideal.

We could also document them in `al_create_mixer`.

**Comment by chundermike** [comment]
I've looked at a few examples now (sorry, should have done that before opening the issue), and it's a lot clearer... there's only three parameters and they are all simple so I'm happy with the way it works currently. Thanks.

**Comment by SiegeLord** [comment]
Ok; let's leave this open to at least beef up the documentation.
