### ISSUE TITLE
Allegro is Obsolete

### ISSUE THREAD

**Issue by troutsneeze** [liballeg/allegro5#1259]
Hello. I have found that Allegro is now obsolete. Could someone please fix this?

**Comment by SiegeLord** [comment]
Err... can you post your `allegro.log`?

**Comment by beoran** [comment]
This is an open source project. If you want Allegro to be brand new again, I encourage you to start working on version 6.

**Comment by EdgarReynaldo** [comment]
Why is this even open? Close and delete please. Don't waste the developer's time.

**Comment by beoran** [comment]
@EdgarReynaldo It is true though. If we had more developers we could make a version 6 with support for Wayland, Vulcan, newer DirectX, etc.
