### ISSUE TITLE
Video + PhysicsFS + Password

### ISSUE THREAD

**Issue by jarroddavis6889** [liballeg/allegro5#1262]
The problem with loading videos from an archive that was not at the root has been fixed and I have been using it with no issues. However, today I discovered something. I recently discovered that I can have password protected ZIP files and you just need to append the password to your filename like such "myfilename. ext$MYPASSWORD" and all the allegro routines that I used has worked, except video. Sigh.  Videos for whatever reason will not load if password is used.

**Comment by SiegeLord** [comment]
This should work now.
