### ISSUE TITLE
PhysicsFS + Password + al_load_audio_stream

### ISSUE THREAD

**Issue by jarroddavis6889** [liballeg/allegro5#1264]
Looks like al_load_audio_stream also does not support passed password to PhysicsFS. I've not gotten to al_load_sample yet, but can it also be checked also for password support as well.

**Comment by jarroddavis6889** [comment]
No, al_load_sample does not work when you pass a password either.

**Comment by SiegeLord** [comment]
This is the same issue as the video addon, with the same solution; it's more complicated for acodec though since we support so many more formats there.

**Comment by jarroddavis6889** [comment]
So, I ended up doing this:

```Pascal
function fi_fopen(const path: PUTF8Char; const mode: PUTF8Char): Pointer; cdecl;
var
  LMarshaller: TMarshaller;
  LPath: string;
begin
  if gGlobals.PhysfsPassword.IsEmpty then
    LPath := string(path)
  else
    LPath := string(path) + '$' + gGlobals.PhysfsPassword;

  Result := gGlobals.PhysfsFI[0].fi_fopen(LMarshaller.AsAnsi(LPath).ToPointer, mode);
end; 
```
After calling al_set_physfs_file_interface, I then hijack fl_fopen to call my custom fl_fopen, which will setup the password format expected by physfs and pass this to the original fi_fopen. Everything that I've tried seem to work. So far so good.

**Comment by SiegeLord** [comment]
This should be now fixed, now that we use magic number file format identification.
