### ISSUE TITLE
ALLEGRO_EVENT_MOUSE_ENTER/LEAVE_DISPLAY triggers incorrectly on MacOS after resize.

### ISSUE THREAD

**Issue by NewCreature** [liballeg/allegro5#1282]
After resizing a display by dragging the edge or corner, the events `ALLEGRO_EVENT_MOUSE_ENTER_DISPLAY` and `ALLEGRO_EVENT_MOUSE_LEAVE_DISPLAY` trigger incorrectly under MacOS.

The issue can be reproduced easily by running `ex_mouse_events`, making the window larger using the window edges to resize it, then moving the mouse within the window. The events are triggered when the mouse cursor reaches the area where the mouse would have entered or left the display before it was resized.

**Comment by SiegeLord** [comment]
I tried this and couldn't reproduce this on OSX 10.14 (I followed your proposed reproduction steps). What OSX version are you testing this on?

**Comment by NewCreature** [comment]
Hmm, I think it's actually triggered incorrectly toward the top and right of the window... yep. I am testing on 11.5.2. I'll see if I can get it to happen on my 10.13.6 machine.

**Comment by NewCreature** [comment]
I couldn't reproduce the issue on that machine.

**Comment by NewCreature** [comment]
Looking at the code [here](https://github.com/liballeg/allegro5/blob/acf307bcf75192da30ce769c8ca65f152667311c/src/macosx/osxgl.m#L323) I see that `reshape()` is supposed to be called when the display is resized. On my 11.5.2 machine I see that the function is called but the `if ([NSOpenGLContext currentContext] != nil)` condition fails and the tracking area is not updated.

**Comment by connorjclark** [comment]
@NewCreature I have a fix here, FYI: #1378
