### ISSUE TITLE
Can't build in MSVS 2022 when using NuGet packages and v143 toolset

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#1293]
MSVS 2022 just came out last week.  Using the Allegro NuGet packages, trying to build when targeting the 2022 toolset (v143) results in the linker being unable to find Allegro's `.lib` files.  `Platform Toolset` must currently be set to v142 (i.e. VS 2019) for this to work.

**Comment by SiegeLord** [comment]
https://www.nuget.org/packages/Allegro/5.2.7.1 has just been uploaded with v143 support. Thanks for reminding me to make it.

**Comment by fatcerberus** [comment]
That was quick, thanks!
