### ISSUE TITLE
Can't compile with FreeType support on Windows

### ISSUE THREAD

**Issue by HerrNamenlos123** [liballeg/allegro5#1306]
In the CMakeLists there is this run_c_compile_test function to check if freetype compiles, what is this exactly doing? 

I linked everything correctly for MSVC Visual Studio and without this call everything works fine. However, with the original CMakeLists it simply says `Freetype doesn't compile. disabling support`. I suspect this is because this run_c_compile_test function uses a different compiler under the hood and the static library is incompatible.

Is this compile test really necessary? Without it everything works and I can't find a way to compile without modifying anything.

**Comment by SiegeLord** [comment]
So, to be clear, you're using MSVC to compile Allegro source, you also have FreeType binaries somewhere and Allegro's not picking them up?

If so, you can check `CMakeFiles/CMakeError.log` inside the build directory and see what it says (you can search for freetype).

**Comment by HerrNamenlos123** [comment]
I'm specifically trying to build allegro5 completely automated from the command line, from a conan package. I'm working on a conan package, which can be easily published and updated in the future and provides binaries for all major OSes and compilers and can build it fully automated in any environment. Once it's published you can use conan to set up a project using allegro within minutes.

It seems the reason it's not compiling is that it actually is compiling now, however the linking fails. Apparently freetype has libpng and bzip as dependencies, but they are not linked in anywhere. Should they be linked or is this compile test only supposed to compile and not link it?

**Comment by HerrNamenlos123** [comment]
Found the issue, working on it

**Comment by HerrNamenlos123** [comment]
I applied a little patch which allows me to fix it.

https://github.com/liballeg/allegro5/pull/1307

Please take a look at it very soon

**Comment by SiegeLord** [comment]
I think you're specifying the wrong variable. It should be `-DZLIB_LIBRARY` not `-DZLIB_LIBRARIES`. See https://github.com/liballeg/allegro_winpkg/blob/master/universal/build_allegro_msys.sh#L18 for the example dependency overrides.

**Comment by HerrNamenlos123** [comment]
Wha-what!?

Okay cmake is straight-up weird. 
This variable was different for every library, i tried it, but apparently not all possibilities.
You are right, I had to specify `ZLIB_LIBRARY`, even though `ZLIB_FOUND` was also defined. The variable that is used in the CMakeLists, however, is called `ZLIB_LIBRARIES` and when it is not found cmake also complains that `ZLIB_LIBRARIES` is missing, but apparently it wants to have `ZLIB_LIBRARY` instead and then passes it on as `ZLIB_LIBRARIES`. What a mess.

Nevertheless I think it works now, if that's the case then this PR is not needed anymore.

**Comment by HerrNamenlos123** [comment]
Well it seems to work now, sorry for the inconvenience...
Thank you for your help!

**Comment by HerrNamenlos123** [comment]
Just another little question, too unimportant for its own issue:

I realised in the master branch there is the addon summary which prints the summary list and the end of configuration. It seems to be removed in all other branches except master (branch `5.2.7` for example). 

Was this done deliberately? If so, could you please explain me why? Just interested because I do think it's useful...

**Comment by SiegeLord** [comment]
It was added after 5.2.7 was released. It'll be included in the 5.2.8 release.

**Comment by HerrNamenlos123** [comment]
Alright, I see. Thank you for taking your time!
