### ISSUE TITLE
Build Allegro without cmake

### ISSUE THREAD

**Issue by j0ng4b** [liballeg/allegro5#1312]
Is there any way to build Allegro without cmake especially for Android project?

I'm trying to write a simple shell script or make file to build an Android project thats use Allegro, but I don't want to use the cmake, only shell script ou makefiles.

**Comment by beoran** [comment]
Cmake should also work for android. I  reccomend you try to use cmake. Allegro is complex to build, and without cmake it will be very hard to build it correctly.

**Comment by j0ng4b** [comment]
But hard even to get the source file list (all .c needed to build android shared library) and the compiler flags?

My goal is only to build a pre-built shared library version of Allegro targeting the android.

**Comment by beoran** [comment]
It is already possible to do this if you configure cmake correctly to use the android cross compiler. The files to compile as well as the flags for the compiler depend on the operating system, used libraries, etc. It would be really hard to do all that manually. I reccommend you use Cmake, it is a commonly used tool for building c programs.

**Comment by j0ng4b** [comment]
I see, that's right, I' going to use cmake then.

**Comment by SiegeLord** [comment]
The main difficulty is that we generate a [few files](https://github.com/liballeg/allegro5/search?q=configure_file) during the configuration phase, otherwise the sources are all in https://github.com/liballeg/allegro5/blob/master/cmake/FileList.cmake

**Comment by j0ng4b** [comment]
Oh okay, I understood, thanks for all answers.
