### ISSUE TITLE
How are examples built with emscripten such that sound works?

### ISSUE THREAD

**Issue by connorjclark** [liballeg/allegro5#1321]
Although there is a working example here: https://allegro5.org/examples/examples/ex_saw.html I am not able to get a local build to work.

Following the instructions at https://github.com/liballeg/allegro5/blob/master/README_sdl.txt , I made a few tweaks during my attempts:

1) `-D WANT_OPENAL=ON` (seemed odd this would be disabled, as emscripten has an openal port)
2) `-I "$EM_CACHE/sysroot/include/AL"` (probably a hack.  altho emscripten has openal headers in its provided sysroot, they are within a folder and the compiled code expects them to not be: `#include <al.h>` vs `#include <AL/al.h>`

I can successfully build and load the HTML in the browser, but I only get `Generating saw wave...` in the output and nothing else.

**Comment by SiegeLord** [comment]
@elias-pschernig do you recall?
