### ISSUE TITLE
#include <allegro5/allegro.h> doesn't work on M1 Pro Mac

### ISSUE THREAD

**Issue by StathisKap** [liballeg/allegro5#1342]
I'm trying to complie an allegro project of mine that I made in linux, but on a mac, and it just won't find the header file, and idk why.
Anyone know how I can fix this?

<img width="1624" alt="Screenshot 2022-06-09 at 20 20 29" src="https://user-images.githubusercontent.com/69547998/172927415-5571fa53-066b-4b41-abf9-957e4930a8b5.png">

**Comment by gusnan** [comment]
Looks like you are missing --cflags in your pkg-config-command.

**Comment by StathisKap** [comment]
I tried that and it wasn't working. I've now build from source and that seems to have done it
