### ISSUE TITLE
Pressing SHIFT when holding ALT on windows emits a nil key event

### ISSUE THREAD

**Issue by connorjclark** [liballeg/allegro5#1348]
I found this bug because there's a command in my application that does something when SHIFT and ALT are held down. It works when first pressing SHIFT then holding ALT too, but not the other way around.

From debugging, I found that the second key event received when doing ALT then SHIFT is zero'd out and only has the ALT bit enabled in `modifiers`:

```
{type=11 source=0x00007ffe3bcf6d40 {allegro-5.2.dll!ALLEGRO_KEYBOARD the_keyboard} {...} timestamp=341.56358236244910 ...}
    type: 11
    source: 0x00007ffe3bcf6d40 {allegro-5.2.dll!ALLEGRO_KEYBOARD the_keyboard} {...}
    timestamp: 341.56358236244910
    display: 0x000001eed147f840 {...}
    keycode: 0
    unichar: 0
    modifiers: 4
    repeat: false
```

My expectation is that either `modifiers` would have the SHIFT bit enabled, or that (also?) `keycode` is set to the value for the shift key.

Perhaps related: #713

**Comment by connorjclark** [comment]
Any pointers on where to start with this?

**Comment by SiegeLord** [comment]
#1404 should fix the weird key event, but the fixed key down events don't have modifiers. Ctrl/Shift/Alt are pretty wonky keys, I'm not sure I can get modifiers for them.
