### ISSUE TITLE
ALLEGRO_FULLSCREEN_WINDOW fails under X11 in Allegro 5.2.8

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#1349]
Since commit bd99c161720cce2cabaa5bb903eb977a4b61afee, creating a display with `ALLEGRO_FULLSCREEN_WINDOW` flag ends up with wrong behavior on X11. Tested with KWin, Mutter and i3.

Instead of making the window span the entire size of the screen, it keeps the size passed to `al_create_display` and puts it into bottom left corner of the window. `al_get_display_width/height` functions return the passed dimensions instead of the actual size of the window. This only happens on window creation - toggling fullscreen back and forth makes it work fine.

Here's an example of a FULLSCREEN_WINDOW window created with `al_create_display(1280, 720);` on a 4K screen.

Allegro 5.2.7:

![Screenshot_20220714_173033](https://user-images.githubusercontent.com/126204/179019997-8dc179b1-c3fe-4385-83a7-41f2799d7e1e.png)

Allegro 5.2.8:

![Screenshot_20220714_173011](https://user-images.githubusercontent.com/126204/179020008-e687f294-792f-4af6-a182-02b04755c32d.png)

**Comment by SiegeLord** [comment]
`ALLEGRO_FULLSCREEN_DESKTOP`? Do you mean `ALLEGRO_FULLSCREEN` or `ALLEGRO_FULLSCREEN_WINDOW`?

I wonder how a timer change could have caused this...

**Comment by dos1** [comment]
Argghhh, of course `ALLEGRO_FULLSCREEN_WINDOW`. Mixed it up with competition's `SDL_WINDOW_FULLSCREEN_DESKTOP` :)

Yep, imagine my surprise when this was the commit that git bisect came up with. I checked it multiple times and I can confirm that reverting this single commit makes it work fine again.

**Comment by pmprog** [comment]
Have you changed any desktop settings lately? Only I saw this one time when trying to develop on the PinePhone (I was using Raylib at the time, as I was struggling to get Allegro working), and it was due to the desktops DPI/Scaling factor IIRC.

**Comment by dos1** [comment]
The issue is in Allegro, it goes away and comes back together with the commit mentioned above. Versions earlier than 5.2.8 are not affected. Seems that changing how _al_unix_get_time works comes with some side effect. The only usage I've seen from a quick look appeared to be related to event timestamps, so maybe it influences event ordering?

Also, this issue is reproducible on various window managers, even under XWayland, so it's extremely unlikely it's related to my desktop.

BTW. Allegro should work fine on the PinePhone, although you'll likely want to compile it with GLES, and using SDL backend will give you Wayland support with hidpi that you won't get with Allegro's X11 backend.
