### ISSUE TITLE
Resizing windows on mac results in red blips as display is flipped

### ISSUE THREAD

**Issue by connorjclark** [liballeg/allegro5#1350]
`ex_draw2` exhibits this: https://youtu.be/6UJNHFO4myU

<img width="491" alt="image" src="https://user-images.githubusercontent.com/4071474/179342892-a2be36a1-b75a-452b-92bf-740445dfbd2a.png">

I forget now, but this may only be for Debug build (red suggests a common debugging memory value) and results may vary for Release.

**Comment by SiegeLord** [comment]
There is now a workaround for this implemented in #1442
