### ISSUE TITLE
Joystick docs missing, not being built with html

### ISSUE THREAD

**Issue by EdgarReynaldo** [liballeg/allegro5#1373]
joystick.txt is not getting converted to html in the build process. I assume it's a missing line in some index somewhere.

**Comment by SiegeLord** [comment]
Where do you see it missing? It's online https://liballeg.org/a5docs/trunk/joystick.html and I also just rebuilt the docs and it was there.

**Comment by EdgarReynaldo** [comment]
I built allegro 5.2.9 from GIT. It's not being built corrrectly and is 
empty.

**Comment by EdgarReynaldo** [comment]
I rebuilt and it worked this time. Must have been a quirk of make -j .

**Comment by EdgarReynaldo** [comment]
Must have been a quirk of the build process. It works.
