### ISSUE TITLE
CMake policy CMP0075 is not set

### ISSUE THREAD

**Issue by katastic** [liballeg/allegro5#1376]
Minor issue. CMake files do not conform to modern CMake requirements.

https://cmake.org/cmake/help/latest/policy/CMP0075.html

> git clone allegro
> cd build
> cmake ..

![image](https://user-images.githubusercontent.com/11449593/194950414-df113c1d-15b8-42cd-8ec8-7146c13eb243.png)

**Comment by pedro-w** [comment]
There's another issue flagged when trying to generate Xcode projects - they don't conform to the "new build system". Not at my Mac now but I'll post the exact message when I am.
If someone who knows how CMake works is looking at the files it would be good to get this resolved also.
