### ISSUE TITLE
Child window with ALLEGRO_MENU causes crash upon open/close display.

### ISSUE THREAD

**Issue by MatiasMunk** [liballeg/allegro5#1381]
Using the ex_menu.c example in a program.
The program will crash, if you open/close the child window multiple times.

This is a problem, since I'm developing a game where you can open editor windows for e.g. maps, items, etc.

Crash upon close is in 'allegro5/platform/aintwthr.h' line 59
```
AL_INLINE(void, _al_mutex_lock, (struct _AL_MUTEX *m),
{
   if (m->cs)
      EnterCriticalSection(m->cs);
})
```

Crash upon open is in 'allegro/src/win/wwindow.c' line 196
`GetWindowInfo(my_window, &wi);`
and sometimes other places, like allegro/src/memory.c line 44
```
/* Function: al_malloc_with_context
 */
void *al_malloc_with_context(size_t n,
   int line, const char *file, const char *func)
{
   if (mem)
      return mem->mi_malloc(n, line, file, func);
   else
      return malloc(n); //This right here line 44
}
```

**Comment by rmbeer** [comment]
I hope I'm not wrong.

For work with the menu in the Windows system, a **./addons/native_dialog/win_menu.c** is needed.

I can't work with Windows so I can't check either.

**Comment by MatiasMunk** [comment]
win_menu.c is non-existant in the source.
