### ISSUE TITLE
Drawing functions questions

### ISSUE THREAD

**Issue by TRDario** [liballeg/allegro5#1389]
I've got a few general questions regarding the drawing functions.

Is there a reason some of the bitmap region drawing functions are omitted? All of them are implemented in terms of the same function anyway so the only reason I can think of to omit them would be percieved bloat, but its not really that many extra functions and helps makes things more clear in my opinion.

The only exception I can see is the scaled bitmap drawing, where for some reason the base function has the behavior matching the other region drawing functions. Why's that like that anyway? It makes for a weird inconsistency.

Lastly, what would the attitude here be towards implementing elliptical pieslice drawing functions? All of the other circular functions have elliptical variants so it'd also be more consistent.

I'm partly asking this because I maintain these changes in a personal patch, so I could push them back to here if people think it's a good idea (besides changing scaled bitmap drawing because it'd break API). I'd love to hear your thoughts before i make a PR for anything.

**Comment by SiegeLord** [comment]
> Is there a reason some of the bitmap region drawing functions are omitted? All of them are implemented in terms of the same function anyway so the only reason I can think of to omit them would be percieved bloat, but its not really that many extra functions and helps makes things more clear in my opinion.

Bloat is the reason, but if there's one or two some particular highly used versions we could add them.

> Lastly, what would the attitude here be towards implementing elliptical pieslice drawing functions? All of the other circular functions have elliptical variants so it'd also be more consistent.

I think it's a great idea.

**Comment by TRDario** [comment]
> Bloat is the reason, but if there's one or two some particular highly used versions we could add them.

That's fair enough I suppose. The full list of missing functions is:
`al_draw_scaled_bitmap_region
al_draw_tinted_scaled_bitmap_region
al_draw_rotated_bitmap_region
al_draw_scaled_rotated_bitmap_region
al_draw_tinted_rotated_bitmap_region`

I'm fine with leaving out `al_draw_scaled_bitmap_region` and `al_draw_tinted_scaled_bitmap_region` because the non-bitmap versions already implement their functionality. This leaves us with 3 actual functions, which I don't think is that much extra bloat.
