### ISSUE TITLE
ALLEGRO_EVENT_DISPLAY_SWITCH_IN/OUT Incorrectly Triggered on Ubuntu 22 and Manjaro GNOME

### ISSUE THREAD

**Issue by NewCreature** [liballeg/allegro5#1390]
When clicking anywhere in my ALLEGRO_DISPLAY, I'm getting an ALLEGRO_EVENT_DISPLAY_SWITCH_IN followed immediately by an ALLEGRO_EVENT_DISPLAY_SWITCH_OUT. This behavior started happening after moving from Ubuntu 20 to Ubuntu 22.

**Comment by SiegeLord** [comment]
Is this the same as #1367?

**Comment by NewCreature** [comment]
It could be related.

I did some more testing and found when I switched from Wayland to X11, the issue went away. Also, this issue only occurs when enabling the `ALLEGRO_GTK_TOPLEVEL` flag on the display.

While I was on X11 I noticed I get similar switch in/out events when clicking the title bar. I did not get these events from clicking the title bar under Wayland.

**Comment by SiegeLord** [comment]
I looked into this and have some potential solutions for the initial problem. As for this:

> While I was on X11 I noticed I get similar switch in/out events when clicking the title bar. I did not get these events from clicking the title bar under Wayland.

I think that might be... just WM specific. It seems harmless.
