### ISSUE TITLE
Allegro 6 C++

### ISSUE THREAD

**Issue by troutsneeze** [liballeg/allegro5#1393]
What do you think about shim4 in particular in my repos? I need help. I have a generic game engine functions in wedge3 and gui in tgui6.

**Comment by SiegeLord** [comment]
It doesn't seem like the time to make Allegro 6 yet. All(most?) the API seems to be in a good shape so there doesn't seem a need to break compatibility.

**Comment by goob256** [comment]
Well, it's available now for anyone else who wants to upgrade now.
