### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by francescovezzi** [liballeg/allegro5#1409]
Hi,

I am trying to run an application based on allegro4.2 inside a docker container but I am experiencing some trouble with `install_keyboard()` and `install_mouse()`. Indeed they produce the annoying error "Segmentation fault (core dumped)".

Here you are a minimalistic example to reproduce the result:

example.c:
```
#include <allegro.h>
#include <stdio.h>
#define XMAX 800
#define YMAX 600

int main()
{
int x, y, col;

	allegro_init();
	install_keyboard();
	
	set_color_depth(8);
	set_gfx_mode(GFX_AUTODETECT_WINDOWED, 800, 600, 0, 0);
	clear_to_color(screen, 0);

	do	{
		x = rand()%XMAX;
		y = rand()%YMAX;
		col = rand()%16;
		readkey();
		putpixel(screen, x, y, col);
	} while (!key[KEY_ESC]);
	
	return 0;
}
```

Dockerfile:
```
FROM ubuntu:18.04

WORKDIR /usr/src/example

COPY . .

RUN apt-get update && \
    apt-get -y install build-essential && \
    apt-get -y install liballegro4.2 liballegro4.2-dev && \
    rm -rf /var/lib/apt/lists/*

RUN g++ example.c -o executable `allegro-config --libs`
```

If I run:
`docker build -t example .`
`docker run -it example /bin/bash`
Then we are inside the container bash, if I try:
`./executable`
is not working and producing the error.

Is there a way to use an Allegro application from a docker container?

Thank you in advance.

**Comment by beoran** [comment]
Allegro needs access to the operating system's graphical resources and so it is unlikely to run in Docker. Furthermore allegro 4 is obsolete. Please upgrade to allegro 5. 

What are you trying to accomplish with this?

**Comment by francescovezzi** [comment]
Nothing special, just personal satisfaction and an increase in machine compatibility of my code.
Thank you for your help!

**Comment by beoran** [comment]
I see. I will close this issue since this is not something we will be able to do.
