### ISSUE TITLE
Build fails on MacOS

### ISSUE THREAD

**Issue by pedro-w** [liballeg/allegro5#1411]
If I try and build using the Xcode generator (i.e. `cmake -G Xcode ..`) it configures OK, but when invoking `xcodebuild` I get

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Multiple commands produce '<PbxCp /tmp/x/demos/shooter/RelWithDebInfo/shooter.app/Contents/Resources/data/TITLE_MUSIC.ogg>':
1) Target 'shooter' (project 'ALLEGRO') has copy command from '/Users/peterhull/Projects/allegro5/demos/shooter/data/TITLE_MUSIC.ogg' to '/tmp/x/demos/shooter/RelWithDebInfo/shooter.app/Contents/Resources/data/TITLE_MUSIC.ogg'
2) Target 'shooter' (project 'ALLEGRO') has copy command from '/tmp/x/demos/shooter/data/TITLE_MUSIC.ogg' to '/tmp/x/demos/shooter/RelWithDebInfo/shooter.app/Contents/Resources/data/TITLE_MUSIC.ogg'
```
(and similar errors for other resource files in shooter)

With Ninja it won't even configure
```
CMake Error:
  Running

   '/usr/local/bin/ninja' '-C' '/tmp/n' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:5598: multiple rules generate demos/shooter/shooter.app/Contents/Resources/data/DejaVuSans.ttf
```
Using allegro current master (0aeca8c6a72205dd4893799face0502720d1b341), cmake version 3.25.1, Xcode 12.4, MacOS 10.15.7

**Comment by allefant** [comment]
unix makefiles works

**Comment by pedro-w** [comment]
It looks to me like the problem comes from having a duplicate rule to copy the resources, and I guess that `make` doesn't have anything to check for that situation.

**Comment by pedro-w** [comment]
I think it gets messed up if you do an in-source build (or, if you ever have done an in-source build) Here's some stuff from `demos/shooter/CMakeLists.txt`

Copy some files to the binary dir:
https://github.com/liballeg/allegro5/blob/0aeca8c6a72205dd4893799face0502720d1b341/demos/shooter/CMakeLists.txt#L29-L34

(later in the same file) get all the data files
https://github.com/liballeg/allegro5/blob/0aeca8c6a72205dd4893799face0502720d1b341/demos/shooter/CMakeLists.txt#L41-L45

(later in the same file) add another copy of some files for good measure
https://github.com/liballeg/allegro5/blob/0aeca8c6a72205dd4893799face0502720d1b341/demos/shooter/CMakeLists.txt#L46-L48

(later in the same file) tell CMake we want to put those files in the MacOS bundle
https://github.com/liballeg/allegro5/blob/0aeca8c6a72205dd4893799face0502720d1b341/demos/shooter/CMakeLists.txt#L114-L116

(later in the same file) let's tell CMake to copy them again
https://github.com/liballeg/allegro5/blob/0aeca8c6a72205dd4893799face0502720d1b341/demos/shooter/CMakeLists.txt#L118-L121

Once again CMake has wrestled me to the mat! I think maybe the answer is not to copy those files to the binary dir in the first quoted section but just to refer to them in their 'home' locations, but I'm not confident of that for all platforms and all combinations of in-source and out-of-source builds. It may be I just broke it by running CMake all wrong at some point in the past. 
Can anyone reproduce this problem on macos with ninja or xcode generators?

**Comment by pedro-w** [comment]
A clean check-out worked but attempting an in-source build (1) didn't work and (2) messed up the repo by copying those files as described above (i.e. DejaVuSans.ttf et al get copied to the source `demo/shooter/data` dir and cause duplicate file errors.)
Is there a way to prevent CMake from even attempting an in-source build? (not good practice in any case)

**Comment by allefant** [comment]
I don't think we ever supported in-source builds - the readme tells you to create a "build" folder as first step. It would be nice if cmake could either do that automatically (or just exit with an error if it is in the source folder).

**Comment by pedro-w** [comment]
>  It would be nice if cmake could either do that automatically (or just exit with an error if it is in the source folder).

Agreed!

>  the readme tells you to 

la la stopped reading at that point :wink:

**Comment by pedro-w** [comment]
CMake is so annoying - they nearly implemented it but made it useless. Typical.
https://gitlab.kitware.com/cmake/cmake/-/issues/18403

**Comment by allefant** [comment]
We could still do an explicit check like here: https://stackoverflow.com/questions/1208681/with-cmake-how-would-you-disable-in-source-builds
It's not a big problem that it creates some build files I guess, and at least we can display a message and prevent the eventual build failure. Or maybe we should fix that failure and allow in-source builds, but probably more work and more cmake oddities to fight...

**Comment by pedro-w** [comment]
> the readme tells you to create a "build" folder as first step.

Actually it doesn't, but I have put in a PR to add that advice.
