### ISSUE TITLE
Fullscreen not scaling correctly after #1412 [MacOS]

### ISSUE THREAD

**Issue by MarkOates** [liballeg/allegro5#1415]
After pulling and building `mater`, `ALLEGRO_FULLSCREEN` is not scaling correctly since https://github.com/liballeg/allegro5/pull/1412.  Probably related to a retina display?

Expected:

![expected](https://user-images.githubusercontent.com/772949/222493793-3e5dcd30-6c30-4ff6-90d2-3c8367bd4206.jpg)

Actual:

![actual](https://user-images.githubusercontent.com/772949/222493816-15b72dd2-1e5b-421b-8a99-605f0e7e3081.jpg)

Windowed mode appears to work fine:

![windowed](https://user-images.githubusercontent.com/772949/222493841-d6dcfdb7-5dac-48fa-9fa3-f912eafd3675.jpg)

[edit: replaced large filesize images]

**Comment by allefant** [comment]
Oh weird. That's kinda how it was broken before (when not drawing bitmaps/fonts at least). I thought my change only affected window resizing and left fullscreen untouched, I'll see if I can reproduce somehow.

**Comment by allefant** [comment]
Yeah, after I realized you meant ALLEGRO_FULLSCREEN_WINDOW and not ALLEGRO_FULLSCREEN I was able to reproduce!

**Comment by MarkOates** [comment]
> Yeah, after I realized you meant ALLEGRO_FULLSCREEN_WINDOW and not ALLEGRO_FULLSCREEN I was able to reproduce!

Yes! Sorry for that oversight. I don't think I use `ALLEGRO_FULLSCREEN` anywhere anymore just because it could be destructive to the user's display/settings.

Thank you for that *very fast* fix. 😳
