### ISSUE TITLE
`al_install_joystick` can sometimes freeze [MacOS]

### ISSUE THREAD

**Issue by MarkOates** [liballeg/allegro5#1420]
## Problem

If one or multiple joysticks are already connected when `al_install_joystick()` is called, Allegro will _sometimes_ get stuck in an infinite loop.

## Location

I haven't been able to do much research other than [localize the problem to this loop in `al_install_joystick()`](https://github.com/liballeg/allegro5/blob/master/src/macosx/hidjoy.m#L588-L599), and try it with one and two joysticks.  I also haven't been able to isolate the conditions to reproduce the problem reliably, but I'd say it happens 1 in 4 times or so.

It seems like the loop is doing polling, waiting/expecting for callbacks to finish and the number of `joysticks` (allegro local variable) to match the number of `devices` (os-local count of devices matching the "joystick" criteria).

**Comment by pedro-w** [comment]
What are the values of `count` and `size` when it gets stuck (are either of them 'correct'?)
Also I wonder what the purpose of that loop is - the joysticks will be added eventually (and only a little while later, surely) and that's only the same as if you'd plugged one in after the start of the game.

**Comment by MarkOates** [comment]
When infinite looping, `size` (the number of allegro-known devices) is one less than `count` (number of os-connected devices).  The number of os-connected devices seems to be correct.

> Also I wonder what the purpose of that loop is - the joysticks will be added eventually (and only a little while later, surely) and that's only the same as if you'd plugged one in after the start of the game.

They could also be removed, too!

I'm not sure the design is correct.  My expectation would be to:
1) Enumerate and create the number of connected devices
2) Register callbacks to the OS for newly connected/disconnected devices

The current design seems to mix the two, leaving step 1 after step 2, and then polling for connection events to catch any that were missed.  Thoughts are welcome... I'm still poking around on it.

**Comment by MarkOates** [comment]
Some progress has been made. I'll share a [WIP branch here](https://github.com/liballeg/allegro5/compare/master...MarkOates:allegro5:fix-joystick-infinite-loop?diff=unified) that manually enumerates connected joysticks on initialization (rather than waiting for callbacks), but it is still incomplete. I believe the manual enumeration needs to not compete with the existing callbacks that can also occur.

**Comment by MarkOates** [comment]
Ok, I've got a PR up that seems to fix the issue [here](https://github.com/liballeg/allegro5/pull/1423).

**Comment by MarkOates** [comment]
Issue appears to be be fixed with https://github.com/liballeg/allegro5/pull/1423 🎉
