### ISSUE TITLE
Alt-Graph Keys not recognized on Windows

### ISSUE THREAD

**Issue by egrath** [liballeg/allegro5#1430]
**Issue**
On Windows, characters which are entered using Alt-Graph+Key combinations are not recognized, but instead only the regular Key.

To demonstrate the issue, i've adopted one of the official examples (attached). On both runs, Alt-Graph+Q was pressed to produce the at-Symbol (@):

Windows 11 (English) with german keyboard layout:
```
[KEY_DOWN]: keycode=[217], char=[], modifiers=[00000000](LCTRL)
[KEY_DOWN]: keycode=[220], char=[], modifiers=[00000000](ALTGR)
[KEY_DOWN]: keycode=[017], char=[], modifiers=[00000000](Q)
[KEY_CHAR]: keycode=[017], char=[q], modifiers=[00000242](Q)
[KEY_UP]: keycode=[017], char=[], modifiers=[00000000](Q)
[KEY_UP]: keycode=[217], char=[], modifiers=[00000000](LCTRL)
[KEY_UP]: keycode=[220], char=[], modifiers=[00000000](ALTGR)
```

Ubuntu 20.04 with german keyboard layout:
```
[KEY_DOWN]: keycode=[220], char=[], modifiers=[00000000](ISO_Level3_Shift)
[KEY_DOWN]: keycode=[017], char=[], modifiers=[00000000](q)
[KEY_CHAR]: keycode=[017], char=[@], modifiers=[00000220](q)
[KEY_UP]: keycode=[017], char=[], modifiers=[00000000](q)
[KEY_UP]: keycode=[220], char=[], modifiers=[00000000](ISO_Level3_Shift)
```

Only the later one correctly produces the @-symbol.

**How to reproduce:**
Build the attached application on Windows (MinGW, Allegro 5.2.8) and enter a Alt-Graph generated symbol like @ (Alt-Graph+Q).

**Expected behavior:**
Windows should recognized the keypress in the same way as Linux does.

If you need any further information which can help to get this bug fixed, please let me know.
[keytest.zip](https://github.com/liballeg/allegro5/files/11186126/keytest.zip)

**Comment by torhus** [comment]
I tried this in an Allegro 5.0.5 build of ex_keyboard_events I had laying around, AltGr it works fine there with my Norwegian keyboard layout.

I don't have newer builds to test on, but this commit looks suspicious: https://github.com/liballeg/allegro5/commit/4ff20880c0b146139e461b9ec24170b71acd1a33

**Comment by vortigano** [comment]
Here I have tested MinGW, Allegro 5.2.6.0 and I have the same problem.
Alt-Graph + 2 was pressed to produce the at-Symbol (@)
Windows 8.1 (Spanish) with Spanish keyboard layout:
```
[KEY_DOWN]: keycode=[217], char=[], modifiers=[00000000](LCTRL)
[KEY_DOWN]: keycode=[220], char=[], modifiers=[00000000](ALTGR)
[KEY_DOWN]: keycode=[029], char=[], modifiers=[00000000](2)
[KEY_CHAR]: keycode=[029], char=[2], modifiers=[00000042](2)
[KEY_UP]: keycode=[029], char=[], modifiers=[00000000](2)
[KEY_UP]: keycode=[217], char=[], modifiers=[00000000](LCTRL)
[KEY_UP]: keycode=[220], char=[], modifiers=[00000000](ALTGR)
```
I had reported this on discord too.

**Comment by SiegeLord** [comment]
So... reverting https://github.com/liballeg/allegro5/commit/4ff20880c0b146139e461b9ec24170b71acd1a33 does make this work, as far as I can tell. I sort of can imagine what that change was meant to do, but I think it is wrong. I need to cross-check what happens on Linux with this, but we'll probably just revert it.

**Comment by torhus** [comment]
> So... reverting [4ff2088](https://github.com/liballeg/allegro5/commit/4ff20880c0b146139e461b9ec24170b71acd1a33) does make this work, as far as I can tell. I sort of can imagine what that change was meant to do, but I think it is wrong. I need to cross-check what happens on Linux with this, but we'll probably just revert it.

I'm not completely sure what that commit is supposed to fix, but in my testing key combinations involving AltGr work fine even if I hold Left Control down. I tried on Allegro 5.0.8. If the idea is to suppress the extra key down and key up events that are generated for Left Control when pressing and releasing AltGr, I think that would be more involved.
