### ISSUE TITLE
Native file selector soft locks on MacOSX 10.6.

### ISSUE THREAD

**Issue by NewCreature** [liballeg/allegro5#1435]
When opening a native file selector dialog on MacOSX 10.6, the program soft locks. The output on the terminal is:
```
... -[NSCFArray objectAtIndexedSubscript:]: unrecognized selector set to instance at 0x...
... -[NSCFArray objectAtIndexedSubscript:]: unrecognized selector set to instance at 0x...
```

**Comment by pedro-w** [comment]
We don't use that function `objectAtIndexedSubscript:` directly but as I understand it, it's used to implement the direct indexing of `NSArray`, e.g. `an_array[index]` becomes a call to this. See for example
https://github.com/liballeg/allegro5/blob/23ad1bf8a700255aa0ed174c4f356e1946b473af/addons/native_dialog/osx_dialog.m#L22-L28
If you replace `work_array[i]` with `[work_array objectAtIndex: i]` does it fix it? (there may be other instances of direct indexing, too)

**Comment by NewCreature** [comment]
Yes, that did the trick.

**Comment by NewCreature** [comment]
Yeah, I had a feeling when I encountered the soft lock it had something to do with my file type filter patch.
