### ISSUE TITLE
modaudio acodec handler no longer honors in-built loops.

### ISSUE THREAD

**Issue by NewCreature** [liballeg/allegro5#1439]
While testing one of my current projects I noticed the music wasn't looping properly. I'm using the "Position Jump" effect to make the music loop the way I want. Unfortunately, with commit ef33940, this way of handling looping no longer works.

The problem stems from the way `duh_render()` handles writing samples. Particularly, it will not write the requested number of samples if it reaches a loop point in the song. In the current implementation, this triggers the audio add-on to rewind the stream to the start loop point, which is 0 by default, bypassing DUMB's own handling of the song's in-built looping.

Unfortunately, that's only part of the problem. The current implementation also sets the loop start to 0 and the loop end to the song length reported by `duh_get_length()`. This also bypasses in-built looping by triggering a rewind when playback reaches the end loop point.

These two things together make it impossible to utilize in-built looping that is common to modular music.

**Comment by SiegeLord** [comment]
Do you happen to have an example module I can test this with? Are you setting the playmode to loop or play once?

**Comment by SiegeLord** [comment]
Okay, I managed to make one with the Milktracker, indeed it used to work in 5.2.7 and no longer does in 5.2.8. Let me try fixing this.

**Comment by NewCreature** [comment]
Thank you :) It's working now.
