### ISSUE TITLE
X11 al_set_window_position unexpected behavior

### ISSUE THREAD

**Issue by elias-pschernig** [liballeg/allegro5#1496]
In X11 al_get_window_position returns the client area position (where the 0/0 the Allegro window is on the screen, not where the outer window border is), but in al_set_window_position we set a different position, so al_get_window_position(&x, &y) followed by al_set_window_position(x, y) will move the window around. I tried several window managers from non-compositing X11 to compositing to Wayland and the behavior at least seems consistently wrong.

I assume the expected behavior would be that passing al_get_window_position coordinates to al_set_window_position would not move the window?

**Comment by SiegeLord** [comment]
Yeah, I believe that's expected. There was a similar issue on Windows that was fixed (had to do with initial positions: https://github.com/liballeg/allegro5/commit/fead757535d9d416cd956880c5574ad215582d0a). In addition to that lack of movement, ideally (0, 0) (or whatever al_get_monitor_info returns for the top-left corner) should correspond to that top left corner. This isn't the case on Windows, for example, and its hard to fix: https://github.com/liballeg/allegro5/issues/1459
