### ISSUE TITLE
Android: app freezes while waiting for `al_acknowledge_drawing_halt()`

### ISSUE THREAD

**Issue by alemart** [liballeg/allegro5#1517]
**Summary**

An Android app may freeze while `AllegroSurface.nativeOnDestroy()` waits for a call to `al_acknowledge_drawing_halt()`.

**How to reproduce the issue**

Open ex_android and keep switching the app in and out of context very quickly. Eventually the app will freeze. The issue is reproducible with other examples too.

**Details**

As can be seen below, method `AllegroSurface.nativeOnDestroy()` in android_display.c emits an `ALLEGRO_EVENT_DISPLAY_HALT_DRAWING` just before waiting for a condition variable that is signaled in `android_acknowledge_drawing_halt()`. The drawing halt event is handled in a different thread. If the order of operations is such that the event is handled (and the condition variable is signaled) before the other thread is waiting, the app will freeze. The signal is lost and does nothing. The freeze can be reproduced easily by adding an `al_rest()` call before `al_wait_cond()`.

https://github.com/liballeg/allegro5/blob/9ced31b85310c307c19b0edab6b151e05aea4d3e/src/android/android_display.c#L88-L101

**Comment by dos1** [comment]
Sounds like a duplicate of #959
