### ISSUE TITLE
Memory leak in MacOS joystick code

### ISSUE THREAD

**Issue by pedro-w** [liballeg/allegro5#1534]
The static analyzer tells me there's a leak here:
https://github.com/liballeg/allegro5/blob/edcc50e85036e95474a31a7c75089b6b7653a4e5/src/macosx/hidjoy.m#L363-L375
`device_arr` is calloc'd and never freed.
Probably not a big deal as it's called only once by `init_joystick`

**Comment by pedro-w** [comment]
The one in Xcode but I believe it's based on the same technology as the [clang static analyzer](https://clang-analyzer.llvm.org/) (`scan-build` or whatever)

**Comment by pedro-w** [comment]
@ReiquelApplegate do you think it's wrong?

**Comment by ReiquelApplegate** [comment]
No, I agree `free(device_arr)` should be called.

**Comment by pedro-w** [comment]
Trivial really but I'll do a PR for this.
@SiegeLord should we be using `al_calloc` for internal memory allocation?

**Comment by SiegeLord** [comment]
Vs a plain `calloc`, yes, most of the time.
