### ISSUE TITLE
Undesirable deadzone when using analog Joysticks on Windows

### ISSUE THREAD

**Issue by geecab** [liballeg/allegro5#1538]
Hi there!

This has been discussed here:
[https://www.allegro.cc/forums/thread/618893/1054088](https://www.allegro.cc/forums/thread/618893/1054088)

This can be recreated on Allegro v5.2.9 running the ex_joystick_events example.

When I run ex_joystick_events on Linux, I can see from the graphical output, my analog joystick experiences no deadzone.

When I run ex_joystick_events on Windows, I can see from the graphical output, my analog joystick experiences a large deadzone.

A large deadzone is undesirable when you need high precision controls (flight yokes or steering wheels).

If I edit allegro5\src\win\wjoydxnu.cpp, changing property_deadzone's data value from 2000 to a 0, that gets rid of the deadzone....
``
DIPROPDWORD property_deadzone =
   {
      /* the header */
      {
   sizeof(DIPROPDWORD),   // diph.dwSize
   sizeof(DIPROPHEADER),  // diph.dwHeaderSize
   0,                     // diph.dwObj
   DIPH_DEVICE,           // diph.dwHow
      },
      /* the data */
      2000,                     // dwData
   };
``

It would be good to have control over the amount of deadzone Allegro sets for Windows. It would also be good if the default deadzone was consistent for Linux & Windows. 

Many thanks,

Ben

**Comment by SiegeLord** [comment]
Yeah, that seems not ideal. Wonder what it was that way. Probably harmless to set to 0.

**Comment by geecab** [comment]
>>Wonder what it was that way
I know what you mean. Perhaps when it was originally added, it was tested using a thumb stick / joystick that didn't centre too well, so a big deadzone might have seemed right at the time.

>>Probably harmless to set to 0.
I'd be really happy with a default of 0. I guess the only downside it that it might bother those who have come to expect a big deadzone. Still, a deadzone can always be achieved at a higher level in the game code (Ignoring joystick events when the axis position is below a certain value. That's how I've made it configurable in my game).

Thanks for taking a look at this :)

**Comment by pedro-w** [comment]
The dead zone, or something like it, has been in Allegro for ever (it's certainly in Allegro 3.12, from 1999).
My _speculation_ is that in the old days, the axis value came straight out of the ADC attached to the stick's potentiometer and was subject to a bit of noise which could cause your player to jitter around a bit. Nowadays there will be drivers in between and I bet there's some filtering going on. But nobody checked if the deadzone was still needed (in fairness this is impossible given the range of hardware out there)

**Comment by geecab** [comment]
So shall we just set it to zero then, I can do a pull request if you'd like?

**Comment by SiegeLord** [comment]
Yeah, I think that's fine. The main concern is a backwards compatibility hazard, but I don't there's one here.
