### ISSUE TITLE
Search for link in description of offers

### ISSUE THREAD

**Issue by Marek-ShopStore** [liballeg/allegro5#1552]
We have 90000+ products listed on our seller account. Most of product is created using API by providing GTIN, Name, Price and publication detail.

We now got second penalization for description that includes link to website.

The description is taken from already existing Products in Allegro database so it's link that someone had in they're offer.

Is there a way to scan product descriptions of our offers for links using API? We are unable to control all 90k products by hand...

**Comment by SiegeLord** [comment]
Wrong Allegro. You probably want https://github.com/allegro/allegro-api
