### ISSUE TITLE
ex_prim_wrap.c compile errors on MSVC

### ISSUE THREAD

**Issue by ReiquelApplegate** [liballeg/allegro5#1553]
MSVC Version 17.9.5

```
52>E:\allegro5\examples\ex_prim_wrap.c(50,32): error C2057: expected constant expression
52>E:\allegro5\examples\ex_prim_wrap.c(50,35): error C2466: cannot allocate an array of constant size 0
52>E:\allegro5\examples\ex_prim_wrap.c(50,25): error C2133: 'vtxs': unknown size
52>E:\allegro5\examples\ex_prim_wrap.c(70,36): error C2057: expected constant expression
52>E:\allegro5\examples\ex_prim_wrap.c(70,39): error C2466: cannot allocate an array of constant size 0
52>E:\allegro5\examples\ex_prim_wrap.c(70,25): error C2133: 'vtxs': unknown size
```

constants or #defines seem like a better choice than creating a variable that is never going to change after it's initialized.

**Comment by pedro-w** [comment]
Does this mean no one has ever compiled ex_prim_wrap with MSVC? AFAICS GCC and clang are ok with this code, but MSVC won't work even when replacing `int` with `const int`.
I guess it would have to be a `#define` - no constexpr for C, is there?

**Comment by ReiquelApplegate** [comment]
Who knows 🤷   MSVC doesn't support VLAs yet according to

https://zakuarbor.github.io/blog/variable-len-arr

So yeah I agree #defines will avoid relying on constant size VLAs which does sound like a very silly idea ;)  And yes constexpr is a C++ thing

**Comment by pedro-w** [comment]
From godbolt I can see that `const int` compiles in MSVC in C++ mode, though that's irrelevant here. 
I'm surprised that no Windows users have come across this before now. Also I thought we had GitHub actions set up to test the build.

**Comment by pedro-w** [comment]
Found another couple of issue-ettes here:
https://github.com/liballeg/allegro5/blob/85aa2f9a6274f645e4bfd7e78f70d3a4d20fc20f/examples/ex_prim_wrap.c#L172-L182
First, `pixel_file` may not be initialised (compiler complained about this)
Second, the files `ex_bitmap_wrap_pixel.*` don't exist, I guess should be `ex_prim_wrap_pixel.*`. This gives me an error if I run ex_prim_wrap with the --shader command line option.

**Comment by SiegeLord** [comment]
The CI uses MSYS2. And for the pre-built binaries don't build examples (and Edgar's binaries are MinGW only), so that's how this happened.

**Comment by SiegeLord** [comment]
This got fixed in https://github.com/liballeg/allegro5/commit/9ed326a43ea07b9ac7e44a4fc488e651e59af4b1
