### ISSUE TITLE
Possible typo in docs with al_draw_indexed_buffer

### ISSUE THREAD

**Issue by MarkOates** [liballeg/allegro5#1555]
For the documentation of [al_draw_indexed_buffer](https://liballeg.org/a5docs/trunk/primitives.html#al_draw_indexed_prim), the `start` and `end` params represent positions of the `index_buffer` (not the `vertex_buffer` as stated in the docs).

Currently:

> start - Start index of the subset of the ~~vertex buffer~~ (should be "index buffer") to draw
> end - One past the last index of the subset of the ~~vertex buffer~~ (should be "index buffer") to draw

The other listing https://liballeg.org/a5docs/trunk/primitives.html#al_draw_indexed_prim, appears to have it correct.

**Comment by ReiquelApplegate** [comment]
One piece of evidence that that the buffer `start` is indexing into is an index buffer and not vertex buffer:

_al_draw_buffer_common_soft (which is called from al_draw_indexed_buffer) contains this call:

`      idx = al_lock_index_buffer(index_buffer, start, num_vtx, ALLEGRO_LOCK_READONLY);`
