### ISSUE TITLE
Add ALLEGRO_TRACE_LEVEL environment variable.

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#1556]
This way you can output logs to stdout in two environment variables:

`ALLEGRO_TRACE_LEVEL=debug ALLEGRO_TRACE=- ./your_program`

**Comment by ReiquelApplegate** [comment]
So with `getenv("ALLEGRO_TRACE_LEVEL")`?  What function would need to be modified?

**Comment by SiegeLord** [comment]
Somewhere in `src/debug.c`

**Comment by ReiquelApplegate** [comment]
open_trace_file compares the ALLEGRO_TRACE env var to "-" and sets trace_info.trace_file to stdout if they match
