### ISSUE TITLE
segfault when loading mp3

### ISSUE THREAD

**Issue by connorjclark** [liballeg/allegro5#1569]
When loading a specific mp3 file, this error state is hit:

https://github.com/liballeg/allegro5/blob/7648fdf6824f67aa72c3c82f3accde94434ecede/addons/acodec/mp3.c#L294-L297

On clean up, this results in a segfault:

https://github.com/liballeg/allegro5/blob/7648fdf6824f67aa72c3c82f3accde94434ecede/addons/acodec/mp3.c#L343

I suppose the `mp3file` hasn't been initialized to the expected state, so freeing here is corrupting memory.

As for the error ... idk what that's about, the file loads fine in Windows media players.

mp3: https://drive.google.com/file/d/1wTnx4tf8ezHuJsitcTNkDZ5K2j5u6RGq/view?usp=sharing

**Comment by SiegeLord** [comment]
I fixed the crashes, but I don't know what's wrong with the file. VLC can't play it, and I also tested the minimp3's bundled player, which couldn't play it either. But a few other players could handle it, like you said.

**Comment by SiegeLord** [comment]
I don't think this is an mp3 file, so far it looks like a webm file.
