### ISSUE TITLE
[osx] ALLEGRO_TEXTLOG_MONOSPACE option for al_open_native_text_log doesn't work

### ISSUE THREAD

**Issue by connorjclark** [liballeg/allegro5#1592]
The text dialog I get when doing this does not use monospace, even though the [implementation](https://github.com/liballeg/allegro5/blob/8bc18c0d43b35996b3c201c0ef9b2d0472109d55/addons/native_dialog/osx_dialog.m#L338-L340) seems correct to me.

> m_textlog = al_open_native_text_log("ZScript", ALLEGRO_TEXTLOG_MONOSPACE);

<img width="633" alt="image" src="https://github.com/user-attachments/assets/fb1a0f60-a8e6-4d43-b5e6-8013f500d71d">

**Comment by SiegeLord** [comment]
Thanks, I have a fix ready.
