### ISSUE TITLE
Add al_set_new_window_title

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#478]
Like it says above. Avoids an visually annoying split second wrong title.

**Comment by fatcerberus** [comment]
Oh wow, this has been annoying me for a while but I never thought to put in a feature request for it because it seemed such a trifling thing.  So it's good that someone else thought of it too. :smile:

**Comment by beoran** [comment]
Please check the pull request and see if it's OK.

**Comment by beoran** [comment]
This has been implemented. Please test it and report any problems.
