### ISSUE TITLE
al_load_config_file() skips the first [section] if it is the very first line in the file

### ISSUE THREAD

**Issue by MarkOates** [liballeg/allegro5#481]

**Comment by SiegeLord** [comment]
Do you have an example file that triggers this? My simple tests seem to pass.

**Comment by MarkOates** [comment]
Interesting. It appears that `al_get_first_config_section()` will return the global section if the first line is empty, even if the global section contains no values.  If the first line is a `[labeled section]`, then it will return that section.

I assumed that if the global section was empty (e.g. adding cosmetic empty lines at the top) then it wouldn't be parsed as the first section.  Maybe a note should be added in the docs? perhaps "...in the given config file. Usually this will return an empty string for the global section, even if the global section contains no values."

**Comment by SiegeLord** [comment]
So the reason this happens it that Allegro tries to preserve the whitespace/comments when you load a config file and save it. Those cosmetic lines are preserved by sticking them into the global section. I've added a comment in the documentation, as you suggested. Thanks!
