### ISSUE TITLE
fallback font

### ISSUE THREAD

**Issue by allefant** [liballeg/allegro5#484]
It would sometimes be useful to have a fallback font in case a character is not available in a font. This is what all OS level text output usually does. I'm thinking of something simple like:

    font1 = al_load_font(...)
    font2 = al_load_font(...)
    al_set_fallback_font(fon2, font1)
    al_draw_text(font2, "X")

And now if font2 does not have "X" it would try getting the glyph from font1 instead. It would be up to the user to make sure the size and style and so on match.

**Comment by beoran** [comment]
For this use case, I'd say per-glyph font functions could be useful, like I proposed in #6. I'd just have to add an `al_font_has_glyph(ALLEGRO_FONR * font, int glyph);` function. Then the users can decide on where and how to render a fallback themselves.

**Comment by beoran** [comment]
@allephant, I have brought the per glyph functions back to mergeable state, would they cover your use case or not?

**Comment by elias-pschernig** [comment]
Where are they?

**Comment by beoran** [comment]
Here ==> #6 <== :)

**Comment by elias-pschernig** [comment]
Ah, no, that can't be used at all for what I need. I want to do this:

    al_draw_text("My name is 象 and I like Japanese ♥♥♥!");

And I have one main font (which has only Latin1 glyphs), one Japanese font, and one font with all the emoticons. Right now any glyph not in the main font will simply render as a box, and your new functions will return properties of that box glyph instead of telling me it doesn't exist.

I'll make a patch.

**Comment by beoran** [comment]
No, the sizing functions I implemented will tell you when the glyph doesn't exist. 

But I see your point, a fallback font coud be useful, for people who want to simple per string output. However, is it recursive? If it is it'd be easy to set up a fallback loop, that's something to watch out for. Also, could you please wait with your patch until my per glyph stuff is merged? Like that we can avoid a few possible merge conflicts...

**Comment by trentg** [comment]
Test it and double check everything (as always) and merge it.

**Comment by beoran** [comment]
OK

**Comment by beoran** [comment]
@allefant is your implementation ready? Then we can close this issue as well...

**Comment by elias-pschernig** [comment]
Yes, see PR #502 - not sure how to link them.

**Comment by elias-pschernig** [comment]
Ah, should have put "fixes #484" into any commit message and github would have auto closed :)
