### ISSUE TITLE
TTF re-locking causes missing glyphs

### ISSUE THREAD

**Issue by goobliata** [liballeg/allegro5#495]
This seems to be a very device specific problem, looking for leads on what's causing it. Whenever the page bitmap is re-locked, the first glyph drawn shows up blank on Samsung S6. I know this because I tried calling al_get_text_width on the entire translation and only the first character on a new row other than the first row is blank, which is how the locking works. I tried different sized fonts which results in different first characters on rows and those characters are also blank. When not calling al_get_text_width like this, many more characters are blank which I assume must be the first characters in each lock (but I don't have a good way to test this as I don't have the device in my possession.) This problem doesn't affect all Androids, right now the only one I know of is the S6. 
Potential suspects: ttf addon, OpenGL ES locking code, ???.

Attached the output from debug_cache in TTF addon using the same font size as used on S6. The first characters in the second, third and fourth rows are blank (O, 2, 0) on S6. (background has been coloured black so you can see the glyphs on the white webpage background...)

![font](https://cloud.githubusercontent.com/assets/766383/9747602/d5ea3be0-563b-11e5-89e7-957e7bd3b6db.png)

**Comment by trentg** [comment]
A version of the game compiled with the font addon changes up to and including August 15, 2013 works fine.

**Comment by trentg** [comment]
Got to thinking this may be a driver bug, so Googled to see if anyone has found that glTexSubImage2D followed by glFlush fixes any problems. Found the exact same issue with Cocos2D:

https://github.com/cocos2d/cocos2d-x/issues/9499

What I'm going to attempt is a single line patch that will try to recache any glyph if the locking fails initially... all it does is set glyph->page_bitmap to NULL before returning NULL from alloc_glyph_region. I'm hoping this fixes it...

**Comment by trentg** [comment]
If not perhaps calling glFlush will fix it but that's a pretty horrible solution.

**Comment by trentg** [comment]
Actually the solution I proposed doesn't make sense, since the locking itself just mallocs a buffer. Hopefully glFlush fixes it.

**Comment by trentg** [comment]
One potential way to fix this would be to use accelerated drawing (al_draw_pixel) to draw the characters instead of locking.

**Comment by trentg** [comment]
If anyone comes across this, here's how I've fixed it in my game... First you need to patch Allegro like this:

https://gist.github.com/trentg/4c79372c1da4f45b349b

Next, I load all translations (every language) and concatenate them all into one string, then call al_get_text_width on that string. Horrible. Ugly. But it works.

**Comment by beoran** [comment]
Yikes, what is his I don't even... O_o

Seriously, something's fishy with either OpenGL ES, the ttf font cache, or both. We have to solve it in the long run.

**Comment by trentg** [comment]
This happened to another user of mine with a different device. Maybe a load flag that uses separate bitmaps instead of an atlas would be best.

**Comment by SiegeLord** [comment]
Alternatively, perhaps we could use some non-locking way of populating the atlas (e.g. drawing the glyph to a temporary bitmap via a full lock, and the updating the atlas via `al_draw_bitmap_region`).

Also, did you try using a readwrite lock? Those are more stable in my experience.

**Comment by SiegeLord** [comment]
Hey @trentg, do you still have access to devices that show this behavior? I think I want to try inserting the workaround similar to what you described into the addon (probably disabled by default, but easy to enable if needed).

**Comment by trentg** [comment]
No I don't, unfortunately.

**Comment by fatcerberus** [comment]
Does this affect the S5 as well?  I have one laying around somewhere, I'd need someone to direct me how to compile Allegro for Android though.

**Comment by elias-pschernig** [comment]
There's https://github.com/liballeg/allegro5/blob/5.1/README_android.txt but I'd say simply follow these step-by-step instructions (we should probably sync both documents at some point): https://wiki.allegro.cc/index.php?title=Running_Allegro_applications_on_Android

And a warning, expect several hours before you actually have ex_ttf run on your device, some of the steps are quite involved (like getting the Android SDK installed in the first place).

**Comment by trentg** [comment]
It affects the S6 but not necessarily the S6. I don't remember the other device but I want to say Sony Z1?

**Comment by trentg** [comment]
I put up demos of the games exhibiting this bug:

http://nooskewl.ca/crystal-picnic
http://nooskewl.ca/monster-rpg-2

Though I can't verify myself, but I have to assume it's still there because these builds use Allegro straight from git.

**Comment by trentg** [comment]
When I made the previous gist, it was incomplete, so of course when I had to do an update of my games, the bug was back... so I've done additions to that patch here:

https://gist.github.com/trentg/bbcb173664ccfa7e0448

@SiegeLord I have someone who may test a proper patch for this issue. The main things that need to happen are only ever locking a page once (never unlocking in between glyph caches.) The problem with that is the user of the library will need to send you the characters they need to cache. In my hackish patch it just uses al_get_text_width. I think a fix to this problem could be adding a new function that caches multiple glyphs in one pass.

**Comment by SiegeLord** [comment]
I've implemented what I had in mind in #562. It doesn't have the restriction to lock only once, or the documentation bit... I could probably add those in.

**Comment by trentg** [comment]
@SiegeLord, I guess then you knew about the issue I mentioned in my comments on the patch?

**Comment by SiegeLord** [comment]
Alright, #563 has a slightly reworked approach to that. It now has an explicit way to specify which glyphs you want to cache and whether not you want to never relock after the initial caching.

**Comment by trentg** [comment]
Nice, thank you. I'll make a build of a game using this and ask the person who has helped me testing this bug to try it.

**Comment by SiegeLord** [comment]
Any progress on trying this out? I think the patch is probably ok, but I just want to make sure it actually solves the issue in a real application.

**Comment by trentg** [comment]
I think I way overstepped my bounds last time by asking the guy to test about 50 builds. I don't want to email him asking to test again.

**Comment by goobliata** [comment]
Well I implemented the new pre-cache-from-config in my games, and I haven't heard anything bad so I will assume that it is fixed. Perhaps a better solution would be to create each glyph as an ALLEGRO_BITMAP and al_draw_bitmap it onto a sheet... but really this solves it in a way that's not too difficult.
