### ISSUE TITLE
CMake doesn't find GDIplus

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#510]
Fresh checkout of Allegro 5.1.12, CMake runs but fails to find GDIplus.  Compiler is MSVC 2015.

**Comment by SiegeLord** [comment]
Could you look into your CMakeError.log (inside the CMakeFiles directory inside your build directory)? It should contain the output of the compile test we use to detect gdi+.

**Comment by fatcerberus** [comment]
I searched through CMakeError.log for GDIPlus, GDI+, etc. and couldn't find anything.  So here's the full log after a fresh CMake configure pass:
https://drive.google.com/open?id=0BxPKLRqQOUSNOEd6US1OT0xWb2M

**Comment by SiegeLord** [comment]
Whoops, looks like the output I want is in `CMakeOutput.log`.

**Comment by fatcerberus** [comment]
Alright, here it is:
https://drive.google.com/open?id=0BxPKLRqQOUSNT215TU1JME5uVTg

**Comment by fatcerberus** [comment]
Having taken a quick look through the CMake scripts, I can't find any place where GDIPLUS_FOUND is set?

**Comment by elias-pschernig** [comment]
This is how we detect GDI+, it seems there is no logging on failure:

https://github.com/liballeg/allegro5/blob/5.1/cmake/FindGDIPLUS.cmake

You can check in CMakeCache.txt and see what GDIPLUS_INCLUDE_DIR and GDIPLUS_LIBRARY are set to. If one or both are set to NOTFOUND, maybe we can figure out why. Is maybe only the library found but not the header? First google result for "cmake gdiplus" suggests people are using a different header name than GdiPlus.h which we expect...

**Comment by fatcerberus** [comment]
They are indeed both set to NOTFOUND.

**Comment by SiegeLord** [comment]
Yeah, so the solution is probably to fold this searching code into `FindDirectX.cmake` (and renaming that file), as that file knows how to look at different SDKs.

**Comment by fatcerberus** [comment]
Even so, it doesn't make sense that it can't find it--it correctly guessed the MSVC directory and there is indeed a GdiPlus.h in the Windows SDK include directory, so I have no idea why this worked with MSVC 2013 but not the new version.

**Comment by SiegeLord** [comment]
Oh, I didn't realize it worked at all before... that is confusing.

**Comment by fatcerberus** [comment]
Yeah, it used to work when I used MSVC 2013, now it's stopped working, which is odd because both versions have the same Windows SDK (7.1A).

**Comment by trentg** [comment]
It may be a change in CMake or something because IIRC the last time I tried it failed for me also with MSVC 2013. I just passed the GDIPLUS_INLCUDE_DIR or whatever manually and forgot about it.

**Comment by fatcerberus** [comment]
Hm, I'll try doing that.  I wasn't sure if it would work because CMake is bad about rebuilding stuff when options change, for example failed compile tests due to the wrong .lib will continue to fail even if you change the library path to the correct one.  I learned all this the hard way unfortunately. :(

**Comment by trentg** [comment]
Well doesn't hurt to report it still... ideally it could be fixed.

**Comment by Rottweiller-OS** [comment]
Sorry guys but not to ask, this place is strange for me I feel like I censored passeth good point.
I have trouble installing this nice allegro one thing check with garbage and patches on patches on more patches patched patches and patches patches that some idiot called slackware or slax, specifically I mean wifislax, I can not make fubcione and actually much of this is my aversion to etas slackware based distributions, use the LFS is only mine but for my use, and school is fashionable feel hacker and if not, then it screwed me and tube to install this thing wifislax horrendous call by a terrible thing check exolcar Spaniards who do not know how it works, and end up telling you not look for your count, and Jan here, asking a little attention
![empty0](https://cloud.githubusercontent.com/assets/15120845/10597039/6568557e-76b0-11e5-9a37-572052365ff8.png)
![empty1](https://cloud.githubusercontent.com/assets/15120845/10597040/656ed9a8-76b0-11e5-980e-19c8dd96a4fe.png)
![empty2](https://cloud.githubusercontent.com/assets/15120845/10597041/657b84d2-76b0-11e5-837b-e4786a2a9887.png)
![empty3](https://cloud.githubusercontent.com/assets/15120845/10597042/65829c68-76b0-11e5-857d-4b5df903fcd9.png)
![empty3-1](https://cloud.githubusercontent.com/assets/15120845/10597043/65880f68-76b0-11e5-9e14-68fc6468953b.png)
![empty4](https://cloud.githubusercontent.com/assets/15120845/10597044/658b075e-76b0-11e5-8a3a-c0f983824df1.png)
![empty4-1](https://cloud.githubusercontent.com/assets/15120845/10597045/6595ba64-76b0-11e5-86f7-d5940ea13b05.png)
![empty4-2](https://cloud.githubusercontent.com/assets/15120845/10597057/65f08980-76b0-11e5-9c8c-2e3fbd34976e.png)
![empty5](https://cloud.githubusercontent.com/assets/15120845/10597046/65a4736a-76b0-11e5-8c20-396c09a849bc.png)
![empty6](https://cloud.githubusercontent.com/assets/15120845/10597047/65abcb60-76b0-11e5-8cde-1d130c2ff80e.png)
![empty7](https://cloud.githubusercontent.com/assets/15120845/10597048/65b502a2-76b0-11e5-902e-ca2d338c5456.png)
![empty8](https://cloud.githubusercontent.com/assets/15120845/10597049/65baf522-76b0-11e5-8a85-1faa439a97a6.png)
![empty9](https://cloud.githubusercontent.com/assets/15120845/10597050/65c22ef0-76b0-11e5-9ed3-7a0997f48d3a.png)
![empty10](https://cloud.githubusercontent.com/assets/15120845/10597051/65c9ed20-76b0-11e5-9d50-0f0baef2339f.png)
![empty11](https://cloud.githubusercontent.com/assets/15120845/10597052/65d12284-76b0-11e5-9704-28f3fee898f4.png)
![empty12](https://cloud.githubusercontent.com/assets/15120845/10597053/65d9b750-76b0-11e5-8bb5-951388d0eafe.png)
![empty13](https://cloud.githubusercontent.com/assets/15120845/10597054/65e06b54-76b0-11e5-8e1f-5af94dc083a5.png)
![empty14](https://cloud.githubusercontent.com/assets/15120845/10597055/65ea2f40-76b0-11e5-821e-c961855c75fc.png)
![empty15](https://cloud.githubusercontent.com/assets/15120845/10597056/65ef6230-76b0-11e5-9786-fcff60746e4d.png)
![empty16](https://cloud.githubusercontent.com/assets/15120845/10597058/65f70f8a-76b0-11e5-8c35-0d4ebe37db3f.png)
![empty17](https://cloud.githubusercontent.com/assets/15120845/10597059/66007f5c-76b0-11e5-930c-7dfc4169b620.png)
![empty18](https://cloud.githubusercontent.com/assets/15120845/10597060/66082d2e-76b0-11e5-8bca-84a8132d5a2c.png)
![empty19](https://cloud.githubusercontent.com/assets/15120845/10597061/6611ba10-76b0-11e5-8d7b-2f0221c62f24.png)
![empty20](https://cloud.githubusercontent.com/assets/15120845/10597062/661d429a-76b0-11e5-8b53-57419e20111d.png)
![empty21](https://cloud.githubusercontent.com/assets/15120845/10597063/662412dc-76b0-11e5-8f29-6fe46eb094b6.png)
![empty22](https://cloud.githubusercontent.com/assets/15120845/10597064/66271554-76b0-11e5-89c6-0d662482bf22.png)
![empty23](https://cloud.githubusercontent.com/assets/15120845/10597065/662fefd0-76b0-11e5-9ea4-ec662403a1cb.png)
![empty24](https://cloud.githubusercontent.com/assets/15120845/10597066/6638dd84-76b0-11e5-934b-c9a7c8158ea4.png)
![empty25](https://cloud.githubusercontent.com/assets/15120845/10597067/664022d8-76b0-11e5-9a14-167f30db0c7a.png)
![empty26](https://cloud.githubusercontent.com/assets/15120845/10597068/6645d4b2-76b0-11e5-8bb2-bf1c4530e835.png)

**Comment by fatcerberus** [comment]
Even with the recent changes, CMake is still failing to find GDI+ for me (MSVC2015, Win10).

**Comment by fatcerberus** [comment]
Nevermind, I got it working, just had to blow away the cmake cache.  I'll close this.

**Comment by beoran** [comment]
@Rottweiller-OS 

You're not in the right place here, but you need to instal the DUMB library, either through your package manager, or compile the DUMB library from sources and install it, then CMake should be able to find it. And please don't work as the root user, it's risky.
