### ISSUE TITLE
Network drive returns wrong path in native file dialog

### ISSUE THREAD

**Issue by yayjaa** [liballeg/allegro5#511]
Network drive returns wrong path in native file dialog

    al_show_native_file_dialog(display, f);
    const char* file_path = al_get_native_file_dialog_path(f, 0);

+		file_path	0x06cf6a08 "//NVSURFPhotos\\\\S2\\\\858HDJES\\\\IMG_3012.JPG"	const char *

From directory(explorer): 
\\\\NVSURF\Photos\S2\858HDJES

so one slash is missing just before Photos
first two slashes point the other way (may not be issue)

On windows static link build 2012(2013 actually)
Local paths work fine

5.010

**Comment by yayjaa** [comment]
full code:

#include <stdio.h>
#include <allegro5/allegro.h>
#include <allegro5/allegro_image.h>
#include <allegro5/allegro_native_dialog.h>

ALLEGRO_BITMAP* load_yuv(const char* filename)
{
    return 0;
}

int main(int argc, char **argv)
{
    ALLEGRO_DISPLAY *display = NULL;
    ALLEGRO_BITMAP *bitmap;
    int width = 720;
    int height = 576;
    int button;

    if(!al_init()) {
        const char* failure = "failed to initialize allegro!\n";
        fprintf(stderr, failure);
        button = al_show_native_message_box(display, "Error", "Failure", failure, NULL, ALLEGRO_MESSAGEBOX_WARN);
        return -1;
    }

    if(!al_init_image_addon()) {
        const char* failure = "could not run al_init_image_addon!\n";
        fprintf(stderr, failure);
        button = al_show_native_message_box(display, "Error", "Failure", failure, NULL, ALLEGRO_MESSAGEBOX_WARN);
        return -1;
    }

    if(!al_init_native_dialog_addon()) {
        const char* failure = "could not run al_init_native_dialog_addon!\n";
        fprintf(stderr, failure);
        button = al_show_native_message_box(display, "Error", "Failure", failure, NULL, ALLEGRO_MESSAGEBOX_WARN);
        return -1;
    }

    if(!al_register_bitmap_loader(".yuv", load_yuv))
    {
        const char* failure = "could not register load_yuv!\n";
        fprintf(stderr, failure);
        button = al_show_native_message_box(display, "Error", "Failure", failure, NULL, ALLEGRO_MESSAGEBOX_WARN);
        return -1;
    }

    ALLEGRO_FILECHOOSER* pic_yuv_file = al_create_native_file_dialog("/", "Open file", "*.*", ALLEGRO_FILECHOOSER_PICTURES);
    

    al_set_new_bitmap_format(ALLEGRO_PIXEL_FORMAT_ARGB_8888);

    display = al_create_display(width, height);
    if(!display) {
        fprintf(stderr, "failed to create display!\n");
        return -1;
    }

    bitmap = al_get_backbuffer(display);
    al_set_target_backbuffer(display);

    al_clear_to_color(al_map_rgb(0, 0, 0));

    al_show_native_file_dialog(display, pic_yuv_file);
    const char* file_path = al_get_native_file_dialog_path(pic_yuv_file, 0);
    ALLEGRO_BITMAP * bmp = al_load_bitmap(file_path);
    int w = al_get_bitmap_width(bmp);
    int h = al_get_bitmap_height(bmp);
    al_draw_scaled_bitmap(bmp, 0, 0, w, h, 0, 0, width, height, 0);

    
    al_hold_bitmap_drawing(true);
    al_lock_bitmap(bitmap, ALLEGRO_PIXEL_FORMAT_ANY, ALLEGRO_LOCK_WRITEONLY);
    for(int x = 0; x < 255; x++) {
        al_put_pixel(100+x, 100+x, al_map_rgba(0xff, 0xff, 0xff, 0));
    }
    al_unlock_bitmap(bitmap);
    al_hold_bitmap_drawing(false);

    al_flip_display();

    al_rest(10.0);
    al_destroy_bitmap(bmp);
    al_destroy_native_file_dialog(pic_yuv_file);
    
    al_destroy_display(display);

    return 0;
}

**Comment by elias-pschernig** [comment]
There was an off-by-one bug causing the first path separator to miss in any UNC bug, should be fixed now in git. The issue with the wrong slashes still remains - I'm not sure if UNC paths can be passed to things like al_load_bitmap at all and if so, whether the slashes matter.
