### ISSUE TITLE
Install Alegro 5.0.11 on wifislax 4.1.11 ( based on sackware )

### ISSUE THREAD

**Issue by Rottweiller-OS** [liballeg/allegro5#514]
Sorry guys but not to ask, this place is strange for me I feel like I censored passeth good point.
I have trouble installing this nice allegro one thing check with garbage and patches on patches on more patches patched patches and patches patches that some idiot called slackware or slax, specifically I mean wifislax, I can not make fubcione and actually much of this is my aversion to etas slackware based distributions, use the LFS is only mine but for my use, and school is fashionable feel hacker and if not, then it screwed me and tube to install this thing wifislax horrendous call by a terrible thing check exolcar Spaniards who do not know how it works, and end up telling you not look for your count, and Jan here, asking a little attention
![empty0](https://cloud.githubusercontent.com/assets/15120845/10597336/75538c62-76b3-11e5-91d0-bdf3079c8f14.png)
![empty1](https://cloud.githubusercontent.com/assets/15120845/10597335/75506492-76b3-11e5-8d5b-72afd2e9f003.png)

then try to do it terminal, and the machine locked

![empty2](https://cloud.githubusercontent.com/assets/15120845/10597351/b1e21108-76b3-11e5-9d74-cff2520c4aee.png)
![empty3-1](https://cloud.githubusercontent.com/assets/15120845/10597380/ee78f8fc-76b3-11e5-9dfc-77f8b99d3e23.png)
![empty3](https://cloud.githubusercontent.com/assets/15120845/10597384/f649d0f6-76b3-11e5-98b4-a68d2c77c630.png)

apparently far as I understand if Complies with the requirements of Cmake and libraries, but a problem when Cmake tube did not find DDUMB, which will enlist the end because I have also problems with DUMB and could not compile, diplomatically sent me to hell Cmake

![empty4](https://cloud.githubusercontent.com/assets/15120845/10597464/d3923b4c-76b4-11e5-93e9-b3bc9d391ee3.png)
![empty4-1](https://cloud.githubusercontent.com/assets/15120845/10597465/d3a1f906-76b4-11e5-8582-91069a7f2bfa.png)
![empty4-2](https://cloud.githubusercontent.com/assets/15120845/10597466/d3a48c70-76b4-11e5-9460-0b4900112f8c.png)
![empty5](https://cloud.githubusercontent.com/assets/15120845/10597467/d3af7c8e-76b4-11e5-9b7a-e09ced4aff40.png)
![empty6](https://cloud.githubusercontent.com/assets/15120845/10597468/d3b95722-76b4-11e5-8b89-f4cdebedf47a.png)
![empty7](https://cloud.githubusercontent.com/assets/15120845/10597469/d3bacc06-76b4-11e5-92a9-809bd1db062d.png)
![empty8](https://cloud.githubusercontent.com/assets/15120845/10597470/d3c4977c-76b4-11e5-917e-9a6ac8645f19.png)
![empty9](https://cloud.githubusercontent.com/assets/15120845/10597480/d41e3d18-76b4-11e5-9050-75c05a5a09d3.png)
![empty10](https://cloud.githubusercontent.com/assets/15120845/10597478/d414925e-76b4-11e5-9463-655404991c3b.png)
![empty11](https://cloud.githubusercontent.com/assets/15120845/10597471/d3d5f486-76b4-11e5-9d29-3f3e34ce5dee.png)
![empty12](https://cloud.githubusercontent.com/assets/15120845/10597472/d3e2661c-76b4-11e5-9615-312da9d4a6f3.png)
![empty13](https://cloud.githubusercontent.com/assets/15120845/10597473/d3ea651a-76b4-11e5-8e28-da935c6d6807.png)
![empty14](https://cloud.githubusercontent.com/assets/15120845/10597474/d3f23556-76b4-11e5-8936-6b9095c65e2c.png)
![empty15](https://cloud.githubusercontent.com/assets/15120845/10597475/d3fdb7b4-76b4-11e5-8784-b166cddbe43d.png)
![empty16](https://cloud.githubusercontent.com/assets/15120845/10597476/d40636fa-76b4-11e5-8290-c0efee8eb215.png)
![empty17](https://cloud.githubusercontent.com/assets/15120845/10597477/d40da020-76b4-11e5-85a0-8c191b974b75.png)
![empty18](https://cloud.githubusercontent.com/assets/15120845/10597479/d41a357e-76b4-11e5-9f70-f7cb17e67097.png)
![empty19](https://cloud.githubusercontent.com/assets/15120845/10597481/d427a8b2-76b4-11e5-9767-2cb46d86833c.png)
![empty20](https://cloud.githubusercontent.com/assets/15120845/10597482/d42d90ce-76b4-11e5-884f-1393af16a155.png)
![empty21](https://cloud.githubusercontent.com/assets/15120845/10597483/d4354396-76b4-11e5-9076-4a4ab7d6c2ef.png)
![empty22](https://cloud.githubusercontent.com/assets/15120845/10597484/d43cf140-76b4-11e5-930b-2ff475c50bcc.png)
![empty23](https://cloud.githubusercontent.com/assets/15120845/10597485/d444c1e0-76b4-11e5-89ed-aa9f31593411.png)
![empty24](https://cloud.githubusercontent.com/assets/15120845/10597486/d44e4882-76b4-11e5-9d95-9e84d0115a0a.png)
![empty25](https://cloud.githubusercontent.com/assets/15120845/10597487/d49953ea-76b4-11e5-9a1a-eea448b04963.png)
![empty26](https://cloud.githubusercontent.com/assets/15120845/10597488/d4a369fc-76b4-11e5-9327-f73110015682.png)

Dumb Dainamic Universal Music Bibliotheque
http://dumb.sourceforge.net/index.php?page=news

in advance I say that a lot of linux, but not that garbage slackware and slax, never and studied architecture, I think we do something with cuts cuts and make a collage is like making a pinata of newspaper and glue, which some point will burst, and indeed so, their distros not last for a month installed on a machine in a stable, always thunder and you have to make a thousand malavares to re-raise if you either going, but if you have to install a new distribution. but this fashion everyone feels hacker, I wonder what Kevin Mitnick believes this fashion.

now cometh with regard to DUMB

![empty27](https://cloud.githubusercontent.com/assets/15120845/10611105/380500f4-7710-11e5-8c34-0cd9151ddd24.png)
![empty27-1](https://cloud.githubusercontent.com/assets/15120845/10611413/959e3c0c-7711-11e5-813e-7bee5f477f8b.png)
![empty29](https://cloud.githubusercontent.com/assets/15120845/10613784/54b7039e-771c-11e5-8682-e0250830acb5.png)

**Comment by bambams** [comment]
It's very difficult to understand you. I gather that you're attempting to install Allegro and having trouble. You appear to be running "wifislax", a Slackware-based distribution. I am not familiar with it. The usual approach to building Allegro is installing development dependencies first. For example, in Debian you would install -dev packages for all of the dependencies (the -dev packages contain .h header files and other files needed only during development). These are needed for Allegro to build.

A list of dependencies for other distributions can be found on the wiki: https://wiki.allegro.cc/index.php?title=Getting_Started#Linux_2. They might offer you a clue as to which packages that you'll need. I'm not familiar with Slackware so I don't know just how robust their package repositories are. You may find it easier to install Allegro with a more popular distribution.

You may find that Google Translate does a better job of translating to English than you can (feel free to use this as practice if you like). There are a few Spaniards on https://www.allegro.cc/forums so you could also try asking for help there in hopes of finding some help in your native tongue.

**Comment by Rottweiller-OS** [comment]
*******************************************************************************************************************************
I also post about the same in Alegro.cc
Profile got there and it seems that only use Ubuntu, which personally is also crap, has grown so much that lost obgetivo and simplicity of what is sought

*******************************************************************************************************************************
Hi Bambams, and a lot of thanks.
yes i do, the problem whith slax & slakware, nhave much information on your temples or scripts, I tried to know the tree structure with which it was built, but it is very confusing as this check garbage (patches on patches)
who made this iso (wifislax 4.1.11) update and install everything through scripts, but their escripts writes new user called an idiot, and I mean the well, because it offended when questioned because he felt so proud and boasted their scripts with many failures progamación brutal, presumably because their escripts are especially for your distro and do not work, actually be hacker me that makes me laugh, nowadays a simple audit to call him hack, but anyway, Back then, the only thing that brings almost irrefutably installed correctly programming is the section where you can find several editors of C / C ++ and coodeblocks works very well because it is so light that iso.

the problem ultimately comes down to 2 things

1- if I try to install ALLEGRO, it asks for DUMB
..... 2 if you try to install DUMB, asking me to istale ALLEGRO

this is locked and honestly do not know how out of the loop

Give me this day to finish up all the post, and now with all you can obtain from information, could you give me a more focused council foremost you agradesco your attention and your time,

and I used debian, mint, ubuntu, kubuntu, redhat, not and struggled to establish configurations or facilities codeblocks & Alegro including dumb, but here it becomes very difficult because these Spaniards feel they are gods by a poorly performed distro, not has neither the 10% level of Kali Linux (bacltrack) only that is very light, his manager terminal is slap-get and not very good, and I like allegro codeblocks love, let me do many things in games, and ptros PROGRAMS where administrative and found a way to use Allegro libraries

wifislax is the distro for people who do not know programming or can do nothing in Terminal are just scripts and poorly programmed.

**Comment by elias-pschernig** [comment]
DUMB is an optional dependency, so if that's the only problem and you don't need to play .mod music, you can just ignore the message about DUMB missing - the rest of Allegro should build fine.

**Comment by Rottweiller-OS** [comment]
ok i try to day effter work and i coment you whath happen ok, again elias-cerinig ant thanks men

**Comment by Rottweiller-OS** [comment]
I forgot to mention that my native language is Arabic salam alaykum my friends, i live in Mexico and speak very good Spanish, English more less:
I speak a little Russian, German, Korean, Norwegian, Italian 70%, 50% Japanese, did not speak French I can not, I'm no talk or write, understand mmm ... very little to listen

**Comment by SiegeLord** [comment]
Nothing to fix here, as far as I can see. Check out the support section http://liballeg.org/ for more general help.
