### ISSUE TITLE
Linking to official MSVC static binaries exports symbols

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#515]
Specifically, symbols from libFLAC get exported (MSVC generates .lib and .exp files), as though `FLAC.lib` were compiled with DLL options.  Not a huge issue, but it probably increases compiled executable size unnecessarily.

**Comment by SiegeLord** [comment]
Fixed in https://github.com/SiegeLord/allegro_winpkg/commit/aa2f68362d4e5bc3fb99340d9e24abba24722d5b, thanks for reporting this!

**Comment by fatcerberus** [comment]
No problem, always happy to help!
