### ISSUE TITLE
 X11 support requires Xcursor library

### ISSUE THREAD

**Issue by pax2you4now** [liballeg/allegro5#516]
Hi,

installing allegro on ubuntu 15.04 64bit the command "cmake .." show this message:
CMake Error at CMakeLists.txt:570 (message):
  X11 support requires Xcursor library.
I've installed libxcursor-dev, libxcursor1, libxcursor-dbg.

Could you help me?

**Comment by SiegeLord** [comment]
Try deleting the CMakeCache.txt inside the build directory, and re-running cmake.

**Comment by pax2you4now** [comment]
It woks! 
Thx!
