### ISSUE TITLE
al_get_monitor_info and ALLEGRO_DEFAULT_DISPLAY_ADAPTER

### ISSUE THREAD

**Issue by troutsneeze** [liballeg/allegro5#520]
This function fails, at least with Direct3D, when using said constant. I expected it to use the same monitor as al_set_video_adapter would... that might be impossible, I haven't looked at code yet, but if it's possible it would make a lot of sense. I had to pass 0.

**Comment by SiegeLord** [comment]
Yeah, it's a general thing. `adapter` passed to `al_get_monitor_info` has to be a real adapter. It does seem useful to support passing `ALLEGRO_DEFAULT_DISPLAY_ADAPTER` though.

**Comment by troutsneeze** [comment]
Probably not needed, I was just using it wrong.
