### ISSUE TITLE
AllegroInputStream broken on 64 bit

### ISSUE THREAD

**Issue by elias-pschernig** [liballeg/allegro5#528]
AllegroInputStream uses an "int handle;" field to hold a C pointer - this is bound to crash on 64 bit architectures. I guess one solution would be to use "long" instead of "int", or even better avoid the unsafe cast alltogether and find a way to not have to store a C pointer in Java - but not sure that's feasible.

**Comment by kazzmir** [comment]
Related stackoverflow thread

https://stackoverflow.com/questions/1632367/passing-pointers-between-c-and-java-through-jni

**Comment by beoran** [comment]
The slightly safer way to do it is to allocate a java array of size sizeof(pointer) and store the pointer in that array.
