### ISSUE TITLE
al_set_clipboard_text() cuts off last character

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#530]
For example:
```c
al_set_clipboard_text(NULL, "Stupid pig");
/* Pastes: "Stupid pi" */
```

This is Allegro 5.1.12 official, Windows 10 x64.

**Comment by trentg** [comment]
All platforms?

**Comment by fatcerberus** [comment]
I can only vouch for Windows, I just implemented error copying in my engine a few minutes ago and noticed the glitch.

**Comment by trentg** [comment]
Check ex_clipboard if it works. Works here.

**Comment by trentg** [comment]
Actually does not... it's missing the !

**Comment by trentg** [comment]
Strange because I've used it for gzipped data (hex-encoded gzipped saved state) and it gunzips fine. But it's obviously broken.

**Comment by trentg** [comment]
Is it possible that it expects a NULL terminator in the string in src/win/wclipboard.c:~86? Looks like maybe, from here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms649016(v=vs.85).aspx#_win32_Copying_Information_to_the_Clipboard

**Comment by trentg** [comment]
Fixed. Was missing NULL terminator.

**Comment by fatcerberus** [comment]
Thanks!

**Comment by beoran** [comment]
Thanks, I, completely missed that.
