### ISSUE TITLE
No Ubuntu PPA for 5.1.12

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#534]
There is apparently no Ubuntu PPA available for Allegro 5.1.12.  This prevents me from using the new features without breaking my Travis build.  Any chance the PPA will be updated?

**Comment by SiegeLord** [comment]
Making Ubuntu packages is unfortunately a very laborious process that is hard to automate, hence me procrastinating with it. I'll see if I can hurry it up.

**Comment by fatcerberus** [comment]
I know how you feel, building Allegro from source on Windows isn't very fun either.

**Comment by SiegeLord** [comment]
Alright, I pushed 5.1.12 packages for precise, trusty, vivid and wily. Hopefully they work fine!

**Comment by fatcerberus** [comment]
Something seems to be missing.  After retrieving Allegro 5.1.12 with `apt-get`, this is reported during compilation (Travis appears to be running precise):

```
/usr/include/allegro5/allegro.h:34:32: fatal error: allegro5/clipboard.h: No such file or directory
```

**Comment by SiegeLord** [comment]
Ah darn it, #503 strikes again. I'll re-upload them this evening.

**Comment by fatcerberus** [comment]
Sounds pretty dumb on Debian's part.  Maybe there's a way to automate that somehow.

**Comment by SiegeLord** [comment]
In part it's self inflicted. We split apart Allegro packages, so we need to specify which headers go with which addon. Anyway, I re-uploaded the packages. This time I tested them a bit, so it should work better now.

**Comment by fatcerberus** [comment]
Travis is passing again for minisphere, so it looks like this is fixed.  Thanks!
