### ISSUE TITLE
acodec dynamic load causing grief

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#536]
I've had several OS X testers have to compile Allegro manually because 5.1 is not available on Homebrew.  Invariably, I get a report that sound doesn't work in minisphere, which turns out to be because Allegro failed to load libvorbis at runtime.  Should we turn off the dynamic load option by default?

**Comment by SiegeLord** [comment]
But 5.1 is available on homebrew... `brew install --devel allegro`.

I do sort of agree that this dynamic loading probably is more bad than good...

**Comment by SiegeLord** [comment]
Actually, that wouldn't help as homebrew also compiles it with dynamic loading. It's probably a no-brainer to disable it for there (I already do so for windows binaries). What do you think?

**Comment by fatcerberus** [comment]
Probably for the best, it tends to cause a lot of confusion because they see allegro_acodec builds successfully but still can't load any audio formats at runtime.  If it were me, I'd set `WANT_ACODEC_DYNAMIC_LOAD=0` by default for CMake.  In my experience people almost never want dynamic loading, and I can already compile out the codecs I don't need via other variables, so 9 times out of 10 it's more of a hassle than a help.

Thanks for the tip on 5.1 homebrew, I don't have a Mac myself so I wasn't aware of the `--devel` flag.  Is it 5.1.12?  If so I can stop telling my testers they have to build Allegro themselves. :)

**Comment by SiegeLord** [comment]
Yes, it's 5.1.12.
