### ISSUE TITLE
Android build broken

### ISSUE THREAD

**Issue by trentg** [liballeg/allegro5#543]
commit 9dc88eddcf9b368fae412854d645176511038d74 by Reuben Bell "Implemented get_monitor_info for Android" breaks compatibility with Android 12. Should be obvious, since the code is doing "if (android_version > 13) { android 13 specific code here }".

**Comment by trentg** [comment]
The previously correct way to get the screen size in Android was to use ALLEGRO_FULLSCREEN_WINDOW and then al_get_display_width/height.

**Comment by SiegeLord** [comment]
Well of course it wouldn't build, but are you saying it doesn't run on android < 13? The official SDK is full of examples of using runtime checks like that for newer features.

**Comment by trentg** [comment]
No it probably runs but it doesn't build.

**Comment by trentg** [comment]
Not that running but not building with SDK 12 is useful.

**Comment by trentg** [comment]
Does the else part not work on SDK 13 and up?

**Comment by SiegeLord** [comment]
I'm confused. Typically you'd build with the newest SDK, but make the app work with versions lower than that through reflection and these version checks. Is that not how it works?

**Comment by trentg** [comment]
I usually build with the SDK I'm targetting, but that might work as long as you stick the target SDK in the manifest.

**Comment by trentg** [comment]
I know for certain that you can't build with the latest NDK for all targets though... so I don't know if you can mix and match SDK and NDK. Shared libraries on older phones have different symbols than the ones in the new NDK.

**Comment by trentg** [comment]
IIRC it was sqrt. It's inlined in old or new and not in the other, so you can't use the new NDK to build for old devices.

**Comment by trentg** [comment]
Can't find the issue now, might be thinking of something else... anyway I'll have to try what you said later. I guess I'll close this for now.
