### ISSUE TITLE
Finish implementing al_set_new_window_title

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#544]
It should set the window title right at the time the platform function does so, rather than afterward like it does now.

- [x] Windows DX
- [x] Windows GL
- [ ] OSX
- [ ] Linux

**Comment by fatcerberus** [comment]
I tried making a test change to implement this for Windows, and the resulting display got the default title (i.e. the value passed to `al_set_app_name`) instead of the string I provided.  This seems to indicate that, for Windows at least, the window is actually created *before* a display is?

**Comment by trentg** [comment]
Yes, window is created before the display because to create a Direct3D display you need a window.

**Comment by fatcerberus** [comment]
What I mean is, is the window created before the call to `al_create_display()`, preemptively?  It must be if my `al_set_new_window_title()` call isn't being honored after this change.

**Comment by trentg** [comment]
No, the window is created in al_create_display.

**Comment by fatcerberus** [comment]
In that case I'm completely stumped.  Having commented out the `al_set_window_title()` call in display.c and changed the window creation code to:

```c
   title_text = _al_win_utf16(al_get_new_window_title());
   my_window = CreateWindowEx(ex_style,
      L"ALEX", title_text, style,
      pos_x, pos_y, width, height,
      NULL,NULL,window_class.hInstance,0);
   al_free(title_text);
```

Creating a display like this:
```c
	al_set_new_window_title("pig");
	disp = al_create_display(640, 480);
```

Produces a window whose title is the filename of the application (or if `al_set_app_name` was called, that name instead), and not "pig" as expected.

**Comment by SiegeLord** [comment]
The issue is that the window is created on a separate thread, a thread that hasn't had `al_set_new_window_title` called yet, hence you getting the default value. There are a few TLS things like that that are manually plumbed through, so I just followed their pattern: ce24b939d4a9ec5bb74d33c5ff27ba38ae2980cb

**Comment by fatcerberus** [comment]
Thanks, I probably should have realized that when the helper to create the display had "thread_proc" in its name. :P

I noticed you only did the change in d3d_disp.cpp though.  It also needs to be done for OpenGL for full Windows coverage.

**Comment by goobliata** [comment]
Looks like this was fixed was it not?

**Comment by goobliata** [comment]
I created two pull requests, one for OS X and one for Linux:

https://github.com/liballeg/allegro5/pull/643
https://github.com/liballeg/allegro5/pull/644
