### ISSUE TITLE
ALLEGRO_SINGLE_BUFFER broken in OS X

### ISSUE THREAD

**Issue by koro-xx** [liballeg/allegro5#546]
In Mac OS X 10.9, an attempt to create a single buffer display with ALLEGRO_REQUIRE option is successful, but the display does not work properly. The following minimal example works as expected on Windows and Linux (gives a red screen) but on Mac OS it produces a black display:
```c
    al_set_new_display_flags(ALLEGRO_RESIZABLE | ALLEGRO_GENERATE_EXPOSE_EVENTS);
    al_set_new_display_option(ALLEGRO_SINGLE_BUFFER,1,ALLEGRO_REQUIRE);
  
    display=al_create_display(640, 480);
    if(!display) {
        fprintf(stderr, "failed to create display 1!\n");
        return -1;
    }
  
    al_set_target_bitmap(al_get_backbuffer(display));
    al_clear_to_color(al_map_rgb(255,0,0));
    al_flip_display();
    al_rest(10);
```

**Comment by SiegeLord** [comment]
Could you try this patch, it seems to help on my OSX:

```diff
diff --git a/src/macosx/osxgl.m b/src/macosx/osxgl.m
index 4ee2cd2..d0cccb3 100644
--- a/src/macosx/osxgl.m
+++ b/src/macosx/osxgl.m
@@ -1703,9 +1703,7 @@ static void flip_display(ALLEGRO_DISPLAY *disp)
    if (disp->extra_settings.settings[ALLEGRO_SINGLE_BUFFER]) {
       glFlush();
    }
-   else {
-      [dpy->ctx flushBuffer];
-   }
+   [dpy->ctx flushBuffer];
 
    if (old_target) {
       al_set_target_bitmap(old_target);

```

**Comment by koro-xx** [comment]
That doesn't seem to work here. But from what I you've told me, in  OS X 10.8 the behavior is a bit different than in 10.9. If I got it right you had a refresh problem, where moving the window or hovering the mouse on the window would cause the right color to appear. In 10.9 I don't get anything like that, just a plain white window.

**Comment by SiegeLord** [comment]
Alright, could you instead check out the patch in #552. This time I tested on 10.9 and a real device, so I'm reasonably confident it should work now.

**Comment by koro-xx** [comment]
Seems to work fine!

**Comment by SiegeLord** [comment]
Great! Thanks for reporting and testing.
