### ISSUE TITLE
CMake warning on 5.1 branch

### ISSUE THREAD

**Issue by Neurrone** [liballeg/allegro5#549]
I got the following warning when running cmake.

CMake Warning (dev) at docs/Refman.cmake:274 (configure_file):
configure_file called with unknown argument(s): COPY_ONLY
Call Stack (most recent call first):
docs/CMakeLists.txt:141 (include) 
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at docs/Refman.cmake:274 (configure_file):
configure_file called with unknown argument(s): COPY_ONLY
Call Stack (most recent call first):
docs/CMakeLists.txt:141 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by SiegeLord** [comment]
Thanks!
