### ISSUE TITLE
update to avcodec_decode_audio4

### ISSUE THREAD

**Issue by rcorre** [liballeg/allegro5#557]
Trying the `ex_video` example in 5.1.11 gives me:

```
[aac @ 0xdc6920] Custom get_buffer() for use withavcodec_decode_audio3() detected. Overriding with avcodec_default_get_buffer
[aac @ 0xdc6920] Please port your application to avcodec_decode_audio4()
```

The audio sounds corrupted when it plays.

Looks like it gets called [here](https://github.com/liballeg/allegro5/blob/5.1/addons/video/ffmpeg.c#L385).
I'm on Archlinux with ffmpeg 1:2.8.4-2.

**Comment by beoran** [comment]
Hmm, ffmpeg is a pain, they make it too much of a moving target. But I'll guess we'll have to detect the version at compile time and implement something different depending on it.

**Comment by SiegeLord** [comment]
FFmpeg backend is being temporarily removed in #603. When it is re-added, hopefully it won't have these bugs.

**Comment by SiegeLord** [comment]
Note that the audio being corrupted had nothing to do with this issue, the backend simply did not have correct handling of multi-channel planar audio streams.
