### ISSUE TITLE
Allegro locks up loading BMP file

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#575]
Attempting to load the file following .bmp file causes Allegro to lock up and use 100% of a CPU core until the process is killed:
https://drive.google.com/open?id=0BxPKLRqQOUSNZmFKMVR4NE9hSVU

Wanted to try to debug it myself, but the NuGet packages don't have PDBs so MSVC couldn't load the symbols.

**Comment by fatcerberus** [comment]
Further testing indicates this is a regression in 5.1.13; the bitmap is loaded without issue by 5.1.12.

**Comment by SiegeLord** [comment]
Very strange. It loads fine in Linux. I don't know of a mechanism which would cause this... did you use 32 or 64 bits for this?

**Comment by fatcerberus** [comment]
Tested on 64-bit version.  Haven't tried 32-bit, but downgrading to Allegro 5.1.12 made the issue go away.

**Comment by SiegeLord** [comment]
Yes, 5.1.13 had a lot of work done on the bitmap loading. Looks like there was a regression somehow. I'll investigate this. One other possible cause of this could be things like the `long` type (which I see used in the implementation) which I think has different sizes on 64 bits on Windows vs Linux.

**Comment by fatcerberus** [comment]
I believe `int` and `long` are both 32 bits on Windows whereas `long` is 64 bits on Linux.

**Comment by SiegeLord** [comment]
eba3d499d08dd0b36312612bcbc0006e59224d9f should fix it. Would it be convenient if I released a bugfix release of 5.1.13 or would you prefer to wait until the next release (probably in a month or so?)?

**Comment by fatcerberus** [comment]
There are a few issues with 5.1.12 that aren't showstoppers but are a bit annoying, if it's not too much trouble a 5.1.13 bugfix would be nice to have.  You wouldn't have to do Ubuntu packages, just NuGet.  I just use 5.0 for my Ubuntu releases since that's what's in the official repos.

**Comment by fatcerberus** [comment]
What was the bug by the way?

**Comment by SiegeLord** [comment]
This bug only affects MSVC, so I'd probably only re-make binaries for it. There's a separate code path for non-MSVC compilers, so this slipped by the few meager tests we have for this. There was just a missing `return` in the code which caused an infinite loop in certain situations (but only with MSVC).

**Comment by beoran** [comment]
Why do we even have  separate code paths here? OS-supported loading of bitmaps, perhaps?

**Comment by fatcerberus** [comment]
Thanks, this indeed fixed the bug. :smile:
