### ISSUE TITLE
d3d_lock_region ignores ALLEGRO_LOCK_WRITEONLY flag and copies video texture to system texture

### ISSUE THREAD

**Issue by Rseding91** [liballeg/allegro5#585]
Per the documentation at: https://www.allegro.cc/manual/5/al_lock_bitmap the ALLEGRO_LOCK_WRITEONLY is meant to give improved performance by skipping the video memory -> system memory copy of a video memory bitmap when locking a bitmap.

However, the flag appears to be ignored (under d3d) and the bitmap is always synced resulting in incredibly poor performance: https://github.com/liballeg/allegro5/blob/5.1/src/win/d3d_bmp.cpp#L877

In testing if I change the above conditional to:
`if (!(flags & ALLEGRO_LOCK_WRITEONLY) && !_al_d3d_sync_bitmap(bitmap))`

The video memory -> system memory copy is skipped and I get the expected performance when locking video memory bitmaps for write-only.

**Comment by beoran** [comment]
This seems an easy enough fix, but are there any side effects?

**Comment by Rseding91** [comment]
None that I've observed although I've only been running with it that way for a day.

**Comment by beoran** [comment]
Could you try running all (relevant) allegro examples and tests?

**Comment by SiegeLord** [comment]
This looks pretty harmless, I'll do some tests myself Friday or this weekend and hopefully nothing will break. Thanks for reporting this.
