### ISSUE TITLE
Allegro's cmake still fails to find GDI+

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#591]
GDI+ was supposed to have been fixed in #529, but I'm still getting failures when running CMake:

```
Could NOT find GDIPLUS (missing:  GDIPLUS_INCLUDE_DIR) 
WARNING: cannot use GDI+. Will try other libraries.
```

The value of `GDIPLUS_INCLUDE_DIR` is set to `GDIPLUS_INCLUDE_DIR-NOTFOUND` at this point.  If I set it manually to my WinSDK include path in cmake-gui and reconfigure, it will work.  But it will not find it by default.

**Comment by peterhull90** [comment]
Are you attempting a 32-bit or 64-bit build?

**Comment by fatcerberus** [comment]
32-bit.  I don't remember if I tried 64-bit yet, I usually do a 32-bit build with CMake and then once that works I add an x64 configuration to the MSVC project afterwards.

**Comment by fatcerberus** [comment]
Nope, 64-bit build has the same issue.  The compiler is MSVS 2015 installed with default selections, OS is Windows 10.

**Comment by peterhull90** [comment]
I got this for Windows 10, VS2015 Community, CMake 3.3.2:
```
-- Found DSOUND: C:/Program Files (x86)/Windows Kits/8.1/Include/um
-- Found XINPUT: C:/Program Files (x86)/Windows Kits/8.1/Include/um
D3DX9 not found. You will not be able to compress or decompress textures on the GPU.
-- Found GDIPLUS: C:/Program Files (x86)/Windows Kits/8.1/Include/um
-- Performing Test SUPPORT_GDIPLUS
-- Performing Test SUPPORT_GDIPLUS - Success
```
What do you have in your ` C:/Program Files (x86)/Windows Kits/`?

**Comment by fatcerberus** [comment]
I indeed have a `C:/Program Files (x86)/Windows Kits/8.1/Include/um` folder and it does contain `gdiplus.h`.  In fact it successfully finds DSound and XInput in there, it's just that for whatever reason it *doesn't* find GDIPlus and I have set `GDIPLUS_INCLUDE_DIR` manually.

Here's my full CMake log:
```
The C compiler identification is MSVC 19.0.23918.0
The CXX compiler identification is MSVC 19.0.23918.0
Check for working C compiler using: Visual Studio 14 2015 Win64
Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 14 2015 Win64
Check for working CXX compiler using: Visual Studio 14 2015 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Adding C:/src/allegro5/deps to CMAKE_PREFIX_PATH
Adding C:/src/allegro5/deps/x64 to CMAKE_PREFIX_PATH
Adding C:/src/allegro5/deps/x86 to CMAKE_PREFIX_PATH
Guessed MSVC directory: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
Check if the system is big endian
Searching 16 bit integer
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of unsigned short
Check size of unsigned short - done
Using unsigned short
Check if the system is big endian - little endian
Looking for include file dirent.h
Looking for include file dirent.h - not found
Looking for include file inttypes.h
Looking for include file inttypes.h - found
Looking for include file linux/input.h
Looking for include file linux/input.h - not found
Looking for include file stdbool.h
Looking for include file stdbool.h - found
Looking for include file stdint.h
Looking for include file stdint.h - found
Looking for include file sys/io.h
Looking for include file sys/io.h - not found
Looking for include file sys/stat.h
Looking for include file sys/stat.h - found
Looking for include file sys/time.h
Looking for include file sys/time.h - not found
Looking for include file time.h
Looking for include file time.h - found
Looking for include file sys/utsname.h
Looking for include file sys/utsname.h - not found
Looking for include file sys/types.h
Looking for include file sys/types.h - found
Looking for include file soundcard.h
Looking for include file soundcard.h - not found
Looking for include file sys/soundcard.h
Looking for include file sys/soundcard.h - not found
Looking for include file machine/soundcard.h
Looking for include file machine/soundcard.h - not found
Looking for include file linux/soundcard.h
Looking for include file linux/soundcard.h - not found
Looking for include file libkern/OSAtomic.h
Looking for include file libkern/OSAtomic.h - not found
Looking for include file sys/inotify.h
Looking for include file sys/inotify.h - not found
Looking for include file sal.h
Looking for include file sal.h - found
Looking for getexecname
Looking for getexecname - not found
Looking for mkstemp
Looking for mkstemp - not found
Looking for mmap
Looking for mmap - not found
Looking for mprotect
Looking for mprotect - not found
Looking for sched_yield
Looking for sched_yield - not found
Looking for sysconf
Looking for sysconf - not found
Looking for fseeko
Looking for fseeko - not found
Looking for ftello
Looking for ftello - not found
Looking for strerror_r
Looking for strerror_r - not found
Looking for strerror_s
Looking for strerror_s - found
Check size of _Bool
Check size of _Bool - done
Performing Test ALLEGRO_HAVE_PROCFS_ARGCV
Performing Test ALLEGRO_HAVE_PROCFS_ARGCV - Failed
Performing Test ALLEGRO_HAVE_SV_PROCFS_H
Performing Test ALLEGRO_HAVE_SV_PROCFS_H - Failed
Performing Test ALLEGRO_HAVE_VA_COPY
Performing Test ALLEGRO_HAVE_VA_COPY - Success
Found OpenGL: opengl32  
S3TC locking disabled. You will not be able to load/save pre-compressed textures with OpenGL.
Found DINPUT: C:/Program Files (x86)/Windows Kits/8.1/Include/um  
Found D3D9: C:/Program Files (x86)/Windows Kits/8.1/Include/shared  
Could NOT find D3DX9 (missing:  D3DX9_INCLUDE_DIR D3DX9_LIBRARY) 
Found DSOUND: C:/Program Files (x86)/Windows Kits/8.1/Include/um  
Found XINPUT: C:/Program Files (x86)/Windows Kits/8.1/Include/um  
D3DX9 not found. You will not be able to compress or decompress textures on the GPU.
Could NOT find GDIPLUS (missing:  GDIPLUS_INCLUDE_DIR) 
WARNING: cannot use GDI+. Will try other libraries.
Found ZLIB: C:/src/allegro5/deps/x64/lib/zlib.lib (found version "1.2.8") 
Found PNG: C:/src/allegro5/deps/x64/lib/libpng16.lib (found version "1.6.17") 
Found JPEG: C:/src/allegro5/deps/x64/lib/jpeg.lib  
Could NOT find D3DX9 (missing:  D3DX9_INCLUDE_DIR D3DX9_LIBRARY) 
Could NOT find OpenAL (missing:  OPENAL_LIBRARY OPENAL_INCLUDE_DIR) 
Could NOT find OPENSL (missing:  OPENSL_INCLUDE_DIR OPENSL_LIBRARY) 
Found FLAC: C:/src/allegro5/deps/include  
Performing Test FLAC_COMPILES
Performing Test FLAC_COMPILES - Failed
WARNING: libFLAC not found or compile test failed, disabling support.
Found DUMB: C:/src/allegro5/deps/include  
Performing Test DUMB_COMPILES
Performing Test DUMB_COMPILES - Success
Found OGG: C:/src/allegro5/deps/include  
Found VORBIS: C:/src/allegro5/deps/include  
Performing Test VORBIS_COMPILES
Performing Test VORBIS_COMPILES - Success
Found Freetype: C:/src/allegro5/deps/x64/lib/freetype.lib (found version "2.5.5") 
Found PhysFS: C:/src/allegro5/deps/x64/lib/physfs.lib  
Found PHYSFS: C:/src/allegro5/deps/x64/lib/physfs.lib  
Performing Test PHYSFS_IMPLICIT_ZLIB
Performing Test PHYSFS_IMPLICIT_ZLIB - Failed
Found THEORA: C:/src/allegro5/deps/include  
Could NOT find LATEX (missing:  LATEX_COMPILER) 
Configuring done
```

I saw you said CMake 3.3.2.  I'm using 3.5.1.  I think I remember seeing somewhere that they changed the Windows SDK search behavior in CMake 3.4.  I wonder if that's the cause?

**Comment by peterhull90** [comment]
I'll get the latest CMake and retry.

**Comment by peterhull90** [comment]
I completely deleted my build directory, uninstalled CMake, installed 3.5.1 and started again with CMake. I got the same as previous, i.e. GDI+ was found OK.

Not sure how to proceed. I think @SiegeLord has built the Windows libs recently, maybe he could advise (or at least be the tie-breaker !)

**Comment by fatcerberus** [comment]
Okay, so I figured out what the difference is: Running cmake directly from the command line from a VS2015 command prompt finds GDI+ successfully.  I normally use `cmake-gui` instead because it makes changing options easier.  But building from cmake-gui doesn't find GDI+ (it finds everything else though, weird).

**Comment by peterhull90** [comment]
OK, well, that's a result! Maybe a bug in cmake-gui although I thought it
was just a shell around the cmake 'engine.' I haven't got my PC with me now
but I can try and reproduce - if so I'll file a cmake bug.

**Comment by fatcerberus** [comment]
I opened a pull to fix this issue, #619.  It seems CMake doesn't find the 8.1 kit on Win10, preventing the search for gdiplus.h from working.  Since Allegro's CMake *does* find the DirectX libs, I reused that code to find GDI+.

**Comment by peterhull90** [comment]
Good work! But, yuck. it's a shame if that's the only way to do it. I never liked CMake :person_frowning:

**Comment by peterhull90** [comment]
Still not entirely happy that I understand this. A very simple example I made seems to be able to find GDI+ exactly the same on 32/64 and gui/non-gui. Can we hold of merging this for a little while? Thanks.

**Comment by fatcerberus** [comment]
If you start cmake-gui from an MSVC command prompt, it finds it.  I suspect this isn't the usual case though--normally the GUI will be launched from the start menu, in which case it fails.

**Comment by fatcerberus** [comment]
Basically what the patch does is get the WinSDK path from the registry and then adds it to the list of locations to search for gdiplus.h.  It's not that complicated, but CMake's ugly custom scripting language makes it look like it is though. :-/

**Comment by peterhull90** [comment]
OK, I see it now. It sort of makes sense - the VS command prompt sets the
SDK location as an environment variable and I assume cmake-gui picks it up
from there. It's annoying because, as far as I can see, GDI+ is not an
optional part of the SDK so it's safe to assume on Windows that it's there
anyway...

**Comment by fatcerberus** [comment]
Hm, in that case maybe I'll revisit the patch and see if there's a way to rework the compile test so we don't have to search for gdiplus.h at all.

Another thing that's weird to me is the casing check for GdiPlus.h - Windows is case insensitive so it shouldn't matter what the casing of the filename is.

**Comment by peterhull90** [comment]
I was forgetting about MinGW. I've not used it for years but it may be that GDI+ support is organised differently. And, MinGW allows cross-compiling from Linux which maybe explains the origin of the case check - see the comment for 10f07722c29a16145004459943e2a48267249e34

**Comment by fatcerberus** [comment]
That makes sense, although where is the header ever named GdiPlus.h?  The one in my Windows SDK is lowercase, like that commit claims MinGW's is.

Maybe the PascalCase is from older WinSDK versions?  In any case MSVC doesn't care about case (IIRC) so it should be safe to just use lowercase always.  I don't know, the whole setup is baffling.

**Comment by peterhull90** [comment]
> Maybe the PascalCase is from older WinSDK versions? 

It seems you are Correct!
~~~
C:\Program Files (x86)>dir gdiplus.h /s /b
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include\GdiPlus.h
C:\Program Files (x86)\Windows Kits\8.1\Include\um\gdiplus.h
~~~

>  I don't know, the whole setup is baffling.

Agreed. I think maybe just go ahead with your patch, it's not worth fretting about.

**Comment by SiegeLord** [comment]
I think I made it check for both versions for mingw's sake.

**Comment by peterhull90** [comment]
Since it's in the DirectX script and the GDI+ script, would it be sensible to separate out the 'locate SDK' function into it's own `.cmake` package and use it to conditionally find the SDK location if it's not already available via environment variables?

**Comment by fatcerberus** [comment]
Hm, the patch got merged before I had a chance to look into that.  Something to look at in the future, I guess.

**Comment by SiegeLord** [comment]
Oh, whoops... didn't know it was unfinished.

**Comment by fatcerberus** [comment]
No problem, the patch is fully-working, it just could have used some cleanup.
