### ISSUE TITLE
al_wait_for_event_timed can block for a long time despite 0 timeout

### ISSUE THREAD

**Issue by aldonunez** [liballeg/allegro5#593]
Once in a while a call to `al_wait_for_event_timed` or `al_wait_for_event_until` with zero timeout will block. With a zero timeout, the call should return immediately.

I tracked down the problem to `_al_cond_timedwait` in src/win/wxthread.c and the following lines:
```
   now = timeGetTime();
   rel_msecs = win_timeout->abstime - now;
```

Once in a while, this call to `timeGetTime` will return a time after the one that was used to set up the timeout (`al_init_timeout`). This leads to the subtraction returning the equivalent of a negative number in signed arithmetic. Because unsigned arithmetic is used, we get a very large positive number.

Can I suggest that these lines be added?
```
   if (rel_msecs > INT_MAX/2)
      rel_msecs = 0;
```

I understand that this means we won't be able to wait around 50 days anymore if we wanted. But I think that this is a fair trade-off.

**Comment by trentg** [comment]
Nice find. I think

  if (now > win_timeout->abstime)

Would work best. Thanks.

**Comment by fatcerberus** [comment]
Wow, awesome catch.  I could never figure out why this was needed:
https://github.com/fatcerberus/minisphere/blob/master/src/minisphere/screen.c#L300-L302

```c
			time_left = obj->next_frame_time - al_get_time();
			if (!obj->avoid_sleep && time_left > 0.001)  // engine may stall with < 1ms timeout
				al_wait_for_event_timed(g_events, NULL, time_left);
```

Now I know!  I just never reported it because I assumed it was a bug/limitation in the OS wait routines...

**Comment by aldonunez** [comment]
I thought about using `now > win_timeout->abstime` at first, too. But, I don't think it handles the case where `win_timeout->abstime` wraps around from your start time. In that case, the first values for `now` would be greater than `win_timeout->abstime`, yet their difference would be positive.

**Comment by trentg** [comment]
I think the start time is always 0 is it not? So the only time that would happen (if at all) is if you set a huge timeout... correct me if I'm wrong.

**Comment by fatcerberus** [comment]
timeGetTime() wraps around every 50 days or so, so if you have a long-running game (or server) you could end up wrapping around.  AppVerifier actually has a mode to test this by causing the start time to be some huge value instead of zero.

**Comment by aldonunez** [comment]
`al_init_timeout` calls timeGetTime to get the start time:

```
   wt->abstime = timeGetTime() + (DWORD)(seconds * 1000.0);
```

So, the possibility of the end time wrapping around is definitely real.

**Comment by trentg** [comment]
OK, here's some ideas... but maybe your solution is better.

If you're setting the timeout to 0 and timeGetTime returns a greater number, wouldn't it be within a few milliseconds of wrapping? So you could check if the time has just wrapped pretty easily I think, unless you've created the timeout many days ago. Just food for thought but it might be more complex than necessary.

**Comment by trentg** [comment]
Probably your solution is the best because it's the simplest, and checking for wrap isn't foolproof (hey, someone could create a timeout 25 days ago.)

**Comment by elias-pschernig** [comment]
This is the only fix that should be applied:

if (rel_msecs > INT_MAX)
      rel_msecs = 0;

There is no need for a /2 as we can hold values up to UINT_MAX which is INT_MAX * 2 + 1. The only problem is that abstime somehow can be smaller than now.

Wrap-around is already handled. Look at this example:

now = 4294967286
abstime = 10 (it wrapped around)
rel = abstime - now = 20

(Also the case where a wrap-around occurs but abstime is smaller than now will be handled.)

Of course, the wait time can never be more than INT_MAX. So to be 100% safe we could check for that and make sure no wait is longer than 20 days.

**Comment by aldonunez** [comment]
My mistake. I meant to say **U**INT_MAX/2, forgetting that it's the same thing as INT_MAX.

**Comment by aldonunez** [comment]
Is there some pattern I should use for platform-specific information in the middle of the general API? Or, should I come up with my own?

**Comment by aldonunez** [comment]
Is there some pattern I should use for platform-specific information in the middle of the general API? Or, should I come up with my own?

**Comment by aldonunez** [comment]
Is there some pattern I should use for platform-specific information in the middle of the general API? Or, should I come up with my own?

**Comment by aldonunez** [comment]
Is there some pattern I should use for platform-specific information in the middle of the general API? Or, should I come up with my own?

**Comment by trentg** [comment]
I would make it platform agnostic, ie. "timeouts are limited to about INT_MAX milliseconds on some platforms, therefore it's best to keep them under this limit to make your game work across all platforms."
