### ISSUE TITLE
Cannot build video addon with ffmpeg 1:3.0-1

### ISSUE THREAD

**Issue by rcorre** [liballeg/allegro5#595]
```
ffmpeg.c:919:18: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘get_buffer’
          codecCtx->get_buffer = our_get_buffer;
                  ^
ffmpeg.c:920:18: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘release_buffer’
          codecCtx->release_buffer = our_release_buffer;
```

`get_buffer` is replaced with `get_buffer2` which just takes an extra `flags` argument.
`release_buffer` is gone, apparently replaced with some reference-counting API?

Related #557.

This is libavcodec major version 57 (56 still has get/release_buffer but they are deprecated).

**Comment by SiegeLord** [comment]
FFmpeg backend is being temporarily removed in #603. When it is re-added, hopefully it won't have these bugs.
