### ISSUE TITLE
`al_hold_bitmap_drawing()` doesn't honor transforms

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#610]
Like the title says, calling `al_hold_bitmap_drawing(true)` while a non-identity transform is active causes the transform to not be honored for the duration of the hold.

**Comment by fatcerberus** [comment]
Following up a bit on this, it appears that transformations are honored for some operations, but not for others.  I can say with absolute certainty that `al_draw_vertex_buffer()` is affected by the bug, and probably `al_draw_prim()` as well.  `al_draw_bitmap()` and friends are *not* affected.

**Comment by trentg** [comment]
> Following up a bit on this, it appears that transformations are honored
> for some operations, but not for others.  I can say with absolute
> certainty that `al_draw_vertex_buffer()` is affected by the bug, and
> probably `al_draw_prim()` as well.  `al_draw_bitmap()` and friends are
> *not* affected.

I would have never expected al_hold_bitmap_drawing to work with anything
but the bitmap drawing functions, nor is it needed with low level
primitive drawing. In that case you batch all your triangles together and
call the function once. That's exactly how hold_bitmap_drawing works
itself.

**Comment by SiegeLord** [comment]
As Trent said, it is called `al_hold_*bitmap*_drawing`, so only `al_draw_bitmap` stuff is actually affected by it. It's not that the transformations don't get baked in when using the primitives addon, it's that those functions aren't batched at all.

**Comment by fatcerberus** [comment]
No, I knew it only batches bitmap calls.  It's just that if you happen to draw a primitive other than a bitmap in the middle of a bitmap hold, it doesn't get transformed.  Don't know if that should be considered a bug or not.

**Comment by elias-pschernig** [comment]
It would require changing the documentation, right now it is a user mistake: http://liballeg.org/a5docs/trunk/graphics.html#al_hold_bitmap_drawing
>  While deferred bitmap drawing is enabled, the **only** functions that can be used are the bitmap drawing functions and font drawing functions. Changing the state such as the blending modes will result in undefined behaviour.

**Comment by fatcerberus** [comment]
Hm, that could maybe be clarified a bit.  Right now that paragraph implies it's not safe to call ANY Allegro functions, which probably isn't true.  Maybe change it to say "the only graphics functions that can be used..."

That's probably why I missed that bit by the way--it comes off as hyperbolic so I guess I tuned it out.  So thanks for pointing it out. :smiley:

**Comment by fatcerberus** [comment]
I guess I'll close this--it falls under undefined behavior and is thus not a bug.
