### ISSUE TITLE
File-based audio stream can't be restarted after it ends

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#611]
It is impossible to play an audio stream loaded by `al_load_audio_stream*()` again after it has ended, not even if you seek to the beginning.  The only option is to reload it.  This has forced me to implement a system of reloading sounds after they stop, which causes stutters in my engine.

It seems like the underlying cause is that the stream-feed thread terminates once the file is exhausted and is never restarted.

**Comment by SiegeLord** [comment]
Note that the stream is paused after it reaches the end, so in addition to seeking to the beginning, you'll need to set it to play as well.

**Comment by fatcerberus** [comment]
That doesn't bother me, as long as I can restart the stream without having to reload it I'm happy. :)
