### ISSUE TITLE
OSX joystick patch

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#614]
See https://www.allegro.cc/forums/thread/616193

**Comment by peterhull90** [comment]
How does this relate to #579, does it help?

**Comment by NewCreature** [comment]
It doesn't relate to that issue. This patch is strictly to make enumerating connected joysticks more robust. The current implementation assumes each HID device is one controller/joystick. The patch fixes this by interpreting each collection reported by the device as a separate controller/joystick (this is part of the USB HID spec).

**Comment by peterhull90** [comment]
I've applied your patch (from a.cc) to a branch in my fork of Allegro, and I'll put in a pull request, unless you want to do it. There are a couple of things which I was going to fix:
* `elements` needs releasing in `device_count_joysticks` (memory leak)
* The [docs](https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFStringRef/index.html#//apple_ref/c/func/CFStringGetCStringPtr) for `CFStringGetCStringPtr` in `get_element_name` warn that it could return NULL at any time. Sounds ominous... I assume it's not currently a problem in this code but it would be as well to fix it.

**Comment by NewCreature** [comment]
Yeah, I missed that `CFRelease()`.

`get_element_name()` doesn't do anything except return `default_name` on any devices I've ever used. I don't think it will ever get to that `CFStringGetCStringPtr()` call.

I started working on another patch to get the name and button/stick/axis names from the HID data. I already have the device name working, but I want to see if I can retrieve the other information as well. It should be possible and it would make joystick support on par with the other supported platforms.

**Comment by NewCreature** [comment]
I put up a new version of the patch in the thread linked above. I went ahead and fixed the two issues you mentioned. I also added support for getting the device name instead of just calling it "Joystick" and I made more appropriate default names for the various types of elements.

**Comment by peterhull90** [comment]
OK I have put this in as a pull request #625. Thanks!

**Comment by goobliata** [comment]
Looks like this was closed, reopen if I'm mistaken.
