### ISSUE TITLE
al_hold_bitmap_drawing() high CPU usage when drawing many bitmaps

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#617]
In minisphere I use `al_hold_btimap_drawing()` combined with a character atlas to draw text.  I recently noticed that my text rendering performance was dismal and decided to profile it.  The profiler indicates most of my time was being spent on:

```c
al_hold_bitmap_drawing(false);
```

Going down the rabbit hole a bit further reveals that an inordinate amount of time is being spent in `_al_opengl_set_blender()` (15-20% of my execution time is spent there).  Is this something that Allegro can fix?  Does `al_hold_bitmap_drawing()` need optimization, or am I doing something wrong?

**Comment by fatcerberus** [comment]
I decided to look at Allegro's source code.  It seems like Allegro is setting the blend state for every `al_draw_bitmap_*()` call, regardless of whether bitmap drawing is held or not.  This seems like it could be optimized by moving the `_al_opengl_set_blender()` call into `flush_vertex_cache()`.  I'll experiment with that change and see if it helps.

**Comment by fatcerberus** [comment]
Okay, so the change mentioned above makes a noticable improvement.  There's still a bottleneck due to having populate the VBO on each flush, though.  I guess there's nothing to be done for that, but I'll open a pull request for the `_al_opengl_set_blender` change since it does help performance.

**Comment by goobliata** [comment]
Wasn't this fixed, or at least mostly since the blend state was reduced?

**Comment by fatcerberus** [comment]
Yes, I'll close the bug.
