### ISSUE TITLE
test_convert fails with --no-display flag

### ISSUE THREAD

**Issue by tobihan** [liballeg/allegro5#626]
Hi,

when building the Debian package for Allegro 5.2, the test suite is run with the flag --no-display. In this case the test test_convert.ini fails with the error:

test_driver:.../src/drawing.c:29: al_clear_to_color: Assertion `target' failed.

Could you please have a look?

**Comment by SiegeLord** [comment]
`test_convert.ini` only works with a display. I suggest removing it in the `rules` file (that's what I did for the Ubuntu packages).

**Comment by tobihan** [comment]
Then ouldn't it be nicer if the flag --no-display would disable these tests? It seems that's the purpose of this flag.

**Comment by SiegeLord** [comment]
Yeah, that's a good idea. I can annotate the tests which require a display and then this would work automatically.
