### ISSUE TITLE
test_compressed fails with --no-display flag

### ISSUE THREAD

**Issue by tobihan** [liballeg/allegro5#627]
Hi,

when building the Debian package for Allegro 5.2, the test suite is run with the flag --no-display. In this case the test test_compressed.ini fails with the error:

test_driver: failed to load ../examples/data/mysha_dxt1.dds
FAIL test loading dxt1 [sw] - hash=c8616bd1
test_driver: failed to load ../examples/data/mysha_dxt3.dds
FAIL test loading dxt3 [sw] - hash=c8616bd1
test_driver: failed to load ../examples/data/mysha_dxt5.dds
FAIL test loading dxt5 [sw] - hash=c8616bd1
test_driver: failed to load ../examples/data/mysha_dxt1.dds
FAIL test dest rw dxt1 [sw] - hash=188e1cb1
test_driver: failed to load ../examples/data/mysha_dxt3.dds
FAIL test dest rw dxt3 [sw] - hash=188e1cb1
test_driver: failed to load ../examples/data/mysha_dxt5.dds
FAIL test dest rw dxt5 [sw] - hash=188e1cb1
test_driver: failed to load ../examples/data/mysha_dxt1.dds
FAIL test dest wo dxt1 [sw] - hash=5126ebd1
test_driver: failed to load ../examples/data/mysha_dxt3.dds
FAIL test dest wo dxt3 [sw] - hash=5126ebd1
test_driver: failed to load ../examples/data/mysha_dxt5.dds
FAIL test dest wo dxt5 [sw] - hash=5126ebd1
test_driver: failed to load ../examples/data/mysha_dxt1.dds
FAIL test src dxt1 [sw] - hash=eb165abb
test_driver: failed to load ../examples/data/mysha_dxt3.dds
FAIL test src dxt3 [sw] - hash=eb165abb
test_driver: failed to load ../examples/data/mysha_dxt5.dds
FAIL test src dxt5 [sw] - hash=eb165abb
test_driver: failed to load ../examples/data/mysha_dxt1.dds
FAIL test dest sub dxt1 [sw] - hash=5f81ebd1
test_driver: failed to load ../examples/data/mysha_dxt3.dds
FAIL test dest sub dxt3 [sw] - hash=5f81ebd1
test_driver: failed to load ../examples/data/mysha_dxt5.dds
FAIL test dest sub dxt5 [sw] - hash=5f81ebd1
test_driver: failed to load ../examples/data/mysha_dxt1.dds
FAIL test convert from dxt1 [sw] - hash=6aa8d126
test_driver: failed to load ../examples/data/mysha_dxt3.dds
FAIL test convert from dxt3 [sw] - hash=6aa8d126
test_driver: failed to load ../examples/data/mysha_dxt5.dds
FAIL test convert from dxt5 [sw] - hash=6aa8d126
OK   test convert to dxt1 [sw] - by signature
OK   test convert to dxt3 [sw] - by signature
OK   test convert to dxt5 [sw] - by signature

total tests:  21
passed tests: 3
failed tests: 18

The files that cannot be loaded are present at the stated locations. Could you please have a look?

**Comment by SiegeLord** [comment]
`test_compressed.ini` is another test that only works with a display created.
