### ISSUE TITLE
d3dx9 lib missing for ex_d3d with msys2 + monolith build

### ISSUE THREAD

**Issue by White-Unicorn** [liballeg/allegro5#629]
the dxd3d9 lib is not being included for ex_d3d and a monolith build due to the example passed in libs being discarded vie overwriting libs if want_monolith is on.

https://github.com/liballeg/allegro5/blob/master/examples/Helper.cmake#L50

    # Monolith contains all other libraries which were enabled.
    if(WANT_MONOLITH)
        set(libs ${ALLEGRO_MONOLITH_LINK_WITH})
    endif()

Please note specifically [L28](https://github.com/liballeg/allegro5/blob/master/examples/Helper.cmake#L28) and [L41](https://github.com/liballeg/allegro5/blob/master/examples/Helper.cmake#L41) where `libs` is set previous with passed in [D3DX9_LIBRARY](https://github.com/liballeg/allegro5/blob/master/examples/CMakeLists.txt#L190).

I am unsure how to 'fix' this however.

**Comment by krystalgamer** [comment]
Same problem here.
Will leave a comment in case someone answers this.

**Comment by SiegeLord** [comment]
Thanks for investigating this! Indeed, this actually affected all examples with non-Allegro dependencies, but those other examples are not typically enabled.
