### ISSUE TITLE
Intermittent crash with al_destroy_display()

### ISSUE THREAD

**Issue by MarkOates** [liballeg/allegro5#630]
I've been doing some testing on my code which involves quick setup and teardown of Allegro on each test.  Intermittently, the first test crashes on teardown, and I isolated it to `al_destroy_display()`.  It may be a caused by a display being destroyed too quickly after it has been created.

It's an intermittent problem that happens about 1 in 6 times.  I haven't tested this on other devices, I'm on OSX.

You can see more detailed error messages (from boost test) here: https://github.com/MarkOates/allegro_flare/issues/59

**Comment by fatcerberus** [comment]
Definitely sounds like a race condition of some sort.  I know there have been similar issues in the past, for example calling `al_destroy_audio_stream()` too quickly after creating it used to cause a deadlock.

**Comment by MarkOates** [comment]
I "solved" the problem by not calling al_destroy_bitmap() before al_uninstall_system(). Not sure if that leaves a dangling display or not.

I also tried adding a sleep(1) before teardown, but the problem would still occur occasionally.

**Comment by SiegeLord** [comment]
Is this something that's easy to reproduce? Can I just stick a `al_destroy_display` before `al_uninstall_system` and have it happen from time to time?

Also, what OSX version is this? I notice many graphics related issues are very sensitive to the OSX version, surprisingly...

**Comment by MarkOates** [comment]
I'm on OS X El Capitan 10.11.5.

[Here](https://github.com/MarkOates/allegro_flare/blob/master/tests/picking_buffer_test.cpp#L28-L44) is the working version in which the `al_destroy_display` has been removed.  Adding a `al_destroy_display(display)` above line 42 will cause the problem to occur when running the tests (which setup/teardown that `SetupWithDisplay` fixture when running each test).

In theory, one could simply...
```cpp
while (true)
{
    SetupWithDisplay setup = SetupWithDisplay();
}
```
... with that class and it would cause a crash.

Another possibility that I just considered is that the boost tests might be being run in parallel, causing issues.

**Comment by MarkOates** [comment]
I'm not sure what may have been causing this issue when I opened it, but, I've been running Google Test tests for a couple with many many test runs over a couple years, each that create displays and destroy them within a short period of time and have not had any issues, so I'm going to close this.

This lack of being able to reproduce the issue may be due to an improvement in my testing setup/teardown, which you can see [here](https://github.com/allegroflare/allegro_flare/blob/master/src/AllegroFlare/Testing/WithAllegroRenderingFixture.cpp#L55-L113) if you're bored.
