### ISSUE TITLE
Native PNG Loading Broken on iOS

### ISSUE THREAD

**Issue by troutsneeze** [liballeg/allegro5#631]
Some load almost right or right, but most load as garbage or with some garbage in them or even all black.

**Comment by goobliata** [comment]
I found out that this affects games that were built previously as well, so basically any game using native png loading on the App Store will have to be updated. I think Apple changed something in iOS 9 (9.3.1 specifically, not sure of others.)

**Comment by goobliata** [comment]
If I resize the images to be multiple of 4 it works. However reading pixels in "mul4" width from the source instead of "w" doesn't work, the image is still corrupt (after making the buffer bigger to account for the extra reads.) However if I read less (282 instead of 285 for a 285 pixel wide image), the image at least isn't skewed... but there is some problems with it. Also small images are sometimes completely corrupted, which makes me think it might be multiples of 16 instead of 4...

All of this makes me think it's an OpenGL bug in Allegro, but libpng works fine so I'd assume it's an Apple bug. I might use one of my "free" support cases to ask/report about it.

**Comment by fatcerberus** [comment]
Maybe the image needs to be in power-of-two sizes, and not any specific multiple?

**Comment by goobliata** [comment]
Doesn't seem to be powers of two, at least 288x160 seems to work which is a multiple of 16 but not a power of 2.

**Comment by goobliata** [comment]
Still shouldn't have to be multiple of anything, and the code worked before iOS 9.3, so seems like an Apple bug.

**Comment by beoran** [comment]
I'd say in the future we should ditch native loading altogether,
better rely on proven in use libraries. If libpng is too muh of a
dependency then we can incorporate a tiny png decoder in Allegro
directly.

Kind Regards, B.

**Comment by goobliata** [comment]
I used one of my Apple tech support requests for this. They told me it's a bug and referred me to report it as a bug in Apple software and gave me my support request back. Have to wait to hear back from the next team.

**Comment by goobliata** [comment]
Apple told me it was a duplicate after I reported it. They gave me a reference number but there's no way to look that bug up, so I don't know if or when they will fix it. I guess I'll try it on the latest iOS 9 sometime when I have a minute, but I don't have an iOS 10 device.

**Comment by seibelj** [comment]
Still broken on iOS 10.3.1. My plan now is to ship all images as BMP inside of a zip and use PhysicsFS to load them

**Comment by goobliata** [comment]
If you want to compile and use libpng, that works. It's what I've been doing.

**Comment by seibelj** [comment]
Does the image addon automatically switch to using libpng if statically linked? Do I need to create my own bitmap loader?

**Comment by goobliata** [comment]
It depends how you compiled Allegro. If you use cmake then you just add `-DWANT_NATIVE_IMAGE_LOADER=off` and make sure it finds libpng. If you use the project in misc/Allegro5_iOS then it's already set up to use libpng. One Allegro is built to use libpng there is no difference between using it with the native image loader, you just use al_load_bitmap("x.png");

**Comment by goobliata** [comment]
The issue on Apple's bug tracker is still open I guess. Obviously it's not a priority and probably will never be fixed on iOS 9 which likely may not get anymore updates. So best thing to do is move to libpng on iOS, maybe even remove (comment out) the native loader.

**Comment by seibelj** [comment]
Thanks for your advice, I'm going to compile libpng into it, safer to go that route anyway

**Comment by troutsneeze** [comment]
Closing as probably outdated...

**Comment by troutsneeze** [comment]
Stale

**Comment by troutsneeze** [comment]
Fucking close...
