### ISSUE TITLE
al_get_standard_path crashes on archlinux

### ISSUE THREAD

**Issue by lilmike** [liballeg/allegro5#638]
Hi,
I have a game that runs under archlinux, and once the arch package for allegro was updated to 5.2.0.0, my game now crashes with a segmentation fault. gdb claims it is on the line that runs al_load_sample(((string)(al_path_cstr(al_get_standard_path(), '/'))+file).c_str()); (where file is the file I'm trying to load). It works just fine on windows, so I'm not sure if this is an allegro bug or an archlinux bug.
The code that my game is using can be found here, https://github.com/2mb-solutions/horseshoes and https://github.com/2mb-solutions/game-kit, and the PKGBUILD that my game uses on the AUR is https://aur.archlinux.org/packages/horseshoes-git
Thanks,
-Michael.
Edit: al_get_standard_path is crashing it, not al_get_path_cstr

**Comment by goobliata** [comment]
Check that your game is not being built with old headers. al_init will fail in that case (check the return value.)

**Comment by lilmike** [comment]
Hi,

I've checked, as best I can, that the game isn't being built with old 
headers. The headers in /usr/include/allegro5 were updated on may 9, 
which, from what I can remember, was when this update was applied. Is 
there a file with the version of allegro the headers are for?

I haven't checked the return value, in fact I just send it straight 
through al_path_cstr, but it's segfaulting in al_get_standard_path 
itself, which, like you, made me think it was oudated headers.

-Michael.

**Comment by lilmike** [comment]
Ok, I just checked allegro5/bass.h, and it is indeed the 5.2.0 headers.

-Michael.

**Comment by BorisCarvajal** [comment]
Check that libvorbis is installed.

**Comment by lilmike** [comment]
Yep, it's definitely al_get_standard_path crashing. And the weird thing is, it worked fine when the package on archlinux was the latest 5.0 version, but now that it's updated to 5.2.0, it's not. I have this same issue on another's computer as well, so either it's a regression in allegro itself, or the archlinux package is broken somehow. I'm just trying to figure out which, as if its the archlinux package I'll have to open a bug report with them.
-Michael.

**Comment by BorisCarvajal** [comment]
I'm using Arch too and al_get_standard_path is working fine (tested with allegro ex_get_path example).

**Comment by lilmike** [comment]
OK, so either I did something in my code that I don't remember, or something else broken on my system. Thanks for letting me know that it's not arch.

**Comment by BorisCarvajal** [comment]
I just compiled your game but I can only see a black window

**Comment by lilmike** [comment]
Yeah currently that's all you'll see, there should be some sounds, but right now it's only really working for blind people. As that's his target audience. It has a screen reader function that can read out the menus, etc., but currently there is no text menu.
Michael.

**Comment by lilmike** [comment]
So it appears on my system that al_init is throwing an error, which of 
course would cause al_get_standard_path to behave incorrectly. I forgot 
to do one of my error checking functions haha. Anyway, I'm not sure what 
else would cause al_init to throw an error except for the headers being 
mismatched, which from all I can tell they aren't, any clues?

Also, are you using the arch package for allegro? Or your own compiled one.

-Michael.

**Comment by BorisCarvajal** [comment]
Used the official one then my own, both behave the same way.

**Comment by goobliata** [comment]
I've very unlikely for al_init to fail unless your headers and libraries don't match. Check all your paths and make sure you don't have any other libs/headers.

**Comment by goobliata** [comment]
@lilmike did you figure this out?

**Comment by lilmike** [comment]
Oops, forgot about this issue. But yes, for whatever reason it works now.
-Michael.
