### ISSUE TITLE
Allegro _al_unregister_destructor performance

### ISSUE THREAD

**Issue by Rseding91** [liballeg/allegro5#640]
I was running some performance analysis on our game (www.Factorio.com) and found that during map unloading it was spending a large percentage of the time (90% of 5 seconds total time) in calls to _al_unregister_destructor().

We solved it by 1: making less subbitmaps so thus making less calls to destroy the subbitmaps and 2: improving the implementation of the function.

I was wondering if you'd be interested in looking at the changes and possibly integrating them if there aren't any issues with how I changed it to work.

The changes are 3:

1. Store the size of the dtors list one before iterating so it doesn't keep getting called during iteration.
2. Store a pointer to the first DTOR and increment that in the loop instead of re-dereferencing inside the loop to find the next one.
3. Instead of deleting the found dtor, copy the last dtor to the one-to-delete and then delete the last (avoiding the memmove)

        void _al_unregister_destructor(_AL_DTOR_LIST *dtors, void *object)
        {
           ASSERT(object);

           _al_mutex_lock(&dtors->mutex);
           {
              size_t size = _al_vector_size(&dtors->dtors);
              DTOR *dtor = _al_vector_ref(&dtors->dtors, 0);
              for (unsigned int i = 0; i < size; ++i)
              {
                if (dtor->object == object)
                {
                  // Copy from last and pop last
                  *dtor = *(DTOR*)(_al_vector_ref(&dtors->dtors, size - 1));
                  _al_vector_delete_at(&dtors->dtors, size - 1);
                  ALLEGRO_DEBUG("removed dtor for object %p\n", object);
                  break;
                }
                ++dtor;
              }

              /* We cannot assert that the destructor was found because it might not
               * have been registered if the owner count was non-zero at the time.
               */
           }
           _al_mutex_unlock(&dtors->mutex);
        }

**Comment by goobliata** [comment]
Couple potential issues. The vector is just an array yes but can that be assumed (thus incrementing pointer should work?) And is destructor order unimporant? Perhaps order of destructors needs to be preserved in some cases thus copying the last forward wouldn't work.

**Comment by goobliata** [comment]
This function does seem awfully inefficient, though.

**Comment by elias-pschernig** [comment]
Maybe we can use a linked list instead (thus having no move nor copy at all), and also keep a reference to the list item (and not the object), and so completely get rid of the loop to search the item.

While the above two things should fix the slowness I'm also wondering - do we really need to register a destructor for every single bitmap created by the user? It seems that's not what destructors are meant for, a single destructor which goes through the list of all bitmaps seems like it could do the same job.

**Comment by SiegeLord** [comment]
I looked a bit through the code, and I don't think Allegro is relying on a particular order of destructors. If there's a parent-child dependency (e.g. ttf fonts have page bitmaps) then the code simply doesn't register those destructors.

That said, it'll probably be best to just implement Elias' linked list suggestion. It's relatively easy, and seems the right thing to do.
