### ISSUE TITLE
Close the alleg-main mailing list.

### ISSUE THREAD

**Issue by dleslie** [liballeg/allegro5#646]
In fact, consider closing all of the mailing lists, and even the forums.

Browsing liballeg.org has the appearance of wading into a long-abandoned project. Allegedly active mailing lists have been silent or spam-only for months (spam since about april for Dev, silent since basically 2014 for main), and the confusing/narrow filtering on the forums makes it look like they're on life-support, at best.

If communication mediums are no longer popular then it is best to shut them down, otherwise the project looks like the lights were left on but no one has been around for some time.

**Comment by beoran** [comment]
I actually agree that those unused communication channels should be closed and archived, but I'm not really able to contribute to that right now. Any takers?

**Comment by goobliata** [comment]
The mailing list should not be shut down. Whether it's used much or not doesn't matter, the point is it's the only place we can have discussions that don't fit in bug reports or feature suggestions. In fact I am preparing a post for the mailing list now to discuss a potential optimization.

**Comment by dleslie** [comment]
It not seeing use means that when I show the project to developers I know they look at the list traffic and give the project a miss. Why use Allegro, which appears to have no users, when SDL2 is so popular?

**Comment by kazzmir** [comment]
It would be nice if liballeg.org showed the number of downloads per file,
which gives some hint as to its popularity. Does gna track that?

**Comment by SiegeLord** [comment]
Those numbers are available at http://stats.gna.org/download.gna.org/allegro/

Apparently allegro-5.2.0.zip is downloaded >100 times a day. According to https://www.nuget.org/packages/Allegro/ that binary package gets 20ish downloads a day. Probably paltry numbers compared to some libraries, but I wouldn't say they're super low.

Anyway, that's seems like a silly number to draw attention to. I typically look at the recency of the update/news posts more than anything when I evaluate the health of the project. Additionally, we do have a link to the forums, which are in principle somewhat active.

It doesn't seem like there's a problem here that needs to be solved.
