### ISSUE TITLE
al_stop_timer causes long delay on Windows

### ISSUE THREAD

**Issue by goobliata** [liballeg/allegro5#651]
On Windows al_rest is very imprecise and often rests a minimum of 10 milliseconds even if asked for less. That part is known, but if al_stop_timer is called and the timer thread is the only thread, it causes the thread to join which waits for the al_rest call to finish causing a big delay, thus it can't be used in a game loop.

My suggestion if this is indeed the problem is maybe having an al_pause_timer which doesn't remove the timer from the queue but just doesn't handle the ticks.

**Comment by goobliata** [comment]
It does indeed seem to be the problem. This patch stops timer events but doesn't cause the delay: https://gist.github.com/goobliata/927b4b4cdcf25c3524837fba7c1a0da3

**Comment by SiegeLord** [comment]
Without thinking too much, could we just detach the timer thread instead of joining it?

**Comment by goobliata** [comment]
I have a pull request that keeps the thread alive here: https://github.com/liballeg/allegro5/pull/654

Unfortunately the thread will run until the timer system is shut down, but it's probably better than new confusing API.
