### ISSUE TITLE
Support custom vertex attributes

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#660]
Allegro already has support for custom shader uniforms.  We should also support custom vertex attributes if we don't already.

**Comment by SiegeLord** [comment]
We support it via `al_create_vertex_decl`: http://liballeg.org/a5docs/trunk/primitives.html#allegro_vertex_element

**Comment by fatcerberus** [comment]
Hmm, in my use case I'm trying to support it in script.  So if I had a vertex shader with an integer attribute `myAttr`, I could then do in a game script:
```javascript
var shape = new Shape([
    { x: 100, y: 100, attribs: { "myAttr": 812 } },
], tex, ShapeType.Points);
shape.draw(screen);
```

I don't think I can support arbitrary attributes like this using `al_create_vertex_decl()`, since it requires essentially hardcoding a vertex structure.  Unless I'm just not thinking creatively enough.

**Comment by SiegeLord** [comment]
You could do something like:

```c
int x = 100;
int y = 100;
int my_attr = 812;
void* my_vertices = malloc(num_vertices, vertex_size);
memcpy(my_vertices + 0, &x, sizeof(x));
memcpy(my_vertices + 4, &y, sizeof(y));
memcpy(my_vertices + 8, &my_attr, sizeof(my_attr));
```

You'd have to compute the offsets and overall size dynamically, and it might be a tiny bit tricky, but definitely possible.

**Comment by fatcerberus** [comment]
Thanks for the help, it's good to know this is already possible.  I'll close the issue since there's nothing to do on Allegro's end.
