### ISSUE TITLE
Compile fails on Mac (10.12)

### ISSUE THREAD

**Issue by KraXarN** [liballeg/allegro5#679]
Compile fails on Mac, not sure if just on 10.12, since `QuickTime/QuickTime.h` was removed and needs to be copied from OSX SDK 10.11. After copying that file however, the compile still fails with the following error:
```
/Users/kraxarn/Downloads/allegro/src/macosx/qzmouse.m:165:22: error: assigning
      to 'float' from incompatible type 'id'
      scaling_factor = [[[evt window] contentView] backingScaleFactor];
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
There are also lots of deprecation warnings, but I guess it's this error that makes it fail.
Thanks!

EDIT: Tried removing the 3 lines causing the issue and it now compiles just fine and after some simple testing, everything seems to be working fine. Not sure what that does or if it's just safe to remove it...

**Comment by goobliata** [comment]
Not sure but that should possibly be [[evt window] backingScaleFactor] without the contentView.

**Comment by SiegeLord** [comment]
Yes, not sure how that code ever worked... I tried calling it on NSWindow directly, and it seemed to work fine. As for QuickTime, I just removed the include and things seemed to keep compiling, so perhaps it was unnecessary. I've got the fixes in a pull request that I'll just pass through travis before merging: https://github.com/liballeg/allegro5/pull/682

**Comment by SiegeLord** [comment]
I merged that commit. Please grab the latest master and try compiling again.

**Comment by KraXarN** [comment]
Yea, compile works and after some simple testing seems to be working fine as well. I also did find a minor "bug" with the native dialogs. Mac ignores the header flag and when text is set to NULL, it just results in crashing. Really not a bug, but thought I would just let you know.
Thanks for the fix :p
