### ISSUE TITLE
Cannot build audio example

### ISSUE THREAD

**Issue by nobody37** [liballeg/allegro5#681]
These are errors I get when running cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-iphone.cmake -G Xcode     -DIOS_PLATFORM="iphoneos" ..; xcodebuild;

(I want to build all examples/demos on IOS and deploy to phone.)

During cmake (I have the latest vorbis compiled from tarball and deployed to /usr/local/):
-- Found OGG: /usr/local/include  
-- Found VORBIS: /usr/local/include  
-- Performing Test VORBIS_COMPILES
-- Performing Test VORBIS_COMPILES - Failed
WARNING: libvorbis not found or compile test failed, disabling support.

During xcodebuild it fails here:

Ld build/examples/RelWithDebInfo-iphoneos/ex_audio_simple.app/ex_audio_simple normal armv7
    cd /Users/john/Documents/Git/allegro/allegro
    export IPHONEOS_DEPLOYMENT_TARGET=9.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/john/Documents/Git/allegro/allegro/build/examples/RelWithDebInfo-iphoneos -F/Users/john/Documents/Git/allegro/allegro/build/examples/RelWithDebInfo-iphoneos -filelist /Users/john/Documents/Git/allegro/allegro/build/examples/ALLEGRO.build/RelWithDebInfo-iphoneos/ex_audio_simple.build/Objects-normal/armv7/ex_audio_simple.LinkFileList -miphoneos-version-min=9.3 -dead_strip -fembed-bitcode-marker -framework CoreGraphics -framework QuartzCore -framework UIKit -framework Foundation -framework CoreFoundation -framework MobileCoreServices -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro-static.a /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro_main-static.a /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro_audio-static.a /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro_acodec-static.a /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro_dialog-static.a /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro_audio-static.a -framework OpenAL /Users/john/Documents/Git/allegro/allegro/build/lib/RelWithDebInfo/liballegro-static.a -framework OpenGLES -Xlinker -dependency_info -Xlinker /Users/john/Documents/Git/allegro/allegro/build/examples/ALLEGRO.build/RelWithDebInfo-iphoneos/ex_audio_simple.build/Objects-normal/armv7/ex_audio_simple_dependency_info.dat -o /Users/john/Documents/Git/allegro/allegro/build/examples/RelWithDebInfo-iphoneos/ex_audio_simple.app/ex_audio_simple
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
Undefined symbols for architecture armv7:
  "__al_kcm_aqueue_driver", referenced from:
      _do_install_audio in liballegro_audio-static.a(audio.o)
  "__al_load_ogg_vorbis_f", referenced from:
      _al_init_acodec_addon in liballegro_acodec-static.a(acodec.o)
  "__al_load_ogg_vorbis_audio_stream_f", referenced from:
      _al_init_acodec_addon in liballegro_acodec-static.a(acodec.o)
  "__al_load_ogg_vorbis_audio_stream", referenced from:
      _al_init_acodec_addon in liballegro_acodec-static.a(acodec.o)
  "__al_load_ogg_vorbis", referenced from:
      _al_init_acodec_addon in liballegro_acodec-static.a(acodec.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

**Comment by goobliata** [comment]
Looks like you're trying to link macOS libraries with iOS binaries...

**Comment by nobody37** [comment]
Well I still need help with getting IOS setup. I just wanted to run the demos on my phone. Why is cmake trying to build VORBIS on IOS? Why is getting a working example difficult?

**Comment by goobliata** [comment]
CMake is checking if vorbis is available, which it is not so it prints an message. You don't need vorbis unless you intend to use vorbis.

Why is the sky blue? Haha. There are multiple reasons building for iOS is difficult

1) you're building for a different system than the one you're running
2) Apple has iOS locked down so you need Xcode to install anything and before you do it needs to be set up very precisely
etc

My suggestions is you compile the Allegro library for iOS using the included iOS Xcode project, then set up a new project for an example that doesn't need any dependencies you don't have. Setting up a new project is not very difficult but it's not a cakewalk either, you'll need to mess around for a while and figure it out.

If you're trying to use the command line exclusively, you won't be able to for iOS. You need to use Xcode.

**Comment by nobody37** [comment]
I got the Xcode project you mentioned to compile, but it outputs a library not an app. So if I understand in order to get a simple "Hello world" I need to write a separate iPhone project in Xcode and import the library?

Is there anything different I need to do in accessing the library versus how I would for OSX?

**Comment by goobliata** [comment]
Yes, first paragraph you said is correct. In differences between iOS and macOS there are a couple (maybe more than I can think of):

- your game will always be fullscreen. you can use the ALLEGRO_FULLSCREEN_WINDOW flag to get a display that is the full size
- you don't have access to keyboard or gamepads
- you use TOUCH_INPUT events instead of MOUSE events. They're similar but a little bit different.

That's all I can think of right now. Most things are the same.

**Comment by nobody37** [comment]
Can you call native functions for gamepads from IOS? (In this case I want to run a NIMBUS Gamepad that's an MFI Bluetooth Gamepad) 

So I've got the Xcode project compiled, I copied my libraries like so...
cp -a ~/Library/Developer/Xcode/DerivedData/Allegro5_iOS-cwetgrpftzszxugtippjzfxnyeia/* ~/Documents/Library/Allegro/

(I did that so I could find them in Finder easily)
Then in Xcode on a new project (IOS Game) I added 
~/Documents/Library/Allegro/Build/Products/Debug-iphoneos/
to the Library Search Paths and added libAllegro5_iOS.a to the Linked Libraries and Frameworks, and it compiles.

I tried al_init(); from my main.m in the new project but of course it says not found. Am I missing a header file of some sort, or are there additional steps I need to make it see the library properly?

**Comment by goobliata** [comment]
You can call native iOS Objective-C functions.

To use anything in Allegro 5 you need to #include <allegro5/allegro.h>.

In addition to that include any addons you use. There is also allegro5/allegro_iphone.h that I believe you need to call Objective C.
