### ISSUE TITLE
IOS problems with Pixel Formats

### ISSUE THREAD

**Issue by nobody37** [liballeg/allegro5#685]
This is on iOS (Allegro 5, testing on IOS 9.3, iPhone5s)
After al_init() in my program I call al_set_new_display_flags(ALLEGRO_FULLSCREEN_WINDOW); That runs fine, al_get_monitor_info(0, &info); runs fine and gets me the screen width/height.

If I run al_get_num_display_modes(); I get EXC_BAD_ACCESS. How do I get the pixel format and refresh rate of the current (only?) displayed mode?

I'm porting an app called MEKA that was written in Allegro 5 for OSX/Win32 to IOS. The existing code tries to lock bitmaps and it's giving me errors.

void    VDP_Mode4_DrawTile(ALLEGRO_BITMAP *dst, ALLEGRO_LOCKED_REGION* dst_region, const u8 *pixels, const u32 *palette_host, int x, int y, int flip)

When it gets into the function the ALLEGRO_LOCKED_REGION dst_region is NULL so it fails here with EXC_BAD_ACCESS:
			u32* dst_data = (u32*)dst_region->data;

locked_region was created like this:
    ALLEGRO_LOCKED_REGION* locked_region = al_lock_bitmap(app->box->gfx_buffer, ALLEGRO_PIXEL_FORMAT_ABGR_8888_LE , ALLEGRO_LOCK_READWRITE);

The bitmap (app->box->gfx_buffer) is created like this (and is a valid image):
	al_set_new_bitmap_flags(ALLEGRO_VIDEO_BITMAP | ALLEGRO_NO_PRESERVE_TEXTURE);
	box->gfx_buffer = al_create_bitmap(box->frame.size.x+1, box->frame.size.y+1);

Afaik from debugging, there are no other locks on bitmaps at the time.
Does ALLEGRO_VIDEO_BITMAP or ALLEGRO_NO_PRESERVE_TEXTURE cause issues on IOS with not being able to lock an image?

**Comment by goobliata** [comment]
I can't really debug your program with this much information, but I'll answer what I can:

1) you can get the pixel format of the display with al_get_bitmap_format(al_get_backbuffer(display))

2) There's no issues using ALLEGRO_VIDEO_BITMAP or ALLEGRO_NO_PRESERVE_TEXTURE on iOS.

**Comment by nobody37** [comment]
That narrows it done some thank you, are there any conditions under which an al_lock_bitmap would fail if you're giving it a valid bitmap?

**Comment by fatcerberus** [comment]
For video bitmaps, I assume the only reason locking would fail is if there wasn't enough free RAM to allocate a buffer for the pixels.

Locking a memory bitmap should never fail since it's basically just retrieving a pointer.

**Comment by goobliata** [comment]
Out of memory, bad pixel format (such as all of the _ANY ones) (the one used above is OK)... I don't know, check the code.

**Comment by nobody37** [comment]
I'm not sure what's causing it, I've checked all the usual suspects. It's something in the code though. Even though when I inspect in Xcode's debugger it shows a pointer rather than NULL for the bitmap, the lock operation is coming back NULL and I get EXC_BAD_ACCESS, so in subsequent functions when it tries to write to the locked region it fails in the Debugger.

Detach from the Debugger and the program works and keeps running, although I suspect there are probably some memory leaks and the like in the background.
