### ISSUE TITLE
Crashes under Windows 7, Allegro calls null pointer

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#689]
I've been trying to debug a crash my users are experiencing under Win7, and I've been able to trace the cause back to Allegro.  I've done some experiments commenting out different bits of code and regardless of where the crash happens, the top two entries in the call stack are always:

```
 	0000000000000000()	Unknown
 	spherun.exe!_al_opengl_set_blender()	Unknown
```

I can't get a source-level listing because I'm using the NuGet build of Allegro (5.2.1.1), but the current instruction at the time of the crash is:

```
00000001400EF066  call        qword ptr [_al_glGenVertexArrays (0140443F50h)]
```

This happens for x86 as well but MSVC doesn't seem to have symbols for that build.

**Comment by goobliata** [comment]
Looks like duplicate of #668.

**Comment by fatcerberus** [comment]
Looks like it, yeah.

According to the forum thread linked in #668 VAO support is required for the programmable pipeline.  My engine is set up to fall back on the fixed pipeline if programmable pipeline fails to init - would it be possible to fail early in this case so I can gracefully degrade rather than crashing?

**Comment by goobliata** [comment]
Tell me about the setup it's crashing on. Operating system, GPU, etc. If it was possible to detect if VAOs were supported or not it would be an easy fix... however I'm not certain how to do that. The thread says OpenGL 3 and on supports them, perhaps that check would do. I'd need to have access to the failing hardware and test it as well as any current working hardware.

**Comment by fatcerberus** [comment]
I'm not sure what the hardware is that the original crash was reported against.  I was only able to reproduce it by setting up a Win7 VM in VirtualBox.  I'll have to find out what the setup involved, ill report back when I do.

Now what's interesting though is that this same
VirtualBox VM runs my engine fine - in Ubuntu.  That would seem to rule out unsupported hardware and rather suggests a driver problem instead?

**Comment by fatcerberus** [comment]
So it turns out the original crash report was actually a null pointer dereference in my engine, the crash I produced under VirtualBox is unrelated and most likely the same root cause as #668.  I'll close this issue.
