### ISSUE TITLE
Python 3 bindings

### ISSUE THREAD

**Issue by gjvnq** [liballeg/allegro5#691]
I was trying to use the allegro5 python bindings on my Arch Linux laptop and I came across two problems:

  * These bindings are not compiled by default.
  * There were a few syntax errors when I used the binding generation scripts.

The [diffs](https://github.com/liballeg/allegro5/files/581816/diffs.txt) are attached.

**Comment by goobliata** [comment]
You'll probably want to keep the bindings off by default. You can enable them by passing -DWANT_PYTHON_WRAPPER=on to CMake. About the other changes, I don't know python but if nobody else comments I'll test them out myself and see.

**Comment by SiegeLord** [comment]
The two argument `str`/`bytes` don't exist in Python 2, so we can't use them. You'll want to use the `encode`/`decode` methods which work on both. Also, would you mind making a pull request with these changes?

**Comment by gjvnq** [comment]
No, I would not mind.

I will try to make the pull request as soon as I can.
