### ISSUE TITLE
liballeg docs and video addon events

### ISSUE THREAD

**Issue by EdgarReynaldo** [liballeg/allegro5#696]
Hello,

I just wanted to note that in the latest version of the online manual, the video addon is mentioned in the index on the left, but not in the main display on the right. See here : http://liballeg.org/a5docs/trunk/ . Is this because the video addon in unstable? Also, none of the ALLEGRO_EVENT_VIDEO video events are listed under the main events page.

**Comment by SiegeLord** [comment]
The first is just an omission. As for the events, they're not there because they're addon events, so they're listed in the addon's documentation section (same goes for the audio addon's events).
