### ISSUE TITLE
Toggle _al_three_finger_flag

### ISSUE THREAD

**Issue by DragonDePlatino** [liballeg/allegro5#697]
I see this marked with `/* TODO: use the config system */` so is there any way this could be implemented?

Here's a realistic scenario: The player opens another window, they cut it with ctrl+alt+del and discover their game was closed and they lost several hours of progress. If we could toggle this with a function for some games (and maybe make it false by default), then it wouldn't be an issue.

**Comment by SiegeLord** [comment]
That should be pretty easy to implement, thanks for pointing it out.

**Comment by SiegeLord** [comment]
It turns out that there were undocumented variables you could set to control this (i.e. you could include the Allegro header and literally set `_al_three_finger_flag` to `false`), but now this uses the config system.

**Comment by DragonDePlatino** [comment]
Thanks for adding this. I tried setting _al_three_finger_flag to false before posting this but it refused to compile. If I might ask, what is the config system?

**Comment by SiegeLord** [comment]
See this bit of the manual: http://liballeg.org/a5docs/trunk/system.html#al_get_system_config

You could, e.g., before you install Allegro have this bit of code:

```c
al_set_config_value(al_get_system_config(), "keyboard", "enable_three_finger_exit", "false");
```
