### ISSUE TITLE
feature request: al_path_ustr() an analogue of al_path_cstr()

### ISSUE THREAD

**Issue by gh0stwizard** [liballeg/allegro5#708]
Hi,
Currently there is only **al_path_cstr**() function exists. As you know and can see an implementation of it below, the **al_path_cstr**() uses private function **path_to_ustr**() to build ALLEGRO_USTR path for the internal usage:

https://github.com/liballeg/allegro5/blob/master/src/path.c#L413

It is unfair that to get a fullpath of ALLEGRO_PATH object as  ALLEGRO_USTR I must use **al_patch_cstr(**) function first and later convert it to ALLEGRO_USTR by calling **al_ustr_new**().
While currently everything is flying around ALLEGRO_USTR it would be good have both version **al_path_cstr**() and **al_path_ustr**(), IMHO.

Thanks!

**Comment by elias-pschernig** [comment]
I agree!

**Comment by fatcerberus** [comment]
Here's a pull that implements this: #709.

**Comment by elias-pschernig** [comment]
Thank you! I'll commit it tonight.
