### ISSUE TITLE
Memory bitmap menu icons  are not shown (GNU/Linux)

### ISSUE THREAD

**Issue by oitofelix** [liballeg/allegro5#711]
Despite the documentation of al_set_menu_item_icon saying:

> If a video bitmap is passed, it will automatically be converted to a memory bitmap, so it is preferrable to pass a memory bitmap.

Unlike video bitmaps, memory bitmaps are not shown in menus.

**Comment by elias-pschernig** [comment]
ex_menu still works with a memory bitmap, so I don't know how to reproduce. Can you post a minimal example (or modified ex_menu) which shows this behavior?

**Comment by elias-pschernig** [comment]
Looking at the code at https://github.com/liballeg/allegro5/blob/master/addons/native_dialog/gtk_menu.c#L130 it uses al_get_pixel to read the bitmap - so memory bitmaps definitely work (and should be much faster as al_get_pixel is a bad idea on video bitmaps). In fact al_get_pixel is a bad idea in general and this should use al_lock_bitmap instead... still, that means it is badly optimized, but I cannot see anything wrong.

**Comment by oitofelix** [comment]
I've tracked down the problem to a more general issue.  The problem is basically that my program was in a state such that effectively both of these lines had been executed:

> al_add_new_bitmap_flag (ALLEGRO_VIDEO_BITMAP);
> al_add_new_bitmap_flag (ALLEGRO_MEMORY_BITMAP);

However, that wasn't obvious, because it was a result of a convoluted execution flow.  It seems Allegro doesn't load bitmaps properly if both flags are set.  Searching the documentation I couldn't find any reference saying whether that is the expected behavior, or declaring it as undefined.  In principle if those flags are mutually exclusive, it would be better if they were just one.  As an user I'd find more helpful if Allegro used a "sane" default (whatever that is) when both flags are set (so programs work as expected), or alternatively (in case that's not possible) an "assert" to notify the user right away.

**PS:**  This [commit](https://github.com/oitofelix/allegro5/commit/bf03e3e28ef1f0837783e2b4411be0ef8f19ca10#diff-8f1bdbd2ebccb4b609f644fade18f73bR108) demonstrates the issue.  By the way, I suggest Allegro developers delete any trailing space of source files before committing.

**Comment by elias-pschernig** [comment]
It does load bitmaps "properly" in that case - the ALLEGRO_VIDEO_BITMAP flag just is very specialized and a normal program would never use it. It basically instructs Allegro to fail (return NULL) on any bitmap creation if the bitmap is not a memory bitmap. So yes, if you use that flag for some strange reason, and you get a memory bitmap (because of any number of reasons, including specifying ALLEGRO_MEMORY_BITMAP), the result is all created bitmaps will be NULL.

**Comment by fatcerberus** [comment]
Hm, maybe that flag could be renamed to `ALLEGRO_VIDEO_BITMAP_ONLY` to make the intent clearer?

**Comment by oitofelix** [comment]
> the ALLEGRO_VIDEO_BITMAP flag just is very specialized and a normal program would never use it.

How so?  I'm considering Allegro's documentation.  It says:

> ALLEGRO_MEMORY_BITMAP: Create a bitmap residing in system memory.
> ALLEGRO_VIDEO_BITMAP: Creates a bitmap that resides in the video card memory.

When **only** ALLEGRO_MEMORY_BITMAP is set, al_load_bitmap returns a memory bitmap.  When **only** ALLEGRO_VIDEO_BITMAP is set, al_load_bitmap returns a video bitmap.  When both are set, Allegro returns NULL.  That's the real behavior, and that's **not** what the documentation says it does.

**Comment by oitofelix** [comment]
To me, that's a bug in the program, not the documentation.  However, fixing either one will solve the issue.

**Comment by elias-pschernig** [comment]
Yes, using ALLEGRO_VIDEO_BITMAP in most cases is a bug - I feel it should have been named differently. An additional warning in the documentation certainly make sense.

We could also detect that special case and then ignore one flag or the other - but that seems like a bad choice to me. It also breaks possibly existing and correct code which relies on the NULL return so is not really an option anyway.

**Comment by oitofelix** [comment]
> Yes, using ALLEGRO_VIDEO_BITMAP in most cases is a bug.

That's not at all clear to me.  Why do you say that?  The documentation has not the slightest indication of such fact.

**Comment by SiegeLord** [comment]
ALLEGRO_VIDEO_BITMAP does have a niche use, but I think the correct fix here is to document that setting both ALLEGRO_MEMORY_BITMAP and ALLEGRO_VIDEO_BITMAP together is nonsensical.

**Comment by oitofelix** [comment]
Could someone explain to me why ALLEGRO_VIDEO_BITMAP is seen as so specialized?  What's its niche?  I'm not arguing, just want to understand, because I might have used it wrong all along.

**Comment by SiegeLord** [comment]
For about 80-90% of use cases, Allegro lets you use memory bitmaps and a video bitmaps interchangeably. Thus, the default behavior is for Allegro to try to make any new bitmap a video bitmap, but fall back to a memory bitmap if something doesn't go right. In general this default state (which is ALLEGRO_CONVERT_BITMAP) lets Allegro change the real bitmap type back and forth as it sees fit.

For example, you could load a bitmap before creating a display. Without a display, there's no choice but to make it a memory bitmap, so Allegro does so. After you create the display, the bitmaps are converted to video bitmaps, and you enjoy the full hardware acceleration etc.

With bitmaps that have the ALLEGRO_VIDEO_BITMAP flag set, you force them to be video bitmaps which increases the chance of various calls returning NULL (e.g. in that create a bitmap before creating a display situation), but you provide guarantees of that this bitmap will use hardware acceleration and will work with the video bitmap-only features (e.g. shaders). Sometimes it's the right thing to do, but it's something you need to do with both eyes open.

**Comment by oitofelix** [comment]
Thanks for explaining.  I started using Allegro 5.2+ only recently.  Allegro 5.0 didn't have ALLEGRO_CONVERT_BITMAP, so I guess this confused me a little bit.  Now I understand what's the real meaning of ALLEGRO_VIDEO_BITMAP.  I think this could use some additional documentation.  It'd be good to have an assert ensuring that both flags (ALLEGRO_MEMORY_BITMAP and ALLEGRO_VIDEO_BITMAP) aren't set at the same time.
