### ISSUE TITLE
NuGet packages don't work with VS2017

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#730]
I've been wanting to beta test the VS 2017 RC but Allegro's NuGet packages don't seem to work with it.  MSVC can't find the binaries, which I assume is because the .lib files are version-specific in the package.  Any chance of the NuGet packages being updated?

**Comment by SiegeLord** [comment]
I probably don't want to install an unreleased version of MSVC, but it's pretty easy to build the packages yourself if you want.

**Comment by fatcerberus** [comment]
That's understandable.  I have no experience with NuGet so I wouldn't know where to start there.  The funny part is that I could probably link against the MSVC 2015 libs directly with no issue, but for NuGet packages it seems the IDE isn't happy unless the .lib files are in the proper folder of the package.

By the way, official release of MSVS 2017 is March 7, so perhaps the next Allegro release (depending on when it lands) could include the 2017 binaries.

**Comment by SiegeLord** [comment]
I'll make a pull request to the package repository soonish, and then it'll just be a matter of installing cmake, nasm and nuget and then running a batch command.

**Comment by SiegeLord** [comment]
And here it is: https://github.com/liballeg/allegro_winpkg/pull/7/files Just follow the instructions in the `README_nuget.txt` and you should be able to build the nuget packages yourself. Since you probably don't have MSVC 2013 and 2015 installed, you'll need to edit some scripts but that should be straightforward.

**Comment by fatcerberus** [comment]
Thanks, I'll check it out tonight.

**Comment by SiegeLord** [comment]
This is now fixed. Package version 5.2.2.1 supports MSVC 2017.

**Comment by fatcerberus** [comment]
After installing 5.2.2.1 in my project in MSVC 2017, I get the following error:
```
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\AllegroDeps.1.5.0.0\build\native\AllegroDeps.targets.
```

I had to manually edit the project file to fix the references, which seems to have fixed it.  MSVC 2017 seems rather glitchy so far, so I doubt this is an Allegro bug.  Just thought I'd mention it anyway.
