### ISSUE TITLE
Gain for sample instances and streams is applied incorrectly.

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#734]
If you do `al_set_sample_instance_gain(spl, 0.5)` you'd expect a sound that is half as loud. The way it's implemented right now, however, results in a sound that is quarter as loud, as the gain multiplier is applied twice. This is due to the pan code being implemented incorrectly, notably if you use the pan value of `ALLEGRO_AUDIO_PAN_NONE` gain will be applied only once.

Unfortunately this behavior was around since around 2008, before 5.0, so it's not clear what should be done about it.

**Comment by beoran** [comment]
I would simply fix it since doing so doesn't really change the API. I also
think that no one has been seriously using that function or the bug would
have been reported much sooner...

Kind Regards, B.

**Comment by goobliata** [comment]
I agree, if it's not the expected behaviour then it's a bug and should be
fixed. I don't think we every INTENDED it like that.

**Comment by SiegeLord** [comment]
Alright, you guys convinced me, we'll revisit this if somebody complains :godmode:.
