### ISSUE TITLE
ALLEGRO_FULLSCREEN_WINDOW issue in Mac OS

### ISSUE THREAD

**Issue by koro-xx** [liballeg/allegro5#740]
_Edit: Apparently my allegro version was 5.1.14 instead of the latest due to a confusion with my local files. I still haven't managed to test it with the latest version but I just saw this issue as fixed in the 5.2 changelog (I don't know how to close or take back this issue report)_

In Mac OS (I only have 10.9 Mavericks to test), after destroying a "FULLSCREEN_WINDOW" display and creating a new windowed display, the whole screen behind the new display window is blank instead of showing the desktop.
The code below in my system produces a full green screen, then after 3 seconds a smaller red window over a white background (where I would expect the background to be my desktop).

```
#include <allegro5/allegro.h>

int main(void)
{
    ALLEGRO_DISPLAY *disp;
    al_init();
    
    al_set_new_display_flags(ALLEGRO_FULLSCREEN_WINDOW);
    disp = al_create_display(800,600);
    al_clear_to_color(al_map_rgb(0,255,0));
    al_flip_display();
    al_rest(3);
    al_destroy_display(disp);
    
    al_set_new_display_flags(ALLEGRO_WINDOWED | ALLEGRO_RESIZABLE);
    disp = al_create_display(800,600);
    al_clear_to_color(al_map_rgb(255,0,0));
    al_flip_display();
    al_rest(3);
    al_destroy_display(disp);
    
    return 0;
}
```

**Comment by goobliata** [comment]
Are you on the latest git version? I'm doing this in my game and it works for me, though I do recall having the problem at one point. It might be because when I switch modes, I shut Allegro down completely and re-init it.

**Comment by fatcerberus** [comment]
It looks like he edited the post - he was indeed using an older version.

**Comment by goobliata** [comment]
OK thanks, I will close this.
