### ISSUE TITLE
Android build fails due to deprecated 'android' command

### ISSUE THREAD

**Issue by kraxarn** [liballeg/allegro5#743]
The new Android SDK deprecates the 'android' command and the SDK manager, moving everything to Android Studio. This makes the final 'make' compile fail with the following error:
```
Scanning dependencies of target jar
[  8%] Generating allegro_activity/AndroidManifest.xml, allegro_activity/build.xml
[  8%] Generating allegro_activity/local.properties
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update project -p . -t android-12"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
make[2]: *** [android/CMakeFiles/jar.dir/build.make:75: android/allegro_activity/local.properties] Error 2
make[1]: *** [CMakeFiles/Makefile2:649: android/CMakeFiles/jar.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

**Comment by goobliata** [comment]
What version of the sdk do you have? I know it's been deprecated but I just recently did a clean install and it works. To get the sdk manager you can use "android sdk" command. But you may be right, maybe they took it a step further (grumble grumble google changes things every 2 days it seems...)

**Comment by KraXarN** [comment]
Downloaded and installed it just now through Android Studio

**Comment by goobliata** [comment]
I guess you're right. The build system will need to be updated to gradle. Until then, maybe try getting an older sdk. Elias said he wanted to update to gradle so maybe he'll do it.

**Comment by KraXarN** [comment]
Now I get this error instead
```
[  8%] Generating ../lib/Allegro5.jar
   [subant] No sub-builds to iterate on
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] android/allegro_activity/src/AllegroActivity-2.java:26: error: class AllegroActivity is public, should be declared in a file named AllegroActivity.java
    [javac] public class AllegroActivity extends Activity
    [javac]        ^
    [javac] android/allegro_activity/src/AllegroActivity.java:26: error: duplicate class: org.liballeg.android.AllegroActivity
    [javac] public class AllegroActivity extends Activity
    [javac]        ^
    [javac] android/allegro_activity/src/AllegroActivity-2.java:108: error: cannot find symbol
    [javac]          display.getRectSize(size);
    [javac]                 ^
    [javac]   symbol:   method getRectSize(Rect)
    [javac]   location: variable display of type Display
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 3 warnings

BUILD FAILED

**Comment by goobliata** [comment]
How are you building? Looks like you're trying to target Android 1.5 while Allegro only supports 2.3 (version 9) and up.

**Comment by KraXarN** [comment]
getRectSize was added in API 13, while Allegro suggests you use API 12. Looks like an issue there

**Comment by elias-pschernig** [comment]
You can always use the pre-compiled binaries for Android as well, just in case you missed those. You can also look at the script to create those binaries to get an idea how it can be done (they are command-line only without any Android Studio).

**Comment by elias-pschernig** [comment]
Oh, I use API 15 for those binaries, so yes, if you need to support older they won't work of course.

**Comment by KraXarN** [comment]
I'll try recompiling for API 19 instead, but if that's the issue, you may want to update the guide :p

**Comment by goobliata** [comment]
The source file checks the Android version so it's not an issue. I build with API 9 and it works fine.

**Comment by goobliata** [comment]
What you need to do is build with the latest SDK but set your minimum target to Android 9.

**Comment by goobliata** [comment]
Here's what I have in my manifest:

	<uses-sdk android:minSdkVersion="9"/>
	<uses-sdk android:targetSdkVersion="23"/>

**Comment by goobliata** [comment]
You can use 25 or 24 or whatever is the latest.

**Comment by KraXarN** [comment]
Compiled fine when setting API to 19, so might want to change that in the guide.

**Comment by goobliata** [comment]
That's something else that should be removed from the guide... it's unnecessary.

**Comment by goobliata** [comment]
Patches are welcome btw...

**Comment by sjfricke** [comment]
I have searched and found no replacement for the `android update project` command.
If you still need to build I suggest reverting to SDK Tools 25.2.5 or earlier as they removed the command in [Build Tool 25.3.0](https://developer.android.com/studio/releases/sdk-tools.html)

You can download them from here and replace the `tools` folder in your ANDROID_SDK_HOME directory
https://dl.google.com/android/repository/tools_r25.2.5-windows.zip
https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip
https://dl.google.com/android/repository/tools_r25.2.5-linux.zip

**Comment by RYPTAR** [comment]
@sjfricke This fixes cocos2d-x issues too, thanks dude!

**Comment by elias-pschernig** [comment]
Should be fixed by commit 55184a.
