### ISSUE TITLE
Bluetooth mouse not detected

### ISSUE THREAD

**Issue by tbass** [liballeg/allegro5#747]
I am restarting gamedev with Allegro5 on a new iMac and use primarily a bluetooth mouse (Logitech MX Master) which is working smoothly in all apps. 
When I start my self written game, I call al_install_mouse()  which fails, as it seems that it can not detect the mouse properly.
Attaching a USB mouse helps, but I do not want to have multiple mice connected to my machine just for development purposes. 
The init order is   

    al_init()
    al_install_keyboard()  

and then   

    al_install_mouse()

, which returns all the time with false, even with the properly (in terms of system usage) BT mouse attached.

The allegro.log returns

> system   I             system.c:257  al_install_system                [   0.00000] Allegro version: 5.2.3 (GIT)
> MacOSX   I            qzmouse.m:236  osx_init_mouse                   [   0.00028] Detected 0 pointing devices
> MacOSX   I            qzmouse.m:271  osx_init_mouse                   [   0.00029] Device effectively has 0 axes and 0

**Comment by tbass** [comment]
Generated a patch for the issue - working at least on my machine. If this patch seems helpful, please review.

<script src="https://gist.github.com/tbass/9bef04cbb63a019489dfa813eceb3102.js"></script>

**Comment by goobliata** [comment]
Thanks for the patch. I took a quick look and it looks OK (for my reference did you change just the top of the big code block, the patch is a little wonky...?) I'll take a look at applying it soon.

**Comment by tbass** [comment]
@goobliata thanks for your feedback. I add here the info I mentioned in the IRC related to the patch:

At first, **kHIDUsage_GD_Mouse** did not detect the bluetooth mouse. Using the **kHIDUsage_GD_Pointer** instead detects it (as it is a "lower level" pointing device (from what I read - can not find it anymore :( ... ))  

To not break the old code, I thought to test on both types, at first the GD_Mouse to keep the standard "as-is". If this does not detect any devices, I will use the fallback of GD_pointer.
To use both searches I introduced a new function **_get_matching_services** to get the iterator

**Also I changed the dictionary used for the search from kIOHIDPrimaryUsageKey and kIOHIDPrimaryUsagePageKey to kIOHIDDeviceUsageKey and kIOHIDDeviceUsagePageKey** as the former ones only take ONE usage into account, so when you have a keyboard with mousepad, it might detect only the keyboard and neglects the mouse part, resulting in no mouse
so I hope the code does not break old stuff and just added an additional feature/fix :)

**Comment by goobliata** [comment]
Thanks for the clarification. I don't have a bluetooth mouse but I'll test with a USB mouse and a keyboard/trackpad combo. But by the look of it it hopefully shouldn't break compatibility.

**Comment by goobliata** [comment]
There's a pull request here if anybody wants to test it with a Bluetooth mouse before it gets committed https://github.com/liballeg/allegro5/pull/748

**Comment by goobliata** [comment]
Patch has been applied. Thanks!
