### ISSUE TITLE
Allegro 4

### ISSUE THREAD

**Issue by dimecoin** [liballeg/allegro5#752]
I apologize in advance if this is the incorrect place to ask this question, but does anyone know if there is still an "active" branch of Allegro 4.2 for DOS still being maintained?

I'm having issues cross compiling Allegro 4.2.3.1 sources in linux using DJGPP version 6.3.0 to DOS.

I understand that it's no longer supported, but was hoping to find some old school hobbyists still holding out on the older version.

**Comment by goobliata** [comment]
You're on the right reposity, "4.2" is now "4.4" and is a branch of the allegro5 repo.

**Comment by SiegeLord** [comment]
Nothing to fix here, as far as I can tell. Pop in allegro.cc, #allegro on FreeNode or the mailing list if you have any specific questions!
