### ISSUE TITLE
Can't playing a XM file.

### ISSUE THREAD

**Issue by rmbeer** [liballeg/allegro5#754]
The file is: https://ptpb.pw/kQkW

Tested with './ex_stream_file helios.xm' and ends directly.
Tested with './ex_stream_seek helios.xm' and show a error with stream.

I known that helios.xm not is a corrupt file, i can playing with other players like 'xmp'.

**Comment by SiegeLord** [comment]
I can reproduce this on my system as well, so it's not an issue of Allegro configuration. Must be some incompatibility between the file and DUMB.

**Comment by rmbeer** [comment]
Well, i forget how to fix. But is like you saying, and always work with recompile and install the allegro again, later of any update from the system or from allegro. Most if it is from a separate  source code.

**Comment by SimonN** [comment]
This should be fixed once A5 has DUMB 1.0 support. I've worked on this in the past few days, and helios.xm plays well through A5 with my change. I'll prepare a pull request today!

**Comment by rmbeer** [comment]
It was already solved.
