### ISSUE TITLE
Using clang 8.1 with -flto fails on macOS 10.12

### ISSUE THREAD

**Issue by eglebbk** [liballeg/allegro5#758]
Using -flto with clang 8.1 strips out _al_mangled_main() because it things the function is not used. Removing -flto as a linker flag fixes this, but the following change fixes the issue properly:

> 
> --- alosx.h.old	2016-09-25 03:32:06.000000000 +0200
> +++ alosx.h	2017-05-12 14:08:51.000000000 +0200
> @@ -53,7 +53,7 @@
>     #ifndef ALLEGRO_NO_MAGIC_MAIN
>        #define ALLEGRO_MAGIC_MAIN
>        #if __GNUC__ >= 4
> -         #define main __attribute__ ((visibility("default"))) _al_mangled_main
> +         #define main __attribute__ ((visibility("default"),used)) _al_mangled_main
>        #else
>           #define main _al_mangled_main
>        #endif
>

**Comment by SiegeLord** [comment]
Made a pull request with this change, will merge if it passes tests. Is that you, Evert? Nice to have a commit from you if so :).
