### ISSUE TITLE
al_load_audio_stream() can only be played once

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#765]
If a stream loaded using `al_load_audio_stream()` plays to completion, it can't be replayed.  Trying to play it after it has finished playback will simply have no effect.  `al_rewind_audio_stream()` has no effect either.

**Comment by SiegeLord** [comment]
I can't reproduce this. I used `ex_stream_seek` on wav/ogg/flac/mod and they all could be restarted after they reached the end. Note that once the stream does reach the end it is stopped, so after calling `al_rewind_audio_stream` it needs to be set to play again.

**Comment by fatcerberus** [comment]
> Note that once the stream does reach the end it is stopped, so after calling al_rewind_audio_stream it needs to be set to play again.

Yes, I was aware of that.  Even setting it to play again didn't work for me, so I ended up implementing a system where streams that had reached the end were reloaded from disk, but obviously that's inefficient so I would prefer to avoid it:
https://github.com/fatcerberus/minisphere/blob/master/src/minisphere/audio.c#L466-L469

When I encountered this bug originally, I took a look at Allegro's source and it seemed like the thread that feeds the stream terminates once the file ends; Allegro doesn't restart the thread if you play it again, causing no sound.  So maybe that's been fixed and I didn't realize it...?

I'll try `ex_stream_seek` and report back.

**Comment by fatcerberus** [comment]
Hm, `ex_stream_seek` seems to work properly (even if I disable looping), and there are no stream-reloading shenanigans in it that I can see.  So it's possible the bug was fixed. 😄

**Comment by fatcerberus** [comment]
Yeah, this got fixed somewhere along the way; reloading streams like I was doing in Allegro 5.0 no longer appears to be necessary.  Closing the issue.

**Comment by fatcerberus** [comment]
The commit that fixed the bug is 3a5a3c9cbb57b31d2db815d7b39b57c828eb09c6, over a year ago.  How I missed that I have no idea 😝
