### ISSUE TITLE
al_lock/unlock_sample_id

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#766]
`al_play_sample` API has a fatal flaw in that once a sound is played, you cannot alter its volume/pan etc. Naturally we could add a ton of APIs to do that on `ALLEGRO_SAMPLE_ID`, but that seems very unfortunate. As an alternative, I propose two new functions:

```c
ALLEGRO_SAMPLE_INSTANCE* al_lock_sample_id(ALLEGRO_SAMPLE_ID id);
void al_unlock_sample_id(ALLEGRO_SAMPLE_ID);
```

`al_lock_sample_id` returns the underlying sample instance allowing you to call all the sample instance APIs on it while marking the sample id as unavailable for future `al_play_sample` calls. `al_unlock_sample_id` returns it back to the pool.

**Comment by fatcerberus** [comment]
I like this proposal.  Adding duplicate APIs for working with sample IDs is a bad way to go (Allegro 5 API is very not-bloated right now and it'd be nice to keep it that way :), and locking to get at lower-level details is already a familiar concept in the Allegro API, so this would work well, I think.
