### ISSUE TITLE
cmake generation broken on Linux at a minimum

### ISSUE THREAD

**Issue by pinballkeefer** [liballeg/allegro5#782]
Our team has been working on migrating from Allegro 5.1.9 to the latest 5.2.  Everything appeared mostly OK, but we were seeing a couple of unusual issues.

After much debugging and tracing and help from freenode:#allegro, there appears to be a major difference in cmake generation.

In Allegro 5.1.13 and previous, when you execute "cmake .." from a "build" directory as per the typical README instructions, the effective root of the build is in the "build" directory.  Most source and include files listed in dependencies reference "../src" or "../include".  This makes sense, as src is not copied into the build directory.

In the current version of 5.2, after running "cmake .." as above, the dependencies appear to treat the parent directory as root.  All dependencies are listed as "src/" and "include/".

The biggest problem with this is that "include/allegro5/platform/alplatf.h" is now referencing the default aplatf.h from source root instead of the generated aplatf.h in build.  Since aplatf.h is generated during cmake, this completely invalidates any configuring that is done.

The reason this was even noticed is that, for example, none of the ALLEGRO_XWINDOWS_WITH_* defines are set, meaning a lot of calls such as al_get_num_video_adapters do not work as expected because there is no XWINDOWS_WITH_ set at all, so none of those systems are called.

In Allegro 5.1.13, aplatf.h is the ONLY file listed (correctly) as dependent on the build directory of pretty much every file instead of the source root (build/..) directory.

I'm still researching this, but I have zero cmake experience.  I can see there are cmake changes between 5.1.13 and 5.2.2, but I can't understand the ramifications of those changes yet.  If I can provide additional information to help clarify the situation, let me know.

**Comment by pinballkeefer** [comment]
Ugh.  A coworker previously had, unbeknownst to me, typed cmake in sourceroot and that corruption was never cleared out until I finally blew away the entire directory and redid everything from scratch.

**Comment by beoran** [comment]
Yeah, I did that once too by mistake and it took me a while to figure it
out. For a project like Allegro definitely always use a separate build
directory.
