### ISSUE TITLE
Vertex buffer creation randomly fails (OpenGL)

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#786]
I found out that in miniSphere, `al_create_vertex_buffer()` often fails after a hundred or so calls.  This used to be fine because I had a fallback to keep vertices in software, so I didn't notice the failures.  I recently made it a hard error if VBO creation fails, and now I'm seeing games randomly failing with VO creation errors.

I have a GTX 1070 on my test machine, with 8 GB of VRAM, so I don't think I'm running out of memory.  We're talking very small buffers here, between 4-100 vertices.  Allegro is initialized in OpenGL mode; I haven't tested with D3D.

**Comment by fatcerberus** [comment]
Something interesting I noticed is that, if I run miniSphere under the debugger and set a breakpoint in the error path, then Set Next Statement to try creating the vertex buffer again, it will succeed.  Normal execution will then resume for a bit longer until it fails again.  Some kind of race condition, I wonder?

**Comment by fatcerberus** [comment]
I wonder if this might be a case of missing error checking somewhere.  `glGetError()` is effectively a global variable and doesn’t get cleared until you actually call it, so it might be returning an error from some unrelated earlier operation that wasn’t checked:
http://9bitscience.blogspot.com/2013/05/error-checking-in-opengl.html?m=1

I’ll do some experiments later to verify if this is the cause.

**Comment by fatcerberus** [comment]
I've verified that calling `al_create_vertex_buffer()` a second time allows the operation to succeed, so my theory on `glGetError()` seems to be correct.  If this is the case, it means we're leaking buffer objects since the buffer was actually successfully created but the call is returning NULL.

A quick hack fix would be to call `glGetError()` in a loop before buffer creation to clear any errors.  I'll try that later and see if it works.

**Comment by fatcerberus** [comment]
Yep, it's an OpenGL error that wasn't cleared from an earlier call.  If anyone else is experiencing this, a workaround is, before calling `al_create_vertex_buffer()`, to do:
```c
while (glGetError() != GL_NO_ERROR);
```

I'm still investigating exactly which call causes the original error flag to be set.

**Comment by SiegeLord** [comment]
Hmm... we should add a debug-mode only call to glGetError in more places/everywhere.
