### ISSUE TITLE
al_create_audio_stream() improper handling of frequency

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#790]
Creating a stereo stream seems to require doubling the frequency, otherwise the sound plays back at half speed.  At first I thought this was a bug in my mp3 decoder, but I've encountered this same behavior with two completely different decoders, so it looks like an Allegro bug.

**Comment by SiegeLord** [comment]
I just tried with with `ex_saw` and everything worked correctly. Are you populating the fragment buffers correctly? A stereo buffer requires 2x as many values in it.

**Comment by fatcerberus** [comment]
> A stereo buffer requires 2x as many values in it.

Yes, I was aware.  The mp3 decoder claims to be returning stereo float data @ 44khz, but if I populate a stereo stream initialized as (44100, 32, 2) the audio plays at half speed.  If I initialize instead as (88200, 32, 2) it sounds normal.

But I'll try `ex_saw` and see what happens.

**Comment by fatcerberus** [comment]
Huh, well `ex_saw` just generates a rising saw wave, so I couldn't say what it's "supposed" to sound like to know if the result is wrong.  The problem in my case is that the audio is being played, but not at the right speed unless I double the frequency.

**Comment by SiegeLord** [comment]
For `ex_saw` I switched it to stereo, adjusted the buffer population code to generate 2 samples instead of 1 and I got the same waveform in the channels (verified by recording via audacity) as the original mono code. Is your stream filling source available somewhere?

**Comment by fatcerberus** [comment]
Sure.  The stream is created here:
https://github.com/fatcerberus/minisphere/blob/v4.7.1/src/minisphere/audio.c#L602-L614
`stream_new()` has been called with `frequency` = 44100 and `channels` = 2.  Audio data in question is likewise 44100Hz stereo.

`stream_buffer()` just stuffs whatever you give it into a growable temporary buffer:
https://github.com/fatcerberus/minisphere/blob/v4.7.1/src/minisphere/audio.c#L688-L704

`update_stream()` is called from my event loop every tick and asks for a free fragment.  If it gets one it fills it from the buffer above:
https://github.com/fatcerberus/minisphere/blob/v4.7.1/src/minisphere/audio.c#L779-L784

**Comment by fatcerberus** [comment]
Hm, maybe I could make a dump of the decoded audio and we could diagnose it that way.

**Comment by fatcerberus** [comment]
I may have found the problem: There was an error in miniSphere's JS layer that caused the SoundStream constructor to ignore the "number of channels" argument and always create a mono stream.  I'll do a bit more testing to verify if that was indeed the cause and if that turns out to be what happened, I'll close this bug.

**Comment by SiegeLord** [comment]
Any luck with this?

**Comment by fatcerberus** [comment]
Sorry, I was in the middle of some extensive refactoring and hadn't gotten around to trying again.  I'm testing it again now to see what happens.

**Comment by fatcerberus** [comment]
Hm, nope.  My test code in miniSphere was:

```js
window = global;
RequireScript('@/lib/aurora.js');
RequireScript('@/lib/mp3.js');

let fs = new FileStream('music/chartreuse.mp3', FileOp.Read);
let mp3Data = fs.read(fs.fileSize);
let asset = AV.Asset.fromBuffer(mp3Data);
let stream = null;
asset.get('format', format => {
        // note: Aurora.js always decodes to float32
	stream = new SoundStream(format.sampleRate, 32,  // 32bit = float32
	                         format.channelsPerFrame);
});
while (stream == null && Sphere.run());
stream.play(Mixer.Default);
asset.on('data', buffer => {
	stream.buffer(buffer);
	Sphere.sleep(0.005);  // run event pump
});
asset.start();
```

This causes the distortion mentioned in the original issue.  However, if I change the stream setup to:
```js
	stream = new SoundStream(format.sampleRate * 2, 32,  // 32bit = float32
	                         format.channelsPerFrame / 2);
```

Then it sounds normal, if somewhat tinny.  I've double- and triple-checked my fragment buffer usage, everything looks fine.  So I'm baffled.

**Comment by fatcerberus** [comment]
I'll see if I can isolate this to a standalone repro case, to remove my own streaming code from the equation.

**Comment by fatcerberus** [comment]
Okay, I still get the distortion even after having saved the output of the mp3 decoder to a file and then feeding it directly to an audio stream, with no abstraction in between.  Here's my test harness:

```c
ALLEGRO_VOICE* voice = al_create_voice(44100, ALLEGRO_AUDIO_DEPTH_INT16, ALLEGRO_CHANNEL_CONF_2);
ALLEGRO_MIXER* mixer = al_create_mixer(44100, ALLEGRO_AUDIO_DEPTH_INT16, ALLEGRO_CHANNEL_CONF_2);
al_attach_mixer_to_voice(mixer, voice);
al_set_voice_playing(voice, true);
al_set_mixer_playing(mixer, true);
ALLEGRO_AUDIO_STREAM* stream = al_create_audio_stream(2, 1000, 44100, ALLEGRO_AUDIO_DEPTH_FLOAT32, ALLEGRO_CHANNEL_CONF_2);
al_attach_audio_stream_to_mixer(stream, mixer);
al_set_audio_stream_playing(stream, true);
size_t size;
uint8_t* data;
FILE* f = fopen("mp3.bin", "rb");
long filesize = (fseek(f, 0, SEEK_END), ftell(f));
fseek(f, 0, SEEK_SET);
fread(data, 1, filesize, f);
fclose(f);
void* buffer;
while (size > 0) {
	if (buffer = al_get_audio_stream_fragment(stream)) {
		memcpy(buffer, data, (size_t)fmin(size, 4000));
		data += (size_t)fmin(size, 4000);
		al_set_audio_stream_fragment(stream, buffer);
	}
}
```

And here's some raw output from Aurora.js mp3 decoder, ostensibly 44.1kHz stereo:
https://drive.google.com/open?id=0BxPKLRqQOUSNNUNRM1RISExXVUU

**Comment by fatcerberus** [comment]
What doesn't make sense to me is that the acodec addon uses `al_create_audio_stream()` under-the-hood and those work fine.  So I thought maybe this was specifically related to float32 streams, but I remember having this problem with a decoder that outputs int16 samples too...

**Comment by fatcerberus** [comment]
I'm starting to think there's a fundamental misunderstanding on my part with the way stereo streams work.  I was under the impression the channels were interleaved, however it seems that might not be the case.  This code, when run in my engine, produces a 1kHz sine wave for 1 second:

```js
	const Tau = 2 * Math.PI;
	var freq = 1000;
	var ch = 1;
	var len = 1.0;
	var ss = new SoundStream(44100, 32, ch);
	var buf = new Float32Array(44100 * len * ch);
	for (i = 0; i < 44100 * len; ++i) {
		for (j = 0; j < ch; ++j) {
			buf[i * ch + j] = Math.sin(Tau * freq * i / 44100);
		}
	}
	ss.write(buf);
	ss.play(Mixer.Default);
```

If I change `ch` to 2, the sound becomes broken up; it's still recognizable as 1kHz, but plays for twice as long.

It's not specific to float32; I get the same result if I adapt the code above to use int16.

**Comment by fatcerberus** [comment]
Figured it out, the bug was my fault after all - `samples` parameter (fragment size) is *samples per channel*, I misunderstood it as being the overall number of samples and calculated the size of a fragment as:
```c
stream->fragment_size = 1024 * sample_size;
```

So I was only half-filling each buffer, which was the cause of the "playing through a box fan at half speed" effect.  That's also why mono streams worked fine - that fragment size calculation is correct for a single channel.

Closing the ticket now, not an Allegro bug.
