### ISSUE TITLE
CMake deprecation warning

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#804]
Just happened to notice CMake 3.9.1 spits out this warning when building Allegro:
> CMake Deprecation Warning at CMakeLists.txt:23 (cmake_policy):
>  The OLD behavior for policy CMP0026 will be removed from a future version
> of CMake.
>
>  The cmake-policies(7) manual explains that the OLD behaviors of all
> policies are deprecated and that a policy should be set to OLD only under
> specific short-term circumstances.  Projects should be ported to the NEW
>  behavior and not rely on setting a policy to OLD.

**Comment by tbass** [comment]
When I see it correctly, Allegro wants at least a 2.8.5 CMake
`cmake_minimum_required(VERSION 2.8.5 FATAL_ERROR)`
but the deprecation warning and corresponding new functionality was introduced in CMake 3.x

So should the minimal CMake of Allegro upgrade to 3.x?

**Comment by dos1** [comment]
Just for reference: https://cmake.org/cmake/help/v3.0/policy/CMP0026.html

It should be checked where and why Allegro reads the LOCATION property, and if necessary, it should be replaced with $<TARGET_FILE> generator expression. As far as I can see, this expression seems to be supported by CMake 2.8.5 as well, so there should be no need for raising the version requirement.
