### ISSUE TITLE
Reusing ids with different menus leads to confusion with respect to event sources.

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#816]
This is due to Allegro using the id to do the reverse lookup to the menu item that generated the event.

Two action points here:

- [ ] document the status quo better
- [ ] try to fix it. On every platform except Windows we have complete control over the id type.

**Comment by fatcerberus** [comment]
For Windows maybe we could use a randomly generated "real ID" (or based on a counter even) along with a lookup table to map the user-provided ID back to the actual system ID.

**Comment by SiegeLord** [comment]
That's a pretty good idea, if all else fails.
