### ISSUE TITLE
Make bypassing the compositor optional.

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#818]
Currently on X, we bypass the compositor unconditionally:

https://github.com/liballeg/allegro5/blob/master/src/x/xdisplay.c#L249

while this makes sense for fullscreen games, this is a bit disruptive for windowed ones. It makes sense to me to make this configurable. The way this can be surfaced to users is via the system config, something like this:

```ini
[x11]
# Can be fullscreen_only, always, never
bypass_compositor = fullscreen_only
```

Alternatively, this could be a display option, but I don't know what this looks like on non-X platforms.

**Comment by fatcerberus** [comment]
Is this the reason why when I'm debugging with GDB, moving the game window while paused at a breakpoint doesn't move the display image?

**Comment by SiegeLord** [comment]
It's a possibility, worth a try.
