### ISSUE TITLE
MSVC compile warn

### ISSUE THREAD

**Issue by LazierCode** [liballeg/allegro5#832]
I'm Windows7 OS + MSVC 2017.
Build Allegro5 project generates warning messages:
Linker Tools Warning LNK4042:object specified more than once; extras ignored.
I found two identical file name in the project.(whaptic.c and whaptic.cpp).
My solution is to change any one file name.
I wonder if other compilers in the other platforms will produce this warning, or will there be a better solution?

**Comment by beoran** [comment]
Hmm, looks like MSVC doesn't like the fact that there is a C and A C++ file with the same name. Under MinGW, this wasn't a problem. Anyway, I will make a fix for this.

**Comment by SiegeLord** [comment]
Fixed by #836.
