### ISSUE TITLE
Allegro.cc registration broken

### ISSUE THREAD

**Issue by Liam-Ryan** [liballeg/allegro5#834]
Hi there, 

I'm unable to contact anyone at allegro.cc without registering and I can't register so I'm hoping someone here can help. 

I tried signing up with google and after successfully linking to google I got "The user 'myemailaddress' is not recognised" even after refreshing and clearing cookies. 

I figured that sso might be broken so registered manually with the same email address. I received a registration mail but when I try to login it says my credentials are invalid. 

After this I tried to sign up with my alternative email address that I use for dev only and I'm now seeing a 403 error on the registration page, probably due to too many attempts? 

The usernames I tried to manually create on the site are "Tubealloy" for my personal mail ( that I also attempted to link) and "pleasework" for the attempt at second registration that ended in a 403. Would have been between 12pm and 12.23pm GMT

**Comment by SiegeLord** [comment]
I've sent a message to the site's administrator, maybe it'll get resolved.

Meanwhile, you can try asking your questions here, the [mailing list](https://listengine.tuxfamily.org/lists.liballeg.org/allegro-developers/) or our [IRC channel](http://liballeg.org/irc.html). Sorry for the mess.

**Comment by wini3d** [comment]
This is still an issue. I am getting a 403 forbidden message, generated password and logging using OpenID does not work as well.
