### ISSUE TITLE
Compile warnings on NDK-Build

### ISSUE THREAD

**Issue by LazierCode** [liballeg/allegro5#838]
I try cross compile Allegro5 use ndk-build for windows 7.(target android api - 26,NDK_TOOLCHAIN_VERSION is clang.BUILD_STATIC_LIBRARY mode)
everything is good at the moment except for a few warning message.
although I've tried to remove the warning, I don't know if it's the best action.
![warning](http://www.codelazier.com/2017-10-05_121939.png)

add code "#include <unistd.h>" in the "include/allegro5/platform/alandroid.h" file.

![warning2](http://www.codelazier.com/2017-10-05_122003.png)

modify code "src/debug.c" in line 324:
 (void)__android_log_print(ANDROID_LOG_INFO, "allegro",
            "%s",static_trace_buffer);
is OK!

![warning3](http://www.codelazier.com/2017-10-05_122015.png)

The problem doesn't seem to be serious. I simply ignored it. Conflict with system definitions?

**Comment by SiegeLord** [comment]
Did you resolve the warnings somehow? If they're real, we'd like to fix them.

**Comment by elias-pschernig** [comment]
I made PR #843 to fix all three warnings (and some others).
