### ISSUE TITLE
Opus stream play no sound on android

### ISSUE THREAD

**Issue by LazierCode** [liballeg/allegro5#842]
On my win7 OS, everything is OK! (DirectSound)
On my android mobile,mod,ogg is OK,but opus play no sound! (OpenSL)
After a lot of tests, I found that before the first broadcast, 1.0sec had a sound, and then it was silent.
Debug in Android Studio logcat messages,there are many kcm_stream.c:641 "Out of buffers."
On win7 OS,only once, at the start of the playing.
I'm not sure if it's my android or NDK compile problem.
But I'll follow up.

**Comment by LazierCode** [comment]
Use an official sample opus file, is OK!
But using my own music to convert to opus, the playback will always repeat the loop in the previous 0.5sec.
It could be opus codec problems. Keep track...

**Comment by LazierCode** [comment]
Repeating the loop before 0.5sec is because this is code:
al_set_audio_stream_playmode(stream,ALLEGRO_PLAYMODE_LOOP);
If it is ALLEGRO_PLAYMODE_ONCE, the previous 0.5sec ends only if the play is played.
I'm not sure whether this is a allegro5 problem or a opus problem, but it seems that allegro5 is more likely to have a problem, according to the official 'sample' opus file and in any way correct on the windows.

**Comment by SiegeLord** [comment]
Sorry, I am confused. Does it mean that you think there is a bug in libopus?

**Comment by LazierCode** [comment]
I will follow up, but it seems that libopus is more likely. If the problem occurs at allegro5, I will submit the report again
