### ISSUE TITLE
FYI: The current Windows binary releases are all completely useless, as they were built without the --static-libgcc and --static-libstdc++ flags enabled...

### ISSUE THREAD

**Issue by BenGrasset** [liballeg/allegro5#850]
As such they're dependent on libwinpthread-1.dll and libstdc++6.dll, neither of which are included in the archive, meaning they cannot actually be used for anything. You need to either set the static flags (not sure why you wouldn't have in the first place?) or include the necessary DLLs.

**Comment by SiegeLord** [comment]
For the binaries that have the static runtime, you pick the binaries with the 'static' in their name, e.g. `allegro-x86_64-w64-mingw32-gcc-7.2.0-posix-seh-static-5.2.3.0.zip`. If that still happens with those, then something is broken.

**Comment by SiegeLord** [comment]
I've verified that that is indeed the case, the `-static` binaries don't require the runtime libraries.
