### ISSUE TITLE
Window sizing issues on macOS Sierra

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#851]
One of my macOS testers, @rhuanjl, has encountered an odd window-sizing bug in Allegro 5.2.3 on macOS Sierra which is eerily similar to past bug reports.

In short, windowed games are rendered too small:
![](https://media.discordapp.net/attachments/356367887880945666/371636782019641345/Screen_Shot_2017-10-22_at_13.31.29.png?width=760&height=601)

...while fullscreen is drawn too large and the image is cropped:
![](https://cdn.discordapp.com/attachments/356367887880945666/371689038924742658/Screen_Shot_2017-10-22_at_16.59.15.png)

Reverting to Allegro 5.2.2 fixed the issue, so this is a regression in the latest release.

**Comment by SiegeLord** [comment]
Huh, how is that FPS counter drawn on the bottom right of the first image? Is this on a retina display?

**Comment by fatcerberus** [comment]
Display is retina, yes.

Here's my flip code including the FPS counter rendering:
https://github.com/fatcerberus/minisphere/blob/master/src/minisphere/screen.c#L323-L343

**Comment by koro-xx** [comment]
I confirm this issue... all my code is having the same problem (in a macbook retina - macos sierra).
This is either a problem introduced in 5.2.3.1, or related to how homebrew builds allegro.
I have 5.2.3.1 built with homebrew and 5.2.3.0 static (manually built),
and I only see this issue when linking against the homebrew version.

**Comment by dos1** [comment]
Would you be able to provide a minimal example that triggers this bug? With it, it should be trivial to bisect Allegro between 5.2.2 and 5.2.3 if it's really a regression, or test it with various builds of the same version, if it somehow turns out to be homebrew related.

**Comment by fatcerberus** [comment]
For what it’s worth I don’t think this is homebrew-specific, per se, as I’m almost positive my macOS tester builds Allegro from source in-house.  Unfortunately I don’t own a Mac myself 🙁

**Comment by koro-xx** [comment]
This code produces a big  red window with a green rectangle half the size in the upper left corner (when it should produce an entirely green window):

```
#include <allegro5/allegro.h>
#include <allegro5/allegro_primitives.h>
 
int main(void)
{
    ALLEGRO_DISPLAY *disp;
    int xsize = 500, ysize = 500;
 
    al_init();
    al_init_primitives_addon();
 
    disp = al_create_display(xsize,ysize);
    al_set_target_backbuffer(disp);
    al_clear_to_color(al_map_rgb(255,0,0));
    al_draw_filled_rectangle(0,0,xsize, ysize, al_map_rgb(0,255,0));
    al_flip_display();
    al_rest(5);
 
    return 0;
}
```

**Comment by koro-xx** [comment]
I'm willing to bet the problem was introduced here: https://github.com/liballeg/allegro5/commit/43ce41bcead4debb23f8f500d8005598ac0a2557

**Comment by koro-xx** [comment]
More specifically, this:
https://github.com/liballeg/allegro5/commit/43ce41bcead4debb23f8f500d8005598ac0a2557#diff-2d6bd78adf023706fb4fd92f43d6044bR2177
