### ISSUE TITLE
Windows: Pixel lines dropped when showing display_menu

### ISSUE THREAD

**Issue by utz82** [liballeg/allegro5#860]
When an ALLEGRO_MENU attached to the display, some arbitrary pixel lines (but always the same ones) will be partially skipped when drawing to the display, and mouse coordinates will go out of sync.

![pixbug_win_menuless](https://user-images.githubusercontent.com/5324866/33173330-06fd5ea8-d054-11e7-929f-95a3d2b3b51a.png)
![pixbug_win_with_menu](https://user-images.githubusercontent.com/5324866/33173533-cac39f78-d054-11e7-8fb7-c27e3cf86b25.png)

It seems at least Win 7 up to Win 10 is affected. Linux and OS X are unaffected.
To reproduce, get the program shown above at https://github.com/utz82/bintracker.
The relevant code to disable the menu is in gui/gui.cpp:110.

As far as I can tell, this is the same issue as mentioned here: https://www.allegro.cc/forums/thread/617007

**Comment by SiegeLord** [comment]
I made a change to try to fix this, see #861.

The gist is that on Windows, menu is drawn on the same area as you typically draw on, which meant that the drawable area got shrunk (either cut off, or nearest-neighbour scaling which results in thiose missing lines). The change does the resize for you, so hopefully it's not something you should need to worry about now.

**Comment by utz82** [comment]
Unfortunately the fix doesn't work for me, it's still squashing the same pixels.
I tried setting the ALLEGRO_RESIZABLE display flag just to be sure, but it didn't help either.

**Comment by SiegeLord** [comment]
There was a subtle race condition that I've now fixed. Could you try again? I also tried bintracker locally, and it appeared to fix the issue for me.

**Comment by utz82** [comment]
I can confirm that this fixes the issue. Sorry again for the delay.

**Comment by SiegeLord** [comment]
Nice, thanks for confirming!
