### ISSUE TITLE
Problem with installing Allegro

### ISSUE THREAD

**Issue by Valach1** [liballeg/allegro5#862]
Hello, 

I have problem installing and setting up Allegro to work with CodeBlocks. (In Windows 7). Sorry, that I am posting here but it looks like the allegro forum is down and I cannot solve my problem.

1. I have downloaded Codeblocks codeblocks-16.01-setup.exe - (without MinGW) http://www.codeblocks.org/downloads/26 .

2. I have download MinGW get setup and throught MinGW Installation Manager I selected and installed mingw32-base (version 2013072200) and mingw32-gcc-g++ (version 6.3.0-1).

3. In CodeBlocks in settings-> compiler -> toolchain executables I used auto-detect and it detected my MinGW installation path.

I tested it, I can build and run C/C++ code so this works.

Now I want to use allegro.

4. I have followed getting started thread on allegro wiki https://wiki.allegro.cc/index.php?title=Getting_Started for Windows is suggested use pre built binaries so I choose Allegro 5.2 binary package http://liballeg.org/download.html#windows 

I downloaded allegro-i686-w64-mingw32-gcc-7.2.0-posix-dwarf-dynamic-5.2.3.0.zip . I unpacked it and placed allegro folder in my disk root directory. 

Then I followed this thread https://wiki.allegro.cc/index.php?title=Windows,_Code::Blocks_and_Allegro_5 [Windows, Code::Blocks and Allegro 5].

5. I  have create a now project and then added new cpp file as instruction says.
I have set search directories in project-> build option -> search directories - > compiler ->and pointed it to allegro\include, in linker tab to allegro\lib in linker settings to allegro\lib\liballegro_monolith.dll.a.

6. I switch to release in codeblocks and clicked build and run button. It created exe file of my application but at run time it requested allegro_monolith-5.2.dll so I copied it from allegro\bin to folder where is exe file. When I clicked run it requested libwinpthread-1.dll. I didnt find it in allegro folder so I copied it from another program directory (inkscape).

After I clicked run it give me this error: This application was unable to start correctly (0xc000007b). Click OK to close the application.

What I did wrong? For every advice I will be grateful.

P.S - I dont know if somebody noticed that but some images in Windows, Code::Blocks and Allegro 5 thread are missing.

**Comment by fatcerberus** [comment]
0xc000007b apparently means “bad image”, i.e. an executable or DLL is corrupted.  Seems like maybe something is wrong on your system?  No idea.

**Comment by Valach1** [comment]
Thanks for quick reply, I already figured it out. I was using different version of MinGW than used allego library. Downloading a related MinGW solved my problem.

**Comment by Valach1** [comment]
But I mean that Allegro tutorials about instalation should be more novice friendly, not everybody is a programmer some people takes programming as hobby (like me) and dont understed things like matching compiler for pre-builded binary files, setting IDE etc ... I would appreciate more tutorials for begginers.

**Comment by SiegeLord** [comment]
Yes, absolutely we should. Could you say where you got the MinGW you got it working with? The tested setup is to use MSYS2, but I'm curious what else works.

**Comment by Valach1** [comment]
Yes of course. 
I have downloaded allegro library package with name: 

> allegro-i686-w64-mingw32-gcc-7.2.0-posix-dwarf-dynamic-5.2.3.0.zip 

So I deduce from its name that used compiler was mingw32-gcc and its specific version was 7.2.0-posix-dwarf. 

So I searched in google this query 

> mingw32-gcc-7.2.0-posix-dwarf

And I have found this:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/7.2.0/threads-posix/dwarf/

I have choosen: 

> i686-7.2.0-release-posix-dwarf-rt_v5-rev1.7z
