### ISSUE TITLE
al_transform_coordinates_3d doesn't work with perspective matrices

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#863]
I'm not sure how to fix this regarding the API compatibility, so I'll just open an issue instead. If you tell me what to do I can make a PR afterwards ;)

When using transformation matrix with fourth column different than "0 0 0 1" (like the one made by `al_perspective_transform`), `al_transform_coordinates_3d` doesn't take the fourth coordinate (w) into account, resulting in invalid data.

Either:
* `al_transform_coordinates_3d` should already return values transformed to Cartesian coordinates (divided by w)
* `al_transform_coordinates_3d` should be modified to also return the fourth value (w), so user can divide the others (x, y, z) by himself
* documentation should take a note about situations with non-one w, like perspective transforms, so users won't try to use this function when it won't work and will do the calculations by themselves

**Comment by elias-pschernig** [comment]
Option 1 could in theory break existing code (but why someone would use this function when the [3][3] value is not 1 I don't know...). It also would raise the question why al_transform_coordinates should not behave in the same way, al_transform_coordinates should work 100% the same, just not return the z value.

Option 2 makes sense to me, but I think it should be a new function called al_transform_coordinates_3d_projective or similar.

Option 3 we definitely should do, for both al_transform_coordinates and al_transform_coordinates_3d. Neither of them takes the 4th column (the trans->m[*][3] values) into account at all, they basically only work on a 4x3 part of the 4x4 matrix.

**Comment by elias-pschernig** [comment]
This would be my suggested function:
`
void al_transform_coordinates_3d_projective(const ALLEGRO_TRANSFORM *trans,
   float *x, float *y, float *z)
{
   float rx, ry, rz, rw;
   ASSERT(trans);
   ASSERT(x);
   ASSERT(y);
   ASSERT(z);

   #define M(i, j) trans->m[i][j]

   rx = M(0, 0) * *x + M(1, 0) * *y + M(2, 0) * *z + M(3, 0);
   ry = M(0, 1) * *x + M(1, 1) * *y + M(2, 1) * *z + M(3, 1);
   rz = M(0, 2) * *x + M(1, 2) * *y + M(2, 2) * *z + M(3, 2);
   rw = M(0, 3) * *x + M(1, 3) * *y + M(2, 3) * *z + M(3, 3);

   #undef M

   *x = rx / rw;
   *y = ry / rw;
   *z = rz / rw;
}
`

**Comment by SiegeLord** [comment]
I prefer `al_transform_coordinates_4d`, we can add a separate function for doing the divide, if necessary, it's more composable that way.

**Comment by fatcerberus** [comment]
Correct me if I'm wrong, but when using a projection matrix, doesn't the GPU do the perspective divide automatically?

**Comment by SiegeLord** [comment]
It does, but this for the case where you're doing stuff manually via `al_transform_coordinates`.

**Comment by elias-pschernig** [comment]
Ok, I added a PR which adds al_transform_coordinates_4d plus a convenience wrapper which calls it with a w coordinate set to 1 and then doing the division for you.

**Comment by dos1** [comment]
Hah, I just tried to use `al_hold_bitmap_drawing` with 3D transformed bitmaps and guess what - it all breaks spectacularly, as it uses `al_transform_coordinates(al_get_current_transform(), x, y);` under the hood :D (at least with OpenGL backend, haven't checked the others)

This raises the severity of the issue a bit IMO.
