### ISSUE TITLE
al_set_new_bitmap_samples not working?

### ISSUE THREAD

**Issue by AmauryPERMER** [liballeg/allegro5#875]
I'm working on a little project where I'm rendering to a bitmap as a buffer to render on screen (this way I can render primitives to the buffer then the buffer in the middle of the screen) but even though I'm using #define ALLEGRO_UNSTABLE and "al_set_new_bitmap_samples(4)" before creating the bitmap with "al_create_bitmap(w, h);" seems not working for me (I'm using al_set_new_display_flags(ALLEGRO_OPENGL); too)
to render on the buffer I'm using this:

```
void draw_to_buffer(ALLEGRO_BITMAP *&buffer, ALLEGRO_DISPLAY *&display)

	static float x = 0;
	
	al_set_target_bitmap(buffer);

	al_draw_filled_rectangle(0,0, 506, 900, al_map_rgb(130, 80, 120));
	al_draw_filled_circle(x, 200, 100, al_map_rgb(12, 138, 129));
	al_draw_filled_triangle(0, 0, 100, 0, 50, 100, al_map_rgb(12, 138, 129));
	
	al_draw_filled_rectangle(0, 0, 506, 143, al_map_rgb(12, 138, 129));
	al_draw_filled_rectangle(0, 757, 506, 900, al_map_rgb(12, 138, 129));

	al_draw_filled_circle(mouseX, mouseY, 10, al_map_rgba_f(1, 1, 1, 1));

	x += 2.7;
	if(x > 506 + 100)
		x = -250;

	
	al_set_target_backbuffer(display);
}
```
Everything on the buffer has jaggies but outside of the buffer I get perfectly smooth primitives due to:
```
al_set_new_display_option(ALLEGRO_SAMPLE_BUFFERS, 2, ALLEGRO_SUGGEST); 
al_set_new_display_option(ALLEGRO_SAMPLES, 4, ALLEGRO_SUGGEST); 
```

**Comment by fatcerberus** [comment]
@AmauryPERMER I guess you solved the issue?
