### ISSUE TITLE
al_install_audio() is 0 when A5 app is quicklaunched from Windows 7/8 taskbar (dsound.cpp seems to depend on display)

### ISSUE THREAD

**Issue by SimonN** [liballeg/allegro5#877]
In Windows 7/8, you can pin application shortcuts to the taskbar. If you run an Allegro 5 app from such a pinned taskbar icon, there is a chance that `al_install_audio` returns 0. The same app would run with sound when you doubleclick the executable in file browser.

My Windows testers can reproduce with Allegro 5.2.3.1 binary releases in Lix (my own game with Allegro 5). Lix is too big an example, and I still have to get their feedback on a short, self-contained example program.

Still, I'm starting to believe this is an Allegro issue, not an issue in my game, because other Allegro 5 users ran into the same problem:
* [A.cc thread from 2016: al_install_audio fails when started from quick launch bar](https://www.allegro.cc/forums/thread/616302)
* [Recent feedback from my Lix players](https://www.lemmingsforums.net/index.php?topic=3594.0). They crash because I blissfully called further A5 audio even after logging that `al_install_audio() == 0`. The crash is a bug in Lix, I should handle the failure better. But the `al_install_audio() == 0` in the first place is this reported issue.

I'll try to get more info from my testers with a small example program and Allegro debugging libraries.

**Comment by SimonN** [comment]
Okay, new insights from the 2nd thread.

**Workaround: In your Allegro-5-using code, create your display first, only then initialize the sound driver. Explanation below.**

First, this is Windows-specific. It feels like a race bug, but not reproducibe on Linux, even when starting many instances of native Linux A5 app and Windows A5 app through Wine simultaneously.

We looked at the Windows code for the sound driver, and found this in `addons/audio/dsond.cpp` lines 266 and 741, the DirectX sound driver:
```
/* FIXME: The window specified here is probably very wrong. NULL won't work either. */
hr = device->SetCooperativeLevel(GetForegroundWindow(), DSSCL_PRIORITY);
```
The sound driver seems to assume that a display is already running.

Examining this theroy, I found that indeed, my non-working usercode initialized sound first, then the display. I swapped the usercode to initialize the display first, and the bug vanished at once for both Windows testers. They could run the game from the quicklaunch bar or by doubleclicking, everything worked.

**Comment by fatcerberus** [comment]
`GetForegroundWindow()` is definitely the wrong function here, as the game might be started without focus and in that case the foreground window would belong to an entirely different process.  But the comment also states that `NULL` won't work, so that forces us to pass a valid window handle... hmm.

I wonder if this is somehow related to #852.

**Comment by fatcerberus** [comment]
Does the bug affect Windows 10 also?

**Comment by SimonN** [comment]
Yes! I've gotten a Windows 10 user to reproduce this. I've let him pin Lix to the taskbar, then run it from there. The bug has a higher chance to hit when you try to run two instances of the game:

<Akseli> hey, I did it now again
<Akseli> right after closing Lix I did the double clicking pretty quickly after that, a crash and no Lix ran
<Simon> oooh perfect

I've asked him to send me a sceenshot, and indeed, it's the same stacktrace (crash in audio functions) that I have seen earlier this week from the Windows 8 users.

Afterwards, I've let Akseli test **my workaround:** When you run several instances of the game in quick succession, it's not perfect on Windows 10 -- sometimes, the game can still not initialize the audio driver, even though I create the display first per instance, only then load the driver in that instance. But with the issue in Allegro 5, for running only a single instance of Lix in isolation, my workaround should still be much better than the original code that initialized sound first, then display.

**Comment by SimonN** [comment]
And from Windows 7, we now have a detailed crash report with Allegro debugging libraries. `allegro.log` contains for the taskbar crash (with shortened path for the Lix root directory):
```
stdio    D         file_stdio.c:109  file_stdio_fopen                 [   0.00000] opening C:\...\LixD-master\bin\allegro5.cfg r
system   W            wsystem.c:792  _al_win_safe_load_library        [   0.00000] PathFindOnPath failed to find shcore.dll
system   D            wsystem.c:788  _al_win_safe_load_library        [   0.00000] PathFindOnPath found: C:\Windows\system32\user32.dll
system   D            wsystem.c:699  load_library_at_path             [   0.00000] Calling LoadLibrary C:\Windows\system32\user32.dll
system   I            wsystem.c:702  load_library_at_path             [   0.00000] Loaded C:\Windows\system32\user32.dll
system   I             system.c:263  al_install_system                [   0.00000] Allegro version: 5.2.3
dtor     D               dtor.c:196  _al_register_destructor          [   0.00014] added dtor for timer 000214E8, func 696363E1
dtor     D               dtor.c:196  _al_register_destructor          [   0.00697] added dtor for queue 0002FB00, func 69625C77
dtor     D               dtor.c:196  _al_register_destructor          [   0.00704] added dtor for queue 0002FB80, func 69625C77
audio-dsound I           dsound.cpp:255  _dsound_open                     [   0.00707] Starting DirectSound...
audio-dsound D           dsound.cpp:264  _dsound_open                     [   0.02727] DirectSoundCreate8 succeeded
audio-dsound E           dsound.cpp:269  _dsound_open                     [   0.02733] SetCooperativeLevel failed: DSERR_INVALIDPARAM
audio    E              audio.c:23   _al_set_error                    [   0.02734] No audio driver can be used. (error code: 1)
```
This is further evidence for our theory about `addons/audio/dsound.cpp` in [my second post](https://github.com/liballeg/allegro5/issues/877#issuecomment-358342919).

**Comment by fatcerberus** [comment]
My guess is that in some cases (especially when done quickly) the taskbar steals focus away from the game and therefore GetForegroundWindow() is the desktop—which doesn’t belong to our process and so the initialization fails.

**Comment by fatcerberus** [comment]
The fix that immediately comes to mind is to have the dsound subsystem create a hidden window of its own and use the handle to that when calling `SetCooperativeLevel`.

**Comment by SiegeLord** [comment]
Wow, amazing work Simon. I like the invisible window idea, also suggested here: https://stackoverflow.com/questions/6714111/how-to-provide-a-hwnd-to-directsound-setcooperativelevel-in-a-console-program

**Comment by SiegeLord** [comment]
Or, as another simple option, `GetDesktopWindow`. Still need more research as to what is truly correct.

**Comment by fatcerberus** [comment]
`GetDesktopWindow` will return a handle that doesn't belong to our process, which I think is what's already happening now sometimes with `GetForegroundWindow`, causing the failures.  So that's not an option.

**Comment by SimonN** [comment]
> Wow, amazing work Simon.

Thanks for the accolade, I'll share it with Forestidia and ccexplore (both from Lemmings Forums): From their own motivation, they dug into the Allegro source, came up with the theory, questioned recent changes in Lix that made the bug hit more often, and produced the `allegro.log` above.

---

> have the dsound subsystem create a hidden window of its own and use the handle to that

If the hidden window spawns reasonably quickly and doesn't pollute the Alt+Tab window-switching dialog, then that's a nice option.

In a pinch, maybe use the HWND from the most recent `al_create_display` that still exists, and only spawn the hidden window when there is no such existing Allegro window? Or would that introduce more nasty coupling between display and sound code, maybe even race bugs?

**Comment by SiegeLord** [comment]
> GetDesktopWindow will return a handle that doesn't belong to our process, which I think is what's already happening now sometimes with GetForegroundWindow, causing the failures. So that's not an option.

It might not be so clear cut. I tested it with GetDesktopWindow on my Win7, and everything continued to work. Perhaps the real reason GetForegroundWindow fails to work is not that it's the non-Allegro window per-se, but some either ephemeral or invalid window that is created as part of launching of Allegro applications or perhaps it even returns NULL. I looked around a bit, and using GetDesktopWindow seems to be a common approach. I can't really find much documentation for it though, which is concerning.

**Comment by SiegeLord** [comment]
I am still having trouble reproducing this anywhere. I can even initialize the audio addon without ever creating the display (it doesn't play audio though /until/ I create it). Could one of you attempt to try the GetDesktopWindow trick and see if it fixes it for you?

**Comment by SimonN** [comment]
I don't have a Windows machine myself, and my Windows testers have never built Allegro from source -- I'm hesitant to ask them to build Allegro. >_>;

I assume you have already tried to quicklaunch an A5 app several times in rapid succession, and that the A5 app initializes sound first, only then graphics.

**Comment by SiegeLord** [comment]
How do they get the final binaries? Can I supply you a new Nuget package, or mingw dlls?

**Comment by SimonN** [comment]
I supply DLLs. Thus, MinGW DLLs with the change should work, I'll forward those.

**Comment by SiegeLord** [comment]
Alright, here are the hacked DLLs: https://www.dropbox.com/s/8gvperzu2zghlxb/allegro_dsound_test.zip?dl=0

in addition to trying GetDesktopWindow, it'll also log what is returned by GetForegroundWindow (I suspect it might return NULL). This will show up in allegro.log.

**Comment by SimonN** [comment]
Forestidia tried your hacked DLLs with Lix 0.9.8 on Windows 7.

This Lix 0.9.8 was *before* my workaround (that workaround creates A5 window before initializing A5 sound) and thus creates sound first, then window. Lix 0.9.8 initialized properly, did not crash (it would crash had audio init failed) and played sound and music.

The relevant part of `allegro.log`:
```
stdio    D         file_stdio.c:109  file_stdio_fopen                 [   0.00000] opening C:\[...]\LixD-0.9.8test\bin\allegro5.cfg r
system   W            wsystem.c:792  _al_win_safe_load_library        [   0.00000] PathFindOnPath failed to find shcore.dll
system   D            wsystem.c:788  _al_win_safe_load_library        [   0.00000] PathFindOnPath found: C:\Windows\system32\user32.dll
system   D            wsystem.c:699  load_library_at_path             [   0.00000] Calling LoadLibrary C:\Windows\system32\user32.dll
system   I            wsystem.c:702  load_library_at_path             [   0.00000] Loaded C:\Windows\system32\user32.dll
system   I             system.c:263  al_install_system                [   0.00000] Allegro version: 5.2.3
dtor     D               dtor.c:196  _al_register_destructor          [   0.00020] added dtor for timer 00311508, func 696363E1
dtor     D               dtor.c:196  _al_register_destructor          [   0.00760] added dtor for queue 0031FB00, func 69625C77
dtor     D               dtor.c:196  _al_register_destructor          [   0.00767] added dtor for queue 0031FB80, func 69625C77
audio-dsound I           dsound.cpp:256  _dsound_open                     [   0.00770] Starting DirectSound...
audio-dsound D           dsound.cpp:265  _dsound_open                     [   0.03848] DirectSoundCreate8 succeeded
audio-dsound I           dsound.cpp:269  _dsound_open                     [   0.03852] Foreground window 0001007C
audio-dsound I           dsound.cpp:273  _dsound_open                     [   0.03854] Desktop window 00010010
audio    I              audio.c:347  do_install_audio                 [   0.03865] Using DirectSound driver
audio-dsound D           dsound.cpp:305  _dsound_allocate_voice           [   0.03871] Allocating voice
audio-dsound D           dsound.cpp:364  _dsound_allocate_voice           [   0.03873] Allocated voice
dtor     D               dtor.c:196  _al_register_destructor          [   0.03874] added dtor for voice 0031FE90, func 6544CBC4
dtor     D               dtor.c:196  _al_register_destructor          [   0.03876] added dtor for mixer 00B243D8, func 654488F8
audio-dsound D           dsound.cpp:460  _dsound_start_voice              [   0.03878] Starting voice
audio-dsound D           dsound.cpp:488  _dsound_start_voice              [   0.03879] CreateSoundBuffer
audio-dsound D           dsound.cpp:496  _dsound_start_voice              [   0.04051] CreateSoundBuffer succeeded
audio-dsound D           dsound.cpp:502  _dsound_start_voice              [   0.04057] Starting _dsound_update thread
audio-dsound I           dsound.cpp:512  _dsound_start_voice              [   0.04074] Voice started
```

**Comment by SimonN** [comment]
Here's a second `allegro.log` from Forestidia running Lix 0.9.8 against your hacked DLLs on Windows 7, this time with NULL for the foreground window.

Again, with your fix, Lix (without workaround) ran well (didn't crash), initialized audio and played music as intended.

```
system   W            wsystem.c:792  _al_win_safe_load_library        [   0.00000] PathFindOnPath failed to find shcore.dll
system   D            wsystem.c:788  _al_win_safe_load_library        [   0.00000] PathFindOnPath found: C:\Windows\system32\user32.dll
system   D            wsystem.c:699  load_library_at_path             [   0.00000] Calling LoadLibrary C:\Windows\system32\user32.dll
system   I            wsystem.c:702  load_library_at_path             [   0.00000] Loaded C:\Windows\system32\user32.dll
system   I             system.c:263  al_install_system                [   0.00000] Allegro version: 5.2.3
dtor     D               dtor.c:196  _al_register_destructor          [   0.00018] added dtor for timer 00E41508, func 696363E1
dtor     D               dtor.c:196  _al_register_destructor          [   0.00914] added dtor for queue 00E4FB00, func 69625C77
dtor     D               dtor.c:196  _al_register_destructor          [   0.00922] added dtor for queue 00E4FB80, func 69625C77
audio-dsound I           dsound.cpp:256  _dsound_open                     [   0.00925] Starting DirectSound...
audio-dsound D           dsound.cpp:265  _dsound_open                     [   0.03667] DirectSoundCreate8 succeeded
audio-dsound I           dsound.cpp:269  _dsound_open                     [   0.03672] Foreground window 00000000
audio-dsound I           dsound.cpp:273  _dsound_open                     [   0.03673] Desktop window 00010010
audio    I              audio.c:347  do_install_audio                 [   0.03681] Using DirectSound driver
audio-dsound D           dsound.cpp:305  _dsound_allocate_voice           [   0.03688] Allocating voice
audio-dsound D           dsound.cpp:364  _dsound_allocate_voice           [   0.03689] Allocated voice
dtor     D               dtor.c:196  _al_register_destructor          [   0.03691] added dtor for voice 00E4FE90, func 6544CBC4
dtor     D               dtor.c:196  _al_register_destructor          [   0.03693] added dtor for mixer 00D143D8, func 654488F8
audio-dsound D           dsound.cpp:460  _dsound_start_voice              [   0.03694] Starting voice
audio-dsound D           dsound.cpp:488  _dsound_start_voice              [   0.03696] CreateSoundBuffer
audio-dsound D           dsound.cpp:496  _dsound_start_voice              [   0.03931] CreateSoundBuffer succeeded
audio-dsound D           dsound.cpp:502  _dsound_start_voice              [   0.03937] Starting _dsound_update thread
audio-dsound I           dsound.cpp:512  _dsound_start_voice              [   0.03954] Voice started
```

**Comment by fatcerberus** [comment]
Hm, so I guess `GetDesktopWindow()` is an acceptable thing to pass to the function.  I guess it's fine as long as you don't request exclusive-mode (which we don't seem to).

**Comment by SiegeLord** [comment]
Alright, thanks a lot Simon. What I'll do here is add a configuration option to select which window to use for initialization (in case this universally good), but default it to the desktop window.
