### ISSUE TITLE
Flickering border artifacts when using "al_set_clipping_rectangle"

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#888]
*Copied from [a locked thread on forum](https://www.allegro.cc/forums/thread/617185) by @drcouzelis*

I have my video game display coded so that "ALLEGRO_FULLSCREEN_WINDOW" mode will do the largest integer scale possible, then use "al_set_clipping_rectangle" to preserve the aspect ratio.

I expect the "borders" of the clipping rectangle to be black, but instead, they flicker with what looks like screen artifacts. (See attachments)

Here is an excerpt from my display code:
```c
al_set_new_display_flags(ALLEGRO_FULLSCREEN_WINDOW);

/* Initialize the one and only global display for the game */
display = al_create_display(width * scale, height * scale);

al_clear_to_color(al_map_rgb(0, 0, 0));

/* Scale and center the display as big as possible on this screen */                                               
set_display_transform(scale, offset_x, offset_y, fullscreen);
                                                                                                                       
/* Crop the drawing area, to not accidentally draw in the black borders */                                         
al_set_clipping_rectangle(offset_x, offset_y, display_width * scale, display_height * scale);
```
Full code here:

https://github.com/drcouzelis/colorwandcastle/blob/master/src/display.c

Is there something I can do to prevent the seizure-inducing flickering around the display area?

My computer:
Arch Linux (current)
Radeon HD 5450, with open source "radeon" driver

**Comment by fatcerberus** [comment]
I believe with OpenGL, the contents of the backbuffer are undefined after a flip, so you need to clear it completely every frame.  If you never change the clipping rectangle than `al_clear_to_color()` will only clear inside of it, so this is expected unfortunately. :(

**Comment by drcouzelis** [comment]
Thank you for this information! (And for making the bug report from my forum post.)

I applied the change you recommended, to clear the display, then flip the display, then clear the display (second buffer) again.

`al_clear_to_color(al_map_rgb(0,0,0));
al_flip_display();
al_clear_to_color(al_map_rgb(0,0,0));`

This appears to resolve the issue for me. If I see it pop up again, I might apply the other code you posted. Thanks!

**Comment by dos1** [comment]
@fatcerberus fair enough, let's add a note to docs then.
@drcouzelis actually, as it's driver dependent, you might want to do it now if you ever distribute your code to other people ;)
