### ISSUE TITLE
Make the source code links specify a specific commit, so they don't get out of date.

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#889]
Right now they're liable to get outdated pretty easily.

**Comment by fatcerberus** [comment]
Wouldn’t it be better to use a tag rather than a commit hash for the link?

**Comment by SiegeLord** [comment]
I couldn't figure out how to use the tag, although I did add an option to specify the ref manually. We do want the hash in general, as we have a cronjob that regenerates the docs regularly for the master branch (which doesn't have tags).
