### ISSUE TITLE
Implement mp3 support

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#900]
mp3 patents have expired in the U.S. as of last year:
https://en.wikipedia.org/wiki/MP3#Licensing,_ownership_and_legislation

Fraunhofer have also terminated their licensing program for the format.  Seems like a good opportunity to add mp3 support to Allegro, at least assuming we can find a liberally-licensed decoder.

**Comment by fatcerberus** [comment]
Holy crud, a public domain mp3 decoder?!  It’s like a dream come true, I swore the only liberally licensed decoder was the old Fluendo codec (MIT), everything else I could find was GPL.

**Comment by fatcerberus** [comment]
Ironically, mp3 is the most widely supported audio format for `<audio>` on the web—better supported than vorbis even (according to wikipedia’s support tables)—so the one format I can’t easily support on the desktop is also the best fit for the web.  Go figure.

**Comment by pmprog** [comment]
I'm in the middle of testing minimp3, and I've got it to load an MP3 as a sample and play it. Just need to look at implementing it as a stream, then if people are interested, I'll upload to my github repo and send a pull request

**Comment by SiegeLord** [comment]
Hey @pmprog, any progress on this? Do you need any assistance? We'd be glad with just a sample implementation even before the streaming one is working.

**Comment by pmprog** [comment]
Hi @SiegeLord I'm afraid real life has got much in the way, and hasn't got any further than our chat on IRC, where you asked about un-vendoring the minimp3 source.

The current version of the code is here, and it can play mp3 "samples", but not streams.
https://github.com/pmprog/allegro5

**Comment by pmprog** [comment]
I spent some time left night trying to use libmpg123 as an approach to not vendoring minimp3, but i had no luck whatsoever!

**Comment by pmprog** [comment]
Doesn't support streams yet, but can load mp3s as samples and play them
https://github.com/liballeg/allegro5/pull/1037
Not had time to look into the streaming side yet

**Comment by SiegeLord** [comment]
I think the current MP3 support (#1037 and #1065) is now good enough to close this.
