### ISSUE TITLE
MacOS Native Dialogs: "View" Menu Items Won't Trigger Event

### ISSUE THREAD

**Issue by NewCreature** [liballeg/allegro5#914]
In my current project, I have a View menu with a couple of options that I add using `al_append_menu_item()`. When I run my program, the View menu has additional items that are automatically added by the OS before my menu items. This ultimately causes my menu items not to trigger the `ALLEGRO_EVENT_MENU_CLICK` event.

I was able to work around the issue by changing the way menu items are looked up when they are activated by the MacOS platform code. I've attached my patch, but I'm not sure if my solution is the best way to handle this issue. With my fix, your menu items will always trigger the `ALLEGRO_EVENT_MENU_CLICK` events. It's kind of crude, but it is guaranteed to work no matter what MacOS does to the menus behind your back.

[osx_menu_item_index_patch.diff.zip](https://github.com/liballeg/allegro5/files/2131404/osx_menu_item_index_patch.diff.zip)

**Comment by SiegeLord** [comment]
I like it, committed as https://github.com/liballeg/allegro5/commit/07f911c8bacef82c23d16f4d6b2c7cb6867e5cd9. Thanks!
