### ISSUE TITLE
ALLEGRO_ALPHA_TEST doesn't work with OpenGL

### ISSUE THREAD

**Issue by danpla** [liballeg/allegro5#924]
al_set_render_state() accepts int as ALLEGRO_ALPHA_TEST_VALUE, but glAlphaFunc() expects a float in range 0..1, which usually set to 0.5 for alpha testing.

**Comment by dos1** [comment]
I wonder if it works at all. I'd say that it doesn't.

OpenGL:
```
glAlphaFunc(_gl_funcs[r->alpha_function], r->alpha_test_value);
```
DirectX:
```
disp->device->SetRenderState(D3DRS_ALPHAREF, (int)(r->alpha_test_value * 255));
```

Both calls clearly expect `r->alpha_test_value` to be `float`, while `internal/aintern_display.h` defines it as `int` and it's assigned directly from the `ALLEGRO_ALPHA_TEST_VALUE`:
```
      case ALLEGRO_ALPHA_TEST_VALUE:
         display->render_state.alpha_test_value = value;
         break;
```

Nice catch :D
