### ISSUE TITLE
al_compose_transform() - Is this pre- or post-multiplied?

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#949]
The documentation for `al_compose_transform()` says:

> The effect of applying the combined transform will be as if first applying `trans` and then applying `other` and not the other way around.

This suggests post-multiplication (I think?), however in Oozaru I've implemented compose using the algorithm from glMatrix.js which is explicitly noted to be post-multiply... and I've had to combine the matrices in the opposite order compared to Allegro to get the correct result:

* Oozaru:
https://github.com/fatcerberus/oozaru/blob/9c7f807a4719ac7fe9c48ed617f1d18a19f22c26/src/galileo.ts#L371-L372
* Allegro:
https://github.com/liballeg/allegro5/blob/3b2afd1a63a526f8b177097f31ca23e357f54414/src/opengl/ogl_draw.c#L455-L456

So does Allegro actually *pre-multiply*?  i.e. is the combined matrix in fact `other*trans` rather than `trans*other`?

**Comment by allefant** [comment]
Both. The documentation is correct, the examples it gives work just like it says. But Allegro does all matrix operations backwards compared to OpenGL, and I think it also transposes the memory location of all matrix elements. So while that is very confusing if you use both, nothing really dictates which way to multiply (or where in memory to store matrix elements).

You can read the introduction at the top of this page: https://liballeg.org/a5docs/trunk/transformations.html which I think explains it all.

**Comment by fatcerberus** [comment]
> For those who know the matrix algebra going behind the scenes, what the transformation functions in Allegro do is "pre-multiply" the successive transformations.

Thanks, this is what I wanted to know: mathematically it’s composing the matrices by multiplying the new one in from the left.  I knew Allegro did transformations in the order you specified, what I didn’t know was what that looked like from a maths perspective.  Now I know: pre-multiply = post-transform.  Matrix math is confusing!
