### ISSUE TITLE
Occasional blank window on OSX 10.14

### ISSUE THREAD

**Issue by SiegeLord** [liballeg/allegro5#960]
This source occasionally fails to render anything:

```c
#include <allegro5/allegro5.h>
#include <allegro5/allegro_image.h>

int main(int argc, char* argv[]) {

	al_init();
	al_install_keyboard();
	al_init_image_addon();
	al_set_new_display_flags(ALLEGRO_RESIZABLE);
	ALLEGRO_TIMER* timer = al_create_timer(1.0 / 30.0);
	ALLEGRO_EVENT_QUEUE* queue = al_create_event_queue();
	ALLEGRO_DISPLAY* display = al_create_display(960 * 2, 640 * 2);
	ALLEGRO_BITMAP* car = al_load_bitmap("assets/sprites/car.png");

	al_register_event_source(queue, al_get_keyboard_event_source());
	al_register_event_source(queue, al_get_timer_event_source(timer));

	bool redraw = true;
	bool done = false;
	ALLEGRO_EVENT event;

	al_start_timer(timer);

	while (true) {

		al_wait_for_event(queue, &event);

		switch (event.type) {
			case ALLEGRO_EVENT_TIMER:
				redraw = true;
				break;
			case ALLEGRO_EVENT_KEY_DOWN:
			case ALLEGRO_EVENT_DISPLAY_CLOSE:
				done = true;
				break;
		}

		if (done) {
			break;
		}

		if (redraw && al_is_event_queue_empty(queue)) {

			al_clear_to_color(al_map_rgb(0, 0, 0));
			al_draw_bitmap(car, 100, 100, 0);
			al_flip_display();
			redraw = false;

		}

	}

	al_destroy_bitmap(car);
	al_destroy_display(display);
	al_destroy_timer(timer);
	al_destroy_event_queue(queue);

	return 0;

}
```

Interestingly, the user reported that adding the `al_set_config_value` to enable logging before `al_init` appeared to fix things. Sounds related to #876, although as can be seen this is a windowed application.

**Comment by slmjkdbtl** [comment]
Not sure if this is related to this: https://github.com/cocos2d/cocos2d-x/issues/19080#issuecomment-435314956, I just tried opening a opengl window with glfw and sdl2, both blank screens, but not occasional.

**Comment by BraveHeart64** [comment]
case ALLEGRO_EVENT_KEY_DOWN: 
Break;
is missing a break statement if I am not mistaken.


Should  the redraw be on the outside of this if statement?
if (redraw && al_is_event_queue_empty(queue)) {

			al_clear_to_color(al_map_rgb(0, 0, 0));
			al_draw_bitmap(car, 100, 100, 0);
		
			redraw = false;

		}
al_flip_redraw();

**Comment by slmjkdbtl** [comment]
I'm totally not familiar with allegro's underlying tech structure but not sure if it's related to macos 10.14.1's underlying opengl problem, some similar problem happens in glfw and sdl (blank screen, not occasional though)

https://github.com/glfw/glfw/issues/1334
https://github.com/cocos2d/cocos2d-x/issues/19080

**Comment by SiegeLord** [comment]
Alright, I guess we'll chalk it up to the OSX bug. Thanks @slmjkdbtl for checking.
