### ISSUE TITLE
Allegro.cc is down

### ISSUE THREAD

**Issue by snoopdouglas** [liballeg/allegro5#961]
There's been a discussion in the forums over the past few days about the site being extremely slow. It now appears to have completely ground to a halt, and any request just spins forever.

I acknowledge this isn't entirely within scope, but I'm posting this here in the hope that someone who has access to the server (maybe only Matthew - I'm unsure) sees this and sorts it out.

**Comment by snoopdouglas** [comment]
Some portions of the site (presumably those on different servers, or that don't use PHP?) are still OK:

* https://wiki.allegro.cc/
* https://www.allegro.cc/manual/5/

**Comment by dos1** [comment]
I keep wondering: what's the relation between allegro.cc and liballeg.org? Especially when I'm duckduckgoing or googling Allegro docs and I keep landing on old allegro.cc docs instead of fresh liballeg.org ones :P

**Comment by fatcerberus** [comment]
Yeah, I have no clue why the Allegro 5.0 docs are still the top result in Google searches when searching by function name.  It’s really annoying because 5.2.x has a bunch of new enumeration constants and such but I actually have to hunt through the search results to find the up-to-date docs that mention them.

**Comment by snoopdouglas** [comment]
Allegro.cc is (I think) technically an independent community, whereas liballeg.org is the official site. We have control of the latter but not the former.

> Yeah, I have no clue why the Allegro 5.0 docs are still the top result in Google searches

Maybe because allegro.cc is more popular than liballeg.org - not sure though. Agreed that they sorely need an update

**Comment by snoopdouglas** [comment]
Forgot to update this. Matthew graced us with his presence in the forums; he's clearly had a look, and the site's been fast for a while now, so closing this

**Comment by snoopdouglas** [comment]
Once again, back up,
