### ISSUE TITLE
Allegro won't compile in Arch Linux

### ISSUE THREAD

**Issue by rvega** [liballeg/allegro5#968]
I also filed this in https://bugs.archlinux.org/task/61007
After upgrading the packages in my Arch system, allegro won´t compile. There are a bunch of openGL functions that are "undeclared" when compiling.

Here's what I did:

git clone https://github.com/liballeg/allegro5.git repo
cd allegro5
mkdir build
cd build
cmake -GNinja ..
ninja

The output of the cmake and ninja steps:
https://gist.github.com/rvega/90e5b48173db35da586c2642e8f67cec
https://gist.github.com/rvega/94c84cddb147cdc89aa264cc18c0280d

**Comment by SiegeLord** [comment]
Maybe related to #967? Could you try the patch there and see if that helps?

**Comment by rvega** [comment]
Yes, that patch fixed it. Thank you!
