### ISSUE TITLE
cmake: finding HarfBuzz is broken

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#979]
```
CMake Error at cmake/FindHarfBuzz.cmake:61 (include):
  include could not find load file:

    /deps/allegro5-dos/cmake/SelectLibraryConfigurations.cmake
Call Stack (most recent call first):
  addons/CMakeLists.txt:97 (find_package)


-- Could NOT find HarfBuzz (missing:  HARFBUZZ_LIBRARY)
```

https://github.com/liballeg/allegro5/blob/a40d30e21802ecf5c9382cf34af9b01bd3781e47/cmake/FindHarfBuzz.cmake#L61

There's no `cmake/SelectLibraryConfigurations.cmake` file in the repository.

**Comment by fatcerberus** [comment]
Somebody must have missed it in code review, HarfBuzz support was added quite recently:
https://github.com/liballeg/allegro5/pull/917

That file is not included in the PR.

**Comment by fatcerberus** [comment]
...actually, it looks like that file might be part of CMake itself which is odd:
https://github.com/Kitware/CMake/blob/master/Modules/SelectLibraryConfigurations.cmake

Maybe they removed it in a recent version...?

**Comment by dos1** [comment]
...or added, as I've seen it on CMake 3.7.2.

However, that `${CMAKE_CURRENT_LIST_DIR}` looks fishy in that case.
